rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL 170_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

---------------------
-- VERSION 0.17.0  --
---------------------

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_TAREAS_ENVIADAS_PDTES');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'LIST_TAREAS_ENVIADAS_PDTES';

SPOOL OFF;
