rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/002_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


CREATE TABLE GE_TIPOS_AGRUPACIONES (TIP_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, N_VERSION NUMBER(19,0), USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, D_DESCRIPCION VARCHAR2(100 CHAR) NOT NULL, N_NIVEL_ANIDAMIENTO NUMBER(19,0) NOT NULL, TIP_TIP_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_TIPOS_AGRUPACIONES_H (TIP_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), L_ACTIVA NUMBER(1,0), D_DESCRIPCION VARCHAR2(255 CHAR), N_NIVEL_ANIDAMIENTO NUMBER(19,0), TIP_TIP_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;


ALTER TABLE GE_COMUNICACIONES_H ADD n_version number(19,0);
ALTER TABLE GE_LOCALIDADES_H ADD n_version number(19,0);
ALTER TABLE GE_MATERIAS_H ADD n_version number(19,0);
ALTER TABLE GE_MOTIVOSRELACION_H ADD n_version number(19,0);
ALTER TABLE GE_PARAMETROS_H ADD n_version number(19,0);
ALTER TABLE GE_PERSONAS_H ADD n_version number(19,0);
ALTER TABLE GE_PERSONASCOMUNICACIONES_H ADD n_version number(19,0);
ALTER TABLE GE_PROVINCIAS_H ADD n_version number(19,0);
ALTER TABLE GE_SEXO_H ADD n_version number(19,0);
ALTER TABLE GE_TIPOEXPEDIENTES_H ADD n_version number(19,0);
ALTER TABLE GE_TIPOSPERSONAS_H ADD n_version number(19,0);
ALTER TABLE GE_REVAUD DROP COLUMN NUM_VERSION;

CREATE TABLE GE_SUJETOS_OBLIGADOS (SUJ_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), T_ABREVIATURA_1 VARCHAR2(5 CHAR), T_ABREVIATURA_2 VARCHAR2(12 CHAR), T_ABREVIATURA_3 VARCHAR2(20 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, C_CODIGO_DIR3 VARCHAR2(50 CHAR), C_CODIGO_POSTAL VARCHAR2(5 CHAR), D_DESCRIPCION VARCHAR2(100 CHAR) NOT NULL, T_DIRECCION VARCHAR2(255 CHAR), T_EMAIL_CONTACTO VARCHAR2(100 CHAR), T_LOCALIDAD VARCHAR2(100 CHAR), N_VERSION NUMBER(19,0), T_NIF VARCHAR2(9 CHAR), N_NIVEL_ANIDAMIENTO NUMBER(19,0) NOT NULL CHECK (N_NIVEL_ANIDAMIENTO<=5), T_ORDEN_VISUALIZACION VARCHAR2(3 CHAR) NOT NULL, SUJ_PRO_ID NUMBER(19,0), SUJ_SUJ_ID NUMBER(19,0), SUJ_TIP_ID NUMBER(19,0) NOT NULL) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_SUJETOS_OBLIGADOS_H (SUJ_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), T_ABREVIATURA_1 VARCHAR2(255 CHAR), T_ABREVIATURA_2 VARCHAR2(255 CHAR), T_ABREVIATURA_3 VARCHAR2(255 CHAR), L_ACTIVA NUMBER(1,0), C_CODIGO_DIR3 VARCHAR2(255 CHAR), C_CODIGO_POSTAL VARCHAR2(255 CHAR), D_DESCRIPCION VARCHAR2(255 CHAR), T_DIRECCION VARCHAR2(255 CHAR), T_EMAIL_CONTACTO VARCHAR2(255 CHAR), T_LOCALIDAD VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0), T_NIF VARCHAR2(255 CHAR), N_NIVEL_ANIDAMIENTO NUMBER(19,0), T_ORDEN_VISUALIZACION VARCHAR2(255 CHAR), SUJ_PRO_ID NUMBER(19,0), SUJ_SUJ_ID NUMBER(19,0), SUJ_TIP_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

SPOOL OFF;
