rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/002_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.2.0 --
-------------------

ALTER TABLE GE_TIPOS_AGRUPACIONES ADD CONSTRAINT GE_TIPAGRUP_TIPAGRUP_FK FOREIGN KEY (TIP_TIP_ID) REFERENCES GE_TIPOS_AGRUPACIONES;
ALTER TABLE GE_TIPOS_AGRUPACIONES_H ADD CONSTRAINT GE_TIPOS_AGRUP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;	

ALTER TABLE GE_SUJETOS_OBLIGADOS ADD CONSTRAINT GE_SUJOBLI_PROVINCIA_FK FOREIGN KEY (SUJ_PRO_ID) REFERENCES GE_PROVINCIAS;
ALTER TABLE GE_SUJETOS_OBLIGADOS ADD CONSTRAINT GE_SUJOBLI_SUJOBLI_FK FOREIGN KEY (SUJ_SUJ_ID) REFERENCES GE_SUJETOS_OBLIGADOS;
ALTER TABLE GE_SUJETOS_OBLIGADOS ADD CONSTRAINT GE_SUJOBLI_TIPAGRUP_FK FOREIGN KEY (SUJ_TIP_ID) REFERENCES GE_TIPOS_AGRUPACIONES;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD CONSTRAINT GE_SUJ_OBLI_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

SPOOL OFF;
