rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/002_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.2.0 --
-------------------

INSERT INTO GE_TIPOS_AGRUPACIONES (TIP_ID, F_CREACION, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO, TIP_TIP_ID, L_ACTIVA, N_VERSION) 
VALUES (S_TIPOAGRUPACION.NEXTVAL, SYSDATE, 'Ámbito', 0, NULL, '1', 0);

INSERT INTO GE_TIPOS_AGRUPACIONES (TIP_ID, F_CREACION, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO, TIP_TIP_ID, L_ACTIVA, N_VERSION) 
VALUES (S_TIPOAGRUPACION.NEXTVAL, SYSDATE, 'Entidad', 1, (SELECT TIP_ID FROM GE_TIPOS_AGRUPACIONES WHERE D_DESCRIPCION = 'Ámbito') , '1', 0);

INSERT INTO GE_TIPOS_AGRUPACIONES (TIP_ID, F_CREACION, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO, TIP_TIP_ID, L_ACTIVA, N_VERSION) 
VALUES (S_TIPOAGRUPACION.NEXTVAL, SYSDATE, 'Organismo', 2, (SELECT TIP_ID FROM GE_TIPOS_AGRUPACIONES WHERE D_DESCRIPCION = 'Entidad') , '1', 0);

INSERT INTO GE_TIPOS_AGRUPACIONES (TIP_ID, F_CREACION, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO, TIP_TIP_ID, L_ACTIVA, N_VERSION) 
VALUES (S_TIPOAGRUPACION.NEXTVAL, SYSDATE, 'Centro', 3, (SELECT TIP_ID FROM GE_TIPOS_AGRUPACIONES WHERE D_DESCRIPCION = 'Organismo'), '1', 0);


-- SE MODIFICAN LAS DESCRIPCIONES DE LAS TABLAS A MODO FRASE Y SE ACTUALIZA LA VERSION
-- SEXO 
UPDATE GE_SEXO SET D_DESCRIPCION = 'Mujer', N_VERSION = 0 WHERE D_DESCRIPCION = 'MUJER';
UPDATE GE_SEXO SET D_DESCRIPCION = 'Hombre', N_VERSION = 0 WHERE D_DESCRIPCION = 'HOMBRE';
-- TIPOS EXPEDIENTES
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Reclamación en materia de derecho de acceso a la información pública.' WHERE D_DESCRIPCION = 'RECLAMACIÓN EN MATERIA DE DERECHO DE ACCESO A LA INFORMACIÓN PÚBLICA.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Denuncia por incumplimiento de las exigencias de publicidad l_activa.' WHERE D_DESCRIPCION = 'DENUNCIA POR INCUMPLIMIENTO DE LAS EXIGENCIAS DE PUBLICIDAD L_ACTIVA.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Reclamación por infracción de la normativa de protección de datos.' WHERE D_DESCRIPCION = 'RECLAMACIÓN POR INFRACCIÓN DE LA NORMATIVA DE PROTECCIÓN DE DATOS.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Notificación de una violación de la seguridad de los datos personales a la autoridad de control.' WHERE D_DESCRIPCION = 'NOTIFICACIÓN DE UNA VIOLACIÓN DE LA SEGURIDAD DE LOS DATOS PERSONALES A LA AUTORIDAD DE CONTROL.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Comunicación a la autoridad de control de la designación, cese o modificación de datos del delegado de protección de datos (dpd).' WHERE D_DESCRIPCION = 'COMUNICACIÓN A LA AUTORIDAD DE CONTROL DE LA DESIGNACIÓN, CESE O MODIFICACIÓN DE DATOS DEL DELEGADO DE PROTECCIÓN DE DATOS (DPD).';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Solicitud de información pública del consejo.' WHERE D_DESCRIPCION = 'SOLICITUD DE INFORMACIÓN PÚBLICA DEL CONSEJO.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Ejercicio de los derechos relativos a la protección de las personas físicas en lo que respecta al tratamiento de los datos personales realizados por el consejo.' WHERE D_DESCRIPCION = 'EJERCICIO DE LOS DERECHOS RELATIVOS A LA PROTECCIÓN DE LAS PERSONAS FÍSICAS EN LO QUE RESPECTA AL TRATAMIENTO DE LOS DATOS PERSONALES REALIZADOS POR EL CONSEJO.';
-- PERSONAS 
UPDATE GE_TIPOSPERSONAS SET D_DESCRIPCION = 'Física', N_VERSION = 0 WHERE D_DESCRIPCION = 'FÍSICA';
UPDATE GE_TIPOSPERSONAS SET D_DESCRIPCION = 'Jurídica', N_VERSION = 0 WHERE D_DESCRIPCION = 'JURÍDICA';

-- SE ACTUALIZA EL N_VERSION PARA QUE COMIENCE EL VERSIONADO CON EL VALOR CERO
UPDATE GE_COMUNICACIONES SET N_VERSION = 0 WHERE D_DESCRIPCION = 'NOTIFIC@';
UPDATE GE_COMUNICACIONES SET N_VERSION = 0 WHERE D_DESCRIPCION = 'POSTAL';
UPDATE GE_COMUNICACIONES SET N_VERSION = 0 WHERE D_DESCRIPCION = 'PENDIENTE DETERMINAR';

SPOOL OFF;
