rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/002_06_GRANTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_TIPOS_AGRUPACIONES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_TIPOAGRUPACION TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_TIPOS_AGRUPACIONES_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_SUJETOS_OBLIGADOS TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_SUJETOS_OBLIGADOS TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_SUJETOS_OBLIGADOS_H TO GE_ROL_GESTOR_DML;

SPOOL OFF;
