rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/004_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

DROP TABLE GE_ELEMENTOS_SERIES CASCADE CONSTRAINTS;
DROP TABLE GE_ELEMENTOS_SERIES_H CASCADE CONSTRAINTS;

DROP TABLE GE_SERIES CASCADE CONSTRAINTS;
DROP TABLE GE_SERIES_H CASCADE CONSTRAINTS;

DROP TABLE GE_EXPEDIENTES_RELACIONADOS CASCADE CONSTRAINTS;
DROP TABLE GE_EXPEDIENTES_RELACIONADOS_H CASCADE CONSTRAINTS;

ALTER TABLE GE_VALORES_DOMINIOS DROP COLUMN N_ORDEN;
ALTER TABLE GE_VALORES_DOMINIOS DROP COLUMN N_NIVEL_ANIDAMIENTO;
ALTER TABLE GE_VALORES_DOMINIOS ADD N_ORDEN NUMBER(19,0) NOT NULL CHECK (N_ORDEN<=3);
ALTER TABLE GE_VALORES_DOMINIOS ADD N_NIVEL_ANIDAMIENTO NUMBER(19,0) NOT NULL CHECK (N_NIVEL_ANIDAMIENTO<=3);

ALTER TABLE GE_PERSONAS   ADD (PER_TIPPER_ID NUMBER(19,0) NOT NULL);
ALTER TABLE GE_PERSONAS_H ADD (PER_TIPPER_ID NUMBER(19,0));
ALTER TABLE GE_PERSONAS   DROP (N_TELEFONO_MOVIL, PER_VALDOM_VIACOM_ID);
ALTER TABLE GE_PERSONAS_H DROP (N_TELEFONO_MOVIL, PER_VALDOM_VIACOM_ID);
ALTER TABLE GE_PERSONAS   RENAME COLUMN N_TELEFONO_FIJO TO N_TELEFONO;
ALTER TABLE GE_PERSONAS_H RENAME COLUMN N_TELEFONO_FIJO TO N_TELEFONO;

DROP TABLE GE_PAISES CASCADE CONSTRAINTS;
DROP TABLE GE_PAISES_H CASCADE CONSTRAINTS;

ALTER TABLE GE_PERSONAS   DROP (PER_PAI_ID, D_DESCRIPCION_MUNICIPIO);
ALTER TABLE GE_PERSONAS_H DROP (PER_PAI_ID, D_DESCRIPCION_MUNICIPIO);

ALTER TABLE GE_SUJETOS_OBLIGADOS   DROP (SUJ_PAI_ID, D_DESCRIPCION_MUNICIPIO);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP (SUJ_PAI_ID, D_DESCRIPCION_MUNICIPIO);

ALTER TABLE GE_PERSONAS   ADD N_CODIGO_POSTAL NUMBER(5,0);
ALTER TABLE GE_PERSONAS_H ADD N_CODIGO_POSTAL NUMBER(5,0);
ALTER TABLE GE_PERSONAS   DROP COLUMN C_CODIGO_POSTAL;
ALTER TABLE GE_PERSONAS_H DROP COLUMN  C_CODIGO_POSTAL;

ALTER TABLE GE_SUJETOS_OBLIGADOS DROP COLUMN SUJ_LOC_ID;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP COLUMN SUJ_LOC_ID;
ALTER TABLE GE_SUJETOS_OBLIGADOS ADD (T_LOCALIDAD VARCHAR(100 CHAR));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (T_LOCALIDAD VARCHAR(100 CHAR));

DROP TABLE GE_OBSERVACIONES_EXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_OBSERVACIONES_EXPEDIENTES_H CASCADE CONSTRAINTS;

SPOOL OFF;