rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/004_UNDO_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

DROP SEQUENCE S_ELEMENTOS_SERIES;

DROP SEQUENCE S_SERIES;

DROP SEQUENCE S_EXPEDIENTES_RELACIONADOS;

DROP SEQUENCE S_PAISES;

DROP SEQUENCE S_OBSERVACIONES_EXPEDIENTES;

SPOOL OFF;