rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/004_UNDO_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONA_TIPOPERSONA_FK FOREIGN KEY (PER_TIPPER_ID) REFERENCES GE_TIPOSPERSONAS;


SPOOL OFF;