rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/001_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.1.0 --
-------------------

DROP TABLE GE_COMUNICACIONES CASCADE CONSTRAINTS;
DROP TABLE GE_COMUNICACIONES_H CASCADE CONSTRAINTS;
DROP TABLE GE_LOCALIDADES CASCADE CONSTRAINTS;
DROP TABLE GE_LOCALIDADES_H CASCADE CONSTRAINTS;
DROP TABLE GE_MATERIAS CASCADE CONSTRAINTS;
DROP TABLE GE_MATERIAS_H CASCADE CONSTRAINTS;
DROP TABLE GE_MOTIVOSRELACION CASCADE CONSTRAINTS;
DROP TABLE GE_MOTIVOSRELACION_H CASCADE CONSTRAINTS;
DROP TABLE GE_PARAMETROS CASCADE CONSTRAINTS;
DROP TABLE GE_PARAMETROS_H CASCADE CONSTRAINTS;
DROP TABLE GE_PERSONAS CASCADE CONSTRAINTS;
DROP TABLE GE_PERSONAS_H CASCADE CONSTRAINTS;
DROP TABLE GE_PERSONASCOMUNICACIONES CASCADE CONSTRAINTS;
DROP TABLE GE_PERSONASCOMUNICACIONES_H CASCADE CONSTRAINTS;
DROP TABLE GE_PROVINCIAS CASCADE CONSTRAINTS;
DROP TABLE GE_PROVINCIAS_H CASCADE CONSTRAINTS;
DROP TABLE GE_REVAUD CASCADE CONSTRAINTS;
DROP TABLE GE_SEXO CASCADE CONSTRAINTS;
DROP TABLE GE_SEXO_H CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOEXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOEXPEDIENTES_H CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOSPERSONAS CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOSPERSONAS_H CASCADE CONSTRAINTS;

SPOOL OFF;
