rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/001_UNDO_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.1.0 --
-------------------

DROP SEQUENCE S_COMUNICACIONES;
DROP SEQUENCE S_LOCALIDADES;
DROP SEQUENCE S_MATERIA;
DROP SEQUENCE S_MOTIVOSRELACION;
DROP SEQUENCE S_PARAMETRO;
DROP SEQUENCE S_PERSONAS;
DROP SEQUENCE S_PERSONASCOMUNICACIONES;
DROP SEQUENCE S_PROVINCIAS;
DROP SEQUENCE S_REVAUD;
DROP SEQUENCE S_SEXO;
DROP SEQUENCE S_TIPOEXPEDIENTE;
DROP SEQUENCE S_TIPOSPERSONAS;

SPOOL OFF;
