rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/003_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

CREATE TABLE GE_DOMINIOS (DOM_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_BLOQUEADO NUMBER(1,0) DEFAULT 0 NOT NULL, C_CODIGO VARCHAR2(15 CHAR) NOT NULL, D_DESCRIPCION VARCHAR2(250 CHAR) NOT NULL, N_VERSION NUMBER(19,0), N_NIVEL_ANIDAMIENTO_MAX NUMBER(19,0) NOT NULL CHECK (N_NIVEL_ANIDAMIENTO_MAX<=3), L_PUNTO_MENU NUMBER(1,0) DEFAULT 0 NOT NULL, L_VISIBLE NUMBER(1,0) DEFAULT 1 NOT NULL) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_DOMINIOS_H (DOM_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_BLOQUEADO NUMBER(1,0), C_CODIGO VARCHAR2(255 CHAR), D_DESCRIPCION VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0), N_NIVEL_ANIDAMIENTO_MAX NUMBER(19,0), L_PUNTO_MENU NUMBER(1,0), L_VISIBLE NUMBER(1,0)) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_VALORES_DOMINIOS (VAL_DOM_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), T_ABREVIATURA VARCHAR2(20 CHAR) NOT NULL, L_ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL, L_BLOQUEADO NUMBER(1,0) DEFAULT 0 NOT NULL, C_CODIGO VARCHAR2(15 CHAR) NOT NULL, D_DESCRIPCION VARCHAR2(250 CHAR) NOT NULL, N_VERSION NUMBER(19,0), N_NIVEL_ANIDAMIENTO NUMBER(19,0) NOT NULL CHECK (N_NIVEL_ANIDAMIENTO<=3), N_ORDEN NUMBER(19,0) NOT NULL CHECK (N_ORDEN<=3), VALDOM_DOM_ID NUMBER(19,0) NOT NULL, VALDOM_VALDOM_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_VALORES_DOMINIOS_H (VAL_DOM_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), T_ABREVIATURA VARCHAR2(255 CHAR), L_ACTIVO NUMBER(1,0), L_BLOQUEADO NUMBER(1,0), C_CODIGO VARCHAR2(255 CHAR), D_DESCRIPCION VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0), N_NIVEL_ANIDAMIENTO NUMBER(19,0), N_ORDEN NUMBER(19,0), VALDOM_DOM_ID NUMBER(19,0), VALDOM_VALDOM_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

ALTER TABLE GE_PERSONAS ADD PER_VALDOM_SEX_ID NUMBER(19,0);
ALTER TABLE GE_PERSONAS ADD PER_VALDOM_TIPPER_ID NUMBER(19,0);
ALTER TABLE GE_PERSONAS_H ADD PER_VALDOM_SEX_ID NUMBER(19,0);
ALTER TABLE GE_PERSONAS_H ADD PER_VALDOM_TIPPER_ID NUMBER(19,0);

CREATE TABLE GE_EXPEDIENTES (EXP_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), T_ETIQUETA1 VARCHAR2(100 CHAR), T_ETIQUETA2 VARCHAR2(100 CHAR), T_ETIQUETA3 VARCHAR2(100 CHAR), F_FECHA_ENTRADA TIMESTAMP NOT NULL, F_FECHA_REGISTRO TIMESTAMP, T_MOTIVO VARCHAR2(500 CHAR), N_VERSION NUMBER(19,0), T_NOMBRE_EXPEDIENTE VARCHAR2(255 CHAR) NOT NULL, T_NUMERO_EXPEDIENTE VARCHAR2(255 CHAR) NOT NULL, T_NUMERO_REGISTRO VARCHAR2(50 CHAR), N_RESOLUCION_WEB NUMBER(19,0) CHECK (N_RESOLUCION_WEB<=1), EXP_VALDOM_CANENT_ID NUMBER(19,0), EXP_VALDOM_MAT_ID NUMBER(19,0), EXP_VALDOM_SIT_ID NUMBER(19,0) NOT NULL, EXP_VALDOM_TIPEXP_ID NUMBER(19,0) NOT NULL, EXP_VALDOM_TIPINF_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT; 
CREATE TABLE GE_EXPEDIENTES_H (EXP_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), T_ETIQUETA1 VARCHAR2(255 CHAR), T_ETIQUETA2 VARCHAR2(255 CHAR), T_ETIQUETA3 VARCHAR2(255 CHAR), F_FECHA_ENTRADA TIMESTAMP, F_FECHA_REGISTRO TIMESTAMP, T_MOTIVO VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0), T_NOMBRE_EXPEDIENTE VARCHAR2(255 CHAR), T_NUMERO_EXPEDIENTE VARCHAR2(255 CHAR), T_NUMERO_REGISTRO VARCHAR2(255 CHAR), N_RESOLUCION_WEB NUMBER(19,0), EXP_VALDOM_CANENT_ID NUMBER(19,0), EXP_VALDOM_MAT_ID NUMBER(19,0), EXP_VALDOM_SIT_ID NUMBER(19,0), EXP_VALDOM_TIPEXP_ID NUMBER(19,0), EXP_VALDOM_TIPINF_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_SUJETOS_OBLIGADOS_EXPDT (SUJ_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(19,0) NOT NULL CHECK (N_PRINCIPAL<=1), SUJ_EXP_ID NUMBER(19,0) NOT NULL, SUJ_SUJ_ID NUMBER(19,0) NOT NULL, SUJ_VALDOM_MOTRELEXPSUJ_ID NUMBER(19,0) NOT NULL) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_SUJETOS_OBLIGADOS_EXPDT_H (SUJ_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(19,0), SUJ_EXP_ID NUMBER(19,0), SUJ_SUJ_ID NUMBER(19,0), SUJ_VALDOM_MOTRELEXPSUJ_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_PERSONAS_EXPEDIENTES (PER_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(19,0) NOT NULL CHECK (N_PRINCIPAL<=1), PER_EXP_ID NUMBER(19,0) NOT NULL, PER_PER_ID NUMBER(19,0) NOT NULL, PER_PER_REPRE_ID NUMBER(19,0), PER_VALDOM_MOTRELEXPPER_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_PERSONAS_EXPEDIENTES_H (PER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(19,0), PER_EXP_ID NUMBER(19,0), PER_PER_ID NUMBER(19,0), PER_PER_REPRE_ID NUMBER(19,0), PER_VALDOM_MOTRELEXPPER_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_MATERIAS_TIPEXPEDIENTES (MAT_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), N_VERSION NUMBER(19,0), MATTIPEXP_VALDOMMAT_ID NUMBER(19,0) NOT NULL, MATTIPEXP_VALDOMTIPEXP_ID NUMBER(19,0) NOT NULL) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_MATERIAS_TIPEXPEDIENTES_H (MAT_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), MATTIPEXP_VALDOMMAT_ID NUMBER(19,0), MATTIPEXP_VALDOMTIPEXP_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

SPOOL OFF;
