rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/003_03_INDICES.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_DOMINIOS ADD CONSTRAINT GE_DOMINIOS_PK PRIMARY KEY (DOM_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_DOMINIOS_H ADD CONSTRAINT GE_DOMINIOS_H_PK PRIMARY KEY (DOM_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_VALORES_DOMINIOS ADD CONSTRAINT GE_VALORES_DOMINIOS_PK PRIMARY KEY (VAL_DOM_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_VALORES_DOMINIOS_H ADD CONSTRAINT GE_VALORES_DOMINIOS_H_PK PRIMARY KEY (VAL_DOM_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_EXPEDIENTES ADD CONSTRAINT GE_EXPEDIENTES_PK PRIMARY KEY (EXP_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_EXPEDIENTES_H ADD CONSTRAINT GE_EXPEDIENTES_H_PK PRIMARY KEY (EXP_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_SUJETOS_OBLIGADOS_EXPDT ADD CONSTRAINT GE_SUJETOS_OBLIGADOS_EXPDT_PK PRIMARY KEY (SUJ_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_SUJETOS_OBLIGADOS_EXPDT_H ADD CONSTRAINT GE_SUJETOS_OBLIGADOSEXPDT_H_PK PRIMARY KEY (SUJ_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_PERSONAS_EXPEDIENTES ADD CONSTRAINT GE_PERSONAS_EXPEDIENTES_PK PRIMARY KEY (PER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERSONAS_EXPEDIENTES_H ADD CONSTRAINT GE_PERSONAS_EXPEDIENTES_H_PK PRIMARY KEY (PER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_MATERIAS_TIPEXPEDIENTES ADD CONSTRAINT GE_MATERIAS_TIPEXPEDIENTES_PK PRIMARY KEY (MAT_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_MATERIAS_TIPEXPEDIENTES_H ADD CONSTRAINT GE_MATERIAS_TIPEXP_H_PK PRIMARY KEY (MAT_ID, REV) USING INDEX TABLESPACE GESTOR_IND;


SPOOL OFF;
