rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/015_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.15.0 --
--------------------

ALTER TABLE GE_CONEXIONES_USUARIOS DROP COLUMN T_IP_CONEXION;
ALTER TABLE GE_CONEXIONES_USUARIOS DROP COLUMN T_EQUIPO_CONEXION;

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN F_FECHA_REGISTRO;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN F_FECHA_REGISTRO;

ALTER TABLE GE_CFG_METADATOS_TRAM DROP COLUMN D_FECHA_REGISTRO;
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP COLUMN D_FECHA_REGISTRO;

-- ------------------

ALTER TABLE GE_EXPEDIENTES DROP COLUMN L_TRAMITACION_ANONIMA;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN L_ABSTENCION_RECUSACION;

ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN L_TRAMITACION_ANONIMA;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN L_ABSTENCION_RECUSACION;


ALTER TABLE GE_DOCUMENTOS   DROP ( F_ULT_EDICION, DOC_USU_EDITA_ID );
ALTER TABLE GE_DOCUMENTOS_H DROP ( F_ULT_EDICION, DOC_USU_EDITA_ID );

ALTER TABLE GE_USUARIOS DROP COLUMN T_UID_SSO;
ALTER TABLE GE_USUARIOS_H DROP COLUMN T_UID_SSO;

---------------------

ALTER TABLE GE_EXPEDIENTES DROP COLUMN T_DESCRIPCION;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN EXP_USR_MOD_DESC;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN F_FECHA_HORA_MOD_DESC;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN F_FECHA_INFRACCION;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN L_INFRACCION_CONT;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN EXP_VALDOM_GRAV;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN F_FECHA_PRESCRIPCIOM;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN F_FECHA_SOLIC_EJ;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN L_RESPUESTA_SOLIC;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN L_RESPUESTA_INSAT;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN F_FECHA_RESP_SOLIC_EJ;
ALTER TABLE GE_EXPEDIENTES MODIFY T_MOTIVO VARCHAR2(4000 CHAR);

ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN T_DESCRIPCION;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN EXP_USR_MOD_DESC;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN F_FECHA_HORA_MOD_DESC;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN F_FECHA_INFRACCION;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN L_INFRACCION_CONT;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN EXP_VALDOM_GRAV;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN F_FECHA_PRESCRIPCIOM;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN F_FECHA_SOLIC_EJ;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN L_RESPUESTA_SOLIC;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN L_RESPUESTA_INSAT;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN F_FECHA_RESP_SOLIC_EJ;
ALTER TABLE GE_EXPEDIENTES_H MODIFY T_MOTIVO VARCHAR2(4000 CHAR);

ALTER TABLE GE_EXPEDIENTES DROP COLUMN EXP_VALDOM_ORIGREC;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN EXP_VALDOM_ORIGREC;

ALTER TABLE GE_EXPEDIENTES DROP COLUMN D_DESC_SEG1;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN D_DESC_SEG2;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN D_DESC_SEG3;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN D_INF_SEG1;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN D_INF_SEG2;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN D_INF_SEG3;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN D_DESC_SEG1;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN D_DESC_SEG2;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN D_DESC_SEG3;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN D_INF_SEG1;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN D_INF_SEG2;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN D_INF_SEG3;




SPOOL OFF;
