rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/016_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

---------------------
-- VERSION 0.16.0  --
---------------------
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SERIESRESOL') AND C_CODIGO = 'RRP';

DELETE FROM GE_ELEMENTOS_SERIES WHERE T_CODIGO_SERIE = 'RRPSEC';

DELETE FROM GE_SERIES WHERE T_CODIGO_SERIE = 'RRPSEC';

-- -------------

UPDATE GE_TIPO_TRAMITE SET T_COMPORTAMIENTO='C000' WHERE T_CODIGO = 'RESREC';

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIPORESOL') AND C_CODIGO = 'REC';

-- ------------

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'ACTO_REC');

DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'ACTO_REC';

UPDATE GE_TIPO_TRAMITE SET T_COMPORTAMIENTO='C001' WHERE T_CODIGO = 'RECP';

--------------

delete from ge_usuarios where T_LOGIN = 'SISTEMA';

----------------------------------------------

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'RCO_VIEW_CAMPOSESP');
DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'RCO_VIEW_CAMPOSESP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'RCO_VIEW_CAMPOSESP';

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'RCE_VIEW_CAMPOSESP');
DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'RCE_VIEW_CAMPOSESP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'RCE_VIEW_CAMPOSESP';

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'PSAN_VIEW_CAMPOSESP');
DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'PSAN_VIEW_CAMPOSESP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'PSAN_VIEW_CAMPOSESP';

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'XPC_VIEW_CAMPOSESP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'XPC_VIEW_CAMPOSESP';

-----------------------------------------

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXPEMPDOC');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'NEW_EXPEMPDOC';

-----------------------------------------

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'RCO_EDIT_RESPEXP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'RCO_EDIT_RESPEXP';

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'RCE_EDIT_RESPEXP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'RCE_EDIT_RESPEXP';

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'PSAN_EDIT_RESPEXP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'PSAN_EDIT_RESPEXP';

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'XPC_EDIT_RESPEXP');
DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'XPC_EDIT_RESPEXP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'XPC_EDIT_RESPEXP';





SPOOL OFF;
