rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/016_UNDO_07_VISTAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.16.0 --
-------------------

	
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GE_LISTADO_RESOLUCIONES" ("RES_ID", "F_CREACION", "F_MODIFICACION", "USU_CREACION", "USU_MODIFICACION", "T_CODIGO_RESOL", "F_FECHA_RESOLUCION", "TIP_RESOL_ID", "TIPO_RESOL", "SENTIDO_ID", "SENTIDO_RESOL", "PER_ID", "NOMBRE_PERSONA", "NIF_PERSONA", "COD_TIPO_PERSONA", "SUJ_ID", "NOMBRE_SUJ_OBLIGADO", "NIF_SUJ_OBLIGADO") AS 
  SELECT 
    R.RES_ID, 
    R.F_CREACION AS F_CREACION,
    R.F_MODIFICACION AS F_MODIFICACION,
    R.USU_CREACION AS USU_CREACION,
    R.USU_MODIFICACION AS USU_MODIFICACION,
    R.T_CODIGO_RESOL, R.F_FECHA_RESOLUCION,
    TIP.VAL_DOM_ID AS TIP_RESOL_ID, TIP.D_DESCRIPCION AS TIPO_RESOL, 
    SEN.VAL_DOM_ID AS SENTIDO_ID, SEN.D_DESCRIPCION AS SENTIDO_RESOL,
    P.PER_ID, 
	CONCAT(CONCAT(CONCAT(CONCAT(P.T_NOMBRE_RAZONSOCIAL, ' '), P.T_PRIMER_APELLIDO), ' '), P.T_SEGUNDO_APELLIDO) AS NOMBRE_PERSONA,
	P.T_NIF_CIF AS NIF_PERSONA, TIPER.C_CODIGO AS COD_TIPO_PERSONA,
    S.SUJ_ID, S.D_DESCRIPCION AS NOMBRE_SUJ_OBLIGADO, S.T_NIF AS NIF_SUJ_OBLIGADO
FROM GE_RESOLUCIONES R
    INNER JOIN GE_VALORES_DOMINIOS TIP ON TIP.VAL_DOM_ID = R.RESOL_VALDOMTIPORESOL_ID
    INNER JOIN GE_VALORES_DOMINIOS SEN ON SEN.VAL_DOM_ID = R.RESOL_VALDOMSENTRESOL_ID
    INNER JOIN GE_RESOL_EXPEDIENTES RE ON (RE.RESEXP_RES_ID = R.RES_ID AND RE.N_PRINCIPAL = 1 )
    INNER JOIN GE_EXPEDIENTES E ON E.EXP_ID = RE.RESEXP_EXP_ID
    LEFT JOIN GE_RESOL_SUJOBL SE ON (SE.RESSUJOBL_RES_ID = R.RES_ID AND SE.N_PRINCIPAL = 1 )
    LEFT JOIN GE_SUJETOS_OBLIGADOS S ON S.SUJ_ID = SE.RESSUJOBL_SUJOBL_ID
    LEFT JOIN GE_RESOL_PERSONA PE  ON (PE.RESPER_RES_ID = R.RES_ID AND PE.N_PRINCIPAL = 1 ) 
    LEFT JOIN GE_PERSONAS P ON P.PER_ID = PE.RESPER_PER_ID
    LEFT JOIN GE_VALORES_DOMINIOS TIPER ON TIPER.VAL_DOM_ID = P.PER_VALDOM_TIPPER_ID;
	
-- -------------------------------------------

  CREATE OR REPLACE VIEW "GE_LISTADO_DOCUMENTOS_EXP_TRAM" AS 
  SELECT
		DE.DOCEXP_ID,DE.DOC_ID,DE.EXP_ID,DE.T_IDEN_DOC,DE.D_DESCRIPCION,DE.D_DESC_ABREV,DE.T_NOMBRE_FICHERO,DE.T_EXTENSION_FICHERO,DE.TIP_DOC_ID,DE.D_DESCRIPCION_TIPO,DE.F_CREACION,DE.F_MODIFICACION,DE.USU_CREACION,DE.USU_MODIFICACION, DE.T_USUARIO_ACCESO, DE.F_FECHA_HORA_ACCESO, DE.L_EDITABLE,DE.L_FIRMADO,DE.L_SELLADO,DE.L_ANONIMIZADO,DE.L_ANONIMIZADO_PARCIAL,DE.L_ACTIVO,DE.CAT_ID,DE.CATEGORIA,DE.N_ORDEN_CAT,
		DET.DETR_ID AS DOC_EXP_TRAM_ID,
		DET.T_ORIGEN AS ORIGEN_DOCEXPTR,
		DET.DETR_TRAMEXP_ID AS TRAM_EXPE_ID,
		TE.TRAM_EXP_TRAMEXPSUP_ID AS TRAM_EXPE_SUP_ID,
		TT.T_CODIGO AS T_CODIGO,
		DTT.D_NUM_RESOLUCION AS NUM_RESOL,
		AGE.AGREXP_ID AS AGR_EXP_ID,
		AGE.D_DESCRIPCION_DOC AS AGRUPACION_EXP,
		AGE.N_ORDEN AS N_ORDEN_AGR_EXP,
		AGE.L_VER_PEST_DOC,
		AGD.N_ORDEN,
		TAR.TAREXP_ID
	FROM GE_LISTADO_DOCUMENTOS_EXP DE 
		INNER JOIN GE_DOCUMENTOS_EXPED_TRAMITES DET ON DE.DOCEXP_ID = DET.DETR_DOCEXP_ID
		INNER JOIN GE_TRAMITE_EXPED TE ON DET.DETR_TRAMEXP_ID = TE.TRAM_EXP_ID
		INNER JOIN GE_TIPO_TRAMITE TT ON TT.TIP_TRA_ID = TE.TRAM_EXP_TIP_TRA_ID
		LEFT OUTER JOIN GE_DETALLE_EXPDTE_TRAM DTT ON TE.TRAM_EXP_ID = DTT.DETEXPTRAM_TRAMEXP_ID
		LEFT OUTER JOIN GE_AGRUP_DOCUMENTOS AGD ON DET.DETR_ID = AGD.AGRDOC_DOC_EXP_TRAM_ID
		LEFT OUTER JOIN GE_AGRUP_EXPEDIENTES AGE ON AGD.AGRDOC_AGREXP_ID = AGE.AGREXP_ID
		LEFT OUTER JOIN (SELECT DISTINCT T.TAREXP_ID, DET_T.DETR_DOCEXP_ID FROM GE_TAREAS_EXPEDIENTE T 
							INNER JOIN GE_VALORES_DOMINIOS TIPT ON T.TAREXP_VALDOM_TAR_ID = TIPT.VAL_DOM_ID
							INNER JOIN GE_DOMINIOS D ON TIPT.VALDOM_DOM_ID = D.DOM_ID
							INNER JOIN GE_DOCUMENTOS_EXPED_TRAMITES DET_T ON DET_T.DETR_ID = T.TAREXP_DOCEXP_TRA_ID
							WHERE T.L_ACTIVA = 1 AND T.T_SITUACION = 'P' 
							AND TIPT.C_CODIGO = 'REV' AND D.C_CODIGO='TAREAS') TAR
						ON DE.DOCEXP_ID = TAR.DETR_DOCEXP_ID;

-- ---------------------------------------

  CREATE OR REPLACE VIEW "GE_EXP_PEREXP_SUJEXP" AS 
  SELECT 
	expe.EXP_ID AS EXP_ID,
	expe.F_CREACION AS F_CREACION,
	expe.F_MODIFICACION AS F_MODIFICACION,
	expe.USU_CREACION AS USU_CREACION,
	expe.USU_MODIFICACION AS USU_MODIFICACION,
	expe.F_FECHA_REGISTRO AS F_FECHA_REGISTRO,
	valortipoexp.T_ABREVIATURA AS T_TIP_EXP,
	expe.T_NUMERO_EXPEDIENTE AS T_NUM_EXPEDIENTE,
	situacionexpe.D_DESCRIPCION AS T_SITUACION,
	expe.F_FECHA_ENTRADA AS T_FECHA_ENTRADA,
	CASE WHEN persona.T_PRIMER_APELLIDO is null THEN persona.T_NOMBRE_RAZONSOCIAL
	ELSE TRIM(CONCAT(CONCAT(TRIM(CONCAT(CONCAT(persona.T_PRIMER_APELLIDO, ' '),persona.T_SEGUNDO_APELLIDO)), ', '), persona.T_NOMBRE_RAZONSOCIAL)) END AS T_PERSONA,
	sujetoobligado.D_DESCRIPCION AS T_SUJETO_OBLIGADO,
    expe.T_NOMBRE_EXPEDIENTE AS T_NOMBRE_EXPEDIENTE,
    LISTAGG('-' ||materia.val_dom_id||'-') WITHIN GROUP (ORDER BY materia.val_dom_id) AS ID_MATERIA,
    LISTAGG('-' ||materia.valdom_valdom_id||'-') WITHIN GROUP (ORDER BY materia.valdom_valdom_id) AS ID_MATERIASUP,
    situacionexpe.L_SIT_FINAL AS FINALIZADOS,
    resptramitacion.D_DESCRIPCION AS T_RESPONSABLE,
	expe.D_SIT_ADICIONAL AS T_SITUACION_ADICIONAL
FROM GE_EXPEDIENTES expe
LEFT OUTER JOIN ge_materias_expdt matexp ON expe.EXP_ID = matexp.MATEXP_EXP_ID
LEFT OUTER JOIN GE_MATERIAS_TIPEXPEDIENTES mattipexp ON matexp.MATEXP_MATTIPEXP_ID = mattipexp.MAT_ID
LEFT OUTER JOIN GE_VALORES_DOMINIOS materia ON materia.VAL_DOM_ID = mattipexp.MATTIPEXP_VALDOMMAT_ID
INNER JOIN GE_VALORES_DOMINIOS valortipoexp ON valortipoexp.VAL_DOM_ID = expe.EXP_VALDOM_TIPEXP_ID 
INNER JOIN GE_VALORES_DOMINIOS valorsituacion ON valorsituacion.VAL_DOM_ID = expe.EXP_VALDOM_SIT_ID 
INNER JOIN GE_PERSONAS_EXPEDIENTES perexpe ON  perexpe.PER_EXP_ID=expe.EXP_ID
INNER JOIN GE_SUJETOS_OBLIGADOS_EXPDT sujetoexpe ON sujetoexpe.SUJ_EXP_ID=expe.EXP_ID
INNER JOIN GE_PERSONAS persona ON persona.PER_ID =perexpe.PER_PER_ID 
INNER JOIN GE_SUJETOS_OBLIGADOS sujetoobligado ON sujetoobligado.SUJ_ID = sujetoexpe.SUJ_SUJ_ID 
INNER JOIN GE_SITUACIONES_EXPEDIENTES situacionexpe ON situacionexpe.SIT_VALDOM_TIPEXP_ID=expe.EXP_VALDOM_TIPEXP_ID 
LEFT OUTER JOIN GE_RESP_TRAMITACION resptramitacion ON expe.EXP_RESTRA_ID =resptramitacion.RESTRA_ID 
WHERE perexpe.N_PRINCIPAL =1 AND sujetoexpe.N_PRINCIPAL =1 
AND situacionexpe.SIT_VALDOM_TIPEXP_ID=expe.EXP_VALDOM_TIPEXP_ID
AND situacionexpe.SIT_VALDOM_SIT_ID=expe.EXP_VALDOM_SIT_ID
group by (expe.EXP_ID,
expe.F_CREACION,
expe.F_MODIFICACION,
expe.USU_CREACION,
expe.USU_MODIFICACION,
expe.F_FECHA_REGISTRO,
valortipoexp.T_ABREVIATURA,
expe.T_NUMERO_EXPEDIENTE,
situacionexpe.D_DESCRIPCION,
expe.F_FECHA_ENTRADA,
	CASE WHEN persona.T_PRIMER_APELLIDO is null THEN persona.T_NOMBRE_RAZONSOCIAL
	ELSE TRIM(CONCAT(CONCAT(TRIM(CONCAT(CONCAT(persona.T_PRIMER_APELLIDO, ' '),persona.T_SEGUNDO_APELLIDO)), ', '), persona.T_NOMBRE_RAZONSOCIAL)) END,
sujetoobligado.D_DESCRIPCION,
expe.T_NOMBRE_EXPEDIENTE,
situacionexpe.L_SIT_FINAL,
expe.T_NOMBRE_EXPEDIENTE, resptramitacion.D_DESCRIPCION, expe.D_SIT_ADICIONAL);

-- ---------------------------------------

  CREATE OR REPLACE VIEW "GE_TRAMITES_ABIERTOS" AS 
  SELECT
	tramite.TRAM_EXP_ID AS TRAM_ID,
	tramite.F_FECHA_INI AS F_FECHA_INI,
	tramite.D_DESCRIPCION AS D_DESC_TRAMITE,
	tipotram.TIP_TRA_ID AS ID_TIPO_TRAMITE,
	tipotram.D_DESCRIPCION AS D_DESC_TIPO_TRAMITE,
	resptramite.D_DESCRIPCION AS T_RESP_TRAMITE,
	resptramite.D_DESC_ABREV AS T_RESP_ABREV_TRAMITE,
	tramitesup.D_DESCRIPCION AS D_DESC_TRAM_SUP,
	vista_exped.EXP_ID AS EXP_ID,
	vista_exped.F_CREACION AS F_CREACION,
	vista_exped.F_MODIFICACION AS F_MODIFICACION,
	vista_exped.USU_CREACION AS USU_CREACION,
	vista_exped.USU_MODIFICACION AS USU_MODIFICACION,
	vista_exped.F_FECHA_REGISTRO AS F_FECHA_REGISTRO,
	vista_exped.T_TIP_EXP AS T_TIP_EXP,
	vista_exped.T_NUM_EXPEDIENTE AS T_NUM_EXPEDIENTE,
	vista_exped.T_SITUACION AS T_SITUACION,
	vista_exped.T_FECHA_ENTRADA AS T_FECHA_ENTRADA,
	vista_exped.T_PERSONA AS T_PERSONA,
	vista_exped.T_SUJETO_OBLIGADO AS T_SUJETO_OBLIGADO,
    vista_exped.T_NOMBRE_EXPEDIENTE AS T_NOMBRE_EXPEDIENTE,
    vista_exped.ID_MATERIA AS ID_MATERIA,
    vista_exped.ID_MATERIASUP AS ID_MATERIASUP,
    vista_exped.FINALIZADOS AS FINALIZADOS,
    vista_exped.T_RESPONSABLE AS T_RESPONSABLE,
	vista_exped.T_SITUACION_ADICIONAL AS T_SITUACION_ADICIONAL,
	dettram.F_FECHA_ENVIO AS F_FECHA_ENVIO,
	dettram.F_FECHA_NOTIFICACION AS F_FECHA_NOTIFICACION,
	dettram.F_FECHA_FIRMA AS F_FECHA_FIRMA,	
	dettram.F_FECHA_LIMITE AS F_FECHA_LIMITE, 
	dominterv.D_DESCRIPCION AS D_TIPO_INTERVINIENTE,
	domcansal.D_DESCRIPCION AS D_CANAL_SALIDA,
	domautcomp.D_DESCRIPCION AS T_AUT_COMP_INTERV,
	CONCAT(CONCAT(CONCAT(CONCAT(persona.T_NOMBRE_RAZONSOCIAL, ' '),persona.T_PRIMER_APELLIDO), ' '), persona.T_SEGUNDO_APELLIDO) AS T_PERSONA_INTERV,
	sujetoobligado.D_DESCRIPCION AS T_SUJETO_OBLIGADO_INTERV,
	domresnot.D_DESCRIPCION AS D_RES_NOTIF,
	CONCAT(CONCAT(domautcomp.D_DESCRIPCION,sujetoobligado.D_DESCRIPCION),CONCAT(CONCAT(CONCAT(CONCAT(persona.T_NOMBRE_RAZONSOCIAL, ' '),persona.T_PRIMER_APELLIDO), ' '), persona.T_SEGUNDO_APELLIDO)) AS T_INTERVINIENTE,
	dettram.L_ACUSE_RECIBO AS L_ACUSE_RECIBO,
	CONCAT(CONCAT(CONCAT(CONCAT(usuar.T_PRIMER_APELLIDO, ' '),usuar.T_SEGUNDO_APELLIDO), ' '), usuar.T_NOMBRE) AS T_FIRMANTE,
	domtipfirm.D_DESCRIPCION AS D_TIPO_FIRMA
FROM
GE_TRAMITE_EXPED tramite
JOIN GE_TIPO_TRAMITE tipotram ON tramite.TRAM_EXP_TIP_TRA_ID = tipotram.TIP_TRA_ID
LEFT OUTER JOIN GE_EXP_PEREXP_SUJEXP vista_exped ON vista_exped.EXP_ID = tramite.TRAM_EXP_EXP_ID
LEFT OUTER JOIN GE_RESP_TRAMITACION resptramite ON tramite.TRAM_EXP_RESTRA_ID = resptramite.RESTRA_ID
LEFT OUTER JOIN GE_TRAMITE_EXPED tramitesup ON tramite.TRAM_EXP_TRAMEXPSUP_ID = tramitesup.TRAM_EXP_ID
JOIN GE_DETALLE_EXPDTE_TRAM dettram ON tramite.TRAM_EXP_ID = dettram.DETEXPTRAM_TRAMEXP_ID
LEFT OUTER JOIN GE_VALORES_DOMINIOS dominterv on dettram.DETEXPTRAM_VALDOMTIPINT_ID = dominterv.VAL_DOM_ID
LEFT OUTER JOIN GE_VALORES_DOMINIOS domcansal on dettram.DETEXPTRAM_VALDOMCANSAL_ID = domcansal.VAL_DOM_ID
LEFT OUTER JOIN GE_VALORES_DOMINIOS domautcomp on dettram.DETEXPTRAM_VALDOM_INT_ID = domautcomp.VAL_DOM_ID
LEFT OUTER JOIN GE_PERSONAS persona ON persona.PER_ID = dettram.DETEXPTRAM_PER_INT_ID 
LEFT OUTER JOIN GE_SUJETOS_OBLIGADOS sujetoobligado ON sujetoobligado.SUJ_ID = dettram.DETEXPTRAM_SUJOBL_INT_ID 
LEFT OUTER JOIN GE_VALORES_DOMINIOS domresnot on dettram.DETEXPTRAM_VALDOMRESNOTIF_ID = domresnot.VAL_DOM_ID
LEFT OUTER JOIN GE_USUARIOS usuar on dettram.DETEXPTRAM_FIRMANTE_ID = usuar.USU_ID
LEFT OUTER JOIN GE_VALORES_DOMINIOS domtipfirm on dettram.DETEXPTRAM_VDOM_TIPFIRM_ID = domtipfirm.VAL_DOM_ID
WHERE tramite.L_ACTIVO = 1
AND tramite.L_FINALIZADO = 0 WITH READ ONLY;


SPOOL OFF;
