rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/007_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

CREATE TABLE GE_DETALLE_EXPDTE_TRAM (DET_EXP_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACREDITA_CUMPLIMIENTO NUMBER(1,0) DEFAULT 0, L_ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL, L_AFECTA_PLAZOS NUMBER(1,0) DEFAULT 0, D_DATOS_CANAL_SALIDA VARCHAR2(255 CHAR), F_FECHA_ACREDITACION TIMESTAMP, F_FECHA_EMISION TIMESTAMP, F_FECHA_ENTRADA TIMESTAMP, F_FECHA_ENVIO TIMESTAMP, F_FECHA_FIRMA TIMESTAMP, F_FECHA_INFORME TIMESTAMP, F_FECHA_LIMITE TIMESTAMP, F_FECHA_NOTIFICACION TIMESTAMP, F_FECHA_RESPUESTA TIMESTAMP, F_FECHA_SUBSANACION TIMESTAMP, D_IDENTIF_ENTRADA VARCHAR2(255 CHAR), INT_ID NUMBER(19,0), L_INFO_REMITIDA NUMBER(1,0) DEFAULT 0, N_VERSION NUMBER(19,0), L_NOTIF_INFRUCTUOSA NUMBER(1,0) DEFAULT 0, D_NUM_RESOLUCION VARCHAR2(255 CHAR), N_PLAZO NUMBER(10,0), L_SUBSANA_ADECUADAMENTE NUMBER(1,0) DEFAULT 0, DETEXPTRAM_EXP_ID NUMBER(19,0), DETEXPTRAM_TRAMEXP_ID NUMBER(19,0), DETEXPTRAM_VALDOMCANENT_ID NUMBER(19,0), DETEXPTRAM_VALDOMCANSAL_ID NUMBER(19,0), DETEXPTRAM_VALDOMSENRES_ID NUMBER(19,0), DETEXPTRAM_VALDOMTIPADM_ID NUMBER(19,0), DETEXPTRAM_VALDOMTIPINT_ID NUMBER(19,0), DETEXPTRAM_VALDOMTIPPLA_ID NUMBER(19,0))  TABLESPACE GESTOR_DAT;
CREATE TABLE GE_DETALLE_EXPDTE_TRAM_H (DET_EXP_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACREDITA_CUMPLIMIENTO NUMBER(1,0), L_ACTIVO NUMBER(1,0), L_AFECTA_PLAZOS NUMBER(1,0), D_DATOS_CANAL_SALIDA VARCHAR2(255 CHAR), F_FECHA_ACREDITACION TIMESTAMP, F_FECHA_EMISION TIMESTAMP, F_FECHA_ENTRADA TIMESTAMP, F_FECHA_ENVIO TIMESTAMP, F_FECHA_FIRMA TIMESTAMP, F_FECHA_INFORME TIMESTAMP, F_FECHA_LIMITE TIMESTAMP, F_FECHA_NOTIFICACION TIMESTAMP, F_FECHA_RESPUESTA TIMESTAMP, F_FECHA_SUBSANACION TIMESTAMP, D_IDENTIF_ENTRADA VARCHAR2(255 CHAR), INT_ID NUMBER(19,0), L_INFO_REMITIDA NUMBER(1,0), N_VERSION NUMBER(19,0), L_NOTIF_INFRUCTUOSA NUMBER(1,0), D_NUM_RESOLUCION VARCHAR2(255 CHAR), N_PLAZO NUMBER(10,0), L_SUBSANA_ADECUADAMENTE NUMBER(1,0), DETEXPTRAM_EXP_ID NUMBER(19,0), DETEXPTRAM_TRAMEXP_ID NUMBER(19,0), DETEXPTRAM_VALDOMCANENT_ID NUMBER(19,0), DETEXPTRAM_VALDOMCANSAL_ID NUMBER(19,0), DETEXPTRAM_VALDOMSENRES_ID NUMBER(19,0), DETEXPTRAM_VALDOMTIPADM_ID NUMBER(19,0), DETEXPTRAM_VALDOMTIPINT_ID NUMBER(19,0), DETEXPTRAM_VALDOMTIPPLA_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_CFG_METADATOS_TRAM (CFG_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), D_ACREDITA_CUMPLIMIENTO VARCHAR2(50 CHAR), L_ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL, D_AFECTA_PLAZOS VARCHAR2(50 CHAR), D_BT_GENERAR_DOC VARCHAR2(50 CHAR), D_BT_INCORPORAR_DOC VARCHAR2(50 CHAR), D_CANAL_ENTRADA VARCHAR2(50 CHAR), D_CANAL_SALIDA VARCHAR2(50 CHAR), D_DATOS_CANAL_SALIDA VARCHAR2(50 CHAR), D_FECHA_ACREDITACION VARCHAR2(50 CHAR), D_FECHA_EMISION VARCHAR2(50 CHAR), D_FECHA_ENTRADA VARCHAR2(50 CHAR), D_FECHA_ENVIO VARCHAR2(50 CHAR), D_FECHA_FIRMA VARCHAR2(50 CHAR), D_FECHA_INFORME VARCHAR2(50 CHAR), D_FECHA_LIMITE VARCHAR2(50 CHAR), D_FECHA_NOTIFICACION VARCHAR2(50 CHAR), D_FECHA_RESPUESTA VARCHAR2(50 CHAR), D_FECHA_SUBSANACION VARCHAR2(50 CHAR), D_IDENTIF_INTERESADO VARCHAR2(50 CHAR), D_IDENTIFICACION_ENTRADA VARCHAR2(50 CHAR), D_INFORM_REMITIDA VARCHAR2(50 CHAR), N_VERSION NUMBER(19,0), D_NOTIF_INFRUCTUOSA VARCHAR2(50 CHAR), D_NUM_RESOLUCION VARCHAR2(50 CHAR), D_PLAZO VARCHAR2(50 CHAR), D_SENTIDO_RESOLUCION VARCHAR2(50 CHAR), D_SUBSANA_ADECUADAMENTE VARCHAR2(50 CHAR), D_TIPO_ADMISION VARCHAR2(50 CHAR), D_TIPO_INTERESADO VARCHAR2(50 CHAR), D_TIPO_PLAZO VARCHAR2(50 CHAR), METTRAM_TIPTRAM_ID NUMBER(19,0), METTRAM_TIPTRAM_SUP_ID NUMBER(19,0), METTRAM_VALDOM_TIPEXP_ID NUMBER(19,0))  TABLESPACE GESTOR_DAT;
CREATE TABLE GE_CFG_METADATOS_TRAM_H (CFG_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), D_ACREDITA_CUMPLIMIENTO VARCHAR2(255 CHAR), L_ACTIVO NUMBER(1,0), D_AFECTA_PLAZOS VARCHAR2(255 CHAR), D_BT_GENERAR_DOC VARCHAR2(255 CHAR), D_BT_INCORPORAR_DOC VARCHAR2(255 CHAR), D_CANAL_ENTRADA VARCHAR2(255 CHAR), D_CANAL_SALIDA VARCHAR2(255 CHAR), D_DATOS_CANAL_SALIDA VARCHAR2(255 CHAR), D_FECHA_ACREDITACION VARCHAR2(255 CHAR), D_FECHA_EMISION VARCHAR2(255 CHAR), D_FECHA_ENTRADA VARCHAR2(255 CHAR), D_FECHA_ENVIO VARCHAR2(255 CHAR), D_FECHA_FIRMA VARCHAR2(255 CHAR), D_FECHA_INFORME VARCHAR2(255 CHAR), D_FECHA_LIMITE VARCHAR2(255 CHAR), D_FECHA_NOTIFICACION VARCHAR2(255 CHAR), D_FECHA_RESPUESTA VARCHAR2(255 CHAR), D_FECHA_SUBSANACION VARCHAR2(255 CHAR), D_IDENTIF_INTERESADO VARCHAR2(255 CHAR), D_IDENTIFICACION_ENTRADA VARCHAR2(255 CHAR), D_INFORM_REMITIDA VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0), D_NOTIF_INFRUCTUOSA VARCHAR2(255 CHAR), D_NUM_RESOLUCION VARCHAR2(255 CHAR), D_PLAZO VARCHAR2(255 CHAR), D_SENTIDO_RESOLUCION VARCHAR2(255 CHAR), D_SUBSANA_ADECUADAMENTE VARCHAR2(255 CHAR), D_TIPO_ADMISION VARCHAR2(255 CHAR), D_TIPO_INTERESADO VARCHAR2(255 CHAR), D_TIPO_PLAZO VARCHAR2(255 CHAR), METTRAM_TIPTRAM_ID NUMBER(19,0), METTRAM_TIPTRAM_SUP_ID NUMBER(19,0), METTRAM_VALDOM_TIPEXP_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
----------------------------------------------------------------------------------------------------

CREATE TABLE GE_CFG_PLAZOS_EXPDTE (CFG_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL, L_BLOQUEADO NUMBER(1,0) DEFAULT 1 NOT NULL, D_DESC_ABREV_TIPO_PLAZO VARCHAR2(255 CHAR), D_DESC_TIPO_PLAZO VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0), N_ORDEN NUMBER(19,0), PLAEXP_VALDOM_TIPEXP_ID NUMBER(19,0), PLAEXP_VALDOM_TIPPLA_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_CFG_PLAZOS_EXPDTE_H (CFG_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACTIVO NUMBER(1,0), L_BLOQUEADO NUMBER(1,0), D_DESC_ABREV_TIPO_PLAZO VARCHAR2(255 CHAR), D_DESC_TIPO_PLAZO VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0), N_ORDEN NUMBER(19,0), PLAEXP_VALDOM_TIPEXP_ID NUMBER(19,0), PLAEXP_VALDOM_TIPPLA_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_CFG_PLAZOS_ESTILOS (CFG_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL, D_ESTILO VARCHAR2(255 CHAR), N_LIMITE_INFERIOR NUMBER(19,0), N_LIMITE_SUPERIOR NUMBER(19,0), N_VERSION NUMBER(19,0), V_TIPO_CONTROL VARCHAR2(255 CHAR) NOT NULL, PLAEST_VALDOM_TIPEXP_ID NUMBER(19,0), PLAEST_VALDOM_TIPPLA_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_CFG_PLAZOS_ESTILOS_H (CFG_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACTIVO NUMBER(1,0), D_ESTILO VARCHAR2(255 CHAR), N_LIMITE_INFERIOR NUMBER(19,0), N_LIMITE_SUPERIOR NUMBER(19,0), N_VERSION NUMBER(19,0), V_TIPO_CONTROL VARCHAR2(255 CHAR), PLAEST_VALDOM_TIPEXP_ID NUMBER(19,0), PLAEST_VALDOM_TIPPLA_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_PLAZOS_EXPDTE (PLA_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL, L_CUMPLIDO NUMBER(1,0), F_FECHA_LIMITE TIMESTAMP, N_VERSION NUMBER(19,0), T_OBSERVACIONES VARCHAR2(255 CHAR), V_ORIGEN_FINAL VARCHAR2(255 CHAR), V_ORIGEN_INICIAL VARCHAR2(255 CHAR), PLAEXP_CFGPLAEXP_ID NUMBER(19,0), PLAEXP_EXP_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_PLAZOS_EXPDTE_H (PLA_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACTIVO NUMBER(1,0), L_CUMPLIDO NUMBER(1,0), F_FECHA_LIMITE TIMESTAMP, N_VERSION NUMBER(19,0), T_OBSERVACIONES VARCHAR2(255 CHAR), V_ORIGEN_FINAL VARCHAR2(255 CHAR), V_ORIGEN_INICIAL VARCHAR2(255 CHAR), PLAEXP_CFGPLAEXP_ID NUMBER(19,0), PLAEXP_EXP_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
-----------------------------------------------------------------------------------------------------

CREATE TABLE GE_CFG_PLAZOS_AUT (CFG_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), D_ACCION_ESPECIAL VARCHAR2(255 CHAR), L_ACTIVO NUMBER(1,0) DEFAULT 1 NOT NULL, L_AVISO NUMBER(1,0), N_VERSION NUMBER(19,0), V_ORIGEN VARCHAR2(255 CHAR), N_PLAZO NUMBER(10,0), V_TIPO_ACCION VARCHAR2(255 CHAR), PLAAUT_TIPTRAM_ID NUMBER(19,0), PLAAUT_TIPTRAMSUP_ID NUMBER(19,0), PLAAUT_VALDOM_PLAZO_ID NUMBER(19,0), PLAAUT_VALDOM_TIPEXP_ID NUMBER(19,0), PLAAUT_VALDOM_TIPPLA_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_CFG_PLAZOS_AUT_H (CFG_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), D_ACCION_ESPECIAL VARCHAR2(255 CHAR), L_ACTIVO NUMBER(1,0), L_AVISO NUMBER(1,0), N_VERSION NUMBER(19,0), V_ORIGEN VARCHAR2(255 CHAR), N_PLAZO NUMBER(10,0), V_TIPO_ACCION VARCHAR2(255 CHAR), PLAAUT_TIPTRAM_ID NUMBER(19,0), PLAAUT_TIPTRAMSUP_ID NUMBER(19,0), PLAAUT_VALDOM_PLAZO_ID NUMBER(19,0), PLAAUT_VALDOM_TIPEXP_ID NUMBER(19,0), PLAAUT_VALDOM_TIPPLA_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
-----------------------------------------------------------------------------------------------------

ALTER TABLE GE_EXPEDIENTES_H MODIFY (T_MOTIVO VARCHAR2(500 CHAR));

-----------------------------------------------------------------------------------------------------

UPDATE GE_DETALLE_EXPDTE_TRAM SET INT_ID = NULL;
UPDATE GE_DETALLE_EXPDTE_TRAM_H SET INT_ID = NULL;

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN INT_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN INT_ID;

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD DETEXPTRAM_VALDOM_INT_ID NUMBER(19,0);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD DETEXPTRAM_PER_INT_ID NUMBER(19,0);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD DETEXPTRAM_SUJOBL_INT_ID NUMBER(19,0);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD DETEXPTRAM_VALDOM_INT_ID NUMBER(19,0);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD DETEXPTRAM_PER_INT_ID NUMBER(19,0);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD DETEXPTRAM_SUJOBL_INT_ID NUMBER(19,0);

-----------------------------------------------------------------------------------------------------

CREATE TABLE GE_DOCUMENTOS_EXPED_TRAMITES (
	DETR_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0),
	F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), 
	DETR_DOCEXP_ID NUMBER(19,0) NOT NULL, DETR_TRAMEXP_ID NUMBER(19,0) NOT NULL
) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_DOCUMENTOS_EXPED_TRAMITES_H (
	DETR_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0), REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), 
	F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), 
	DETR_DOCEXP_ID NUMBER(19,0), DETR_TRAMEXP_ID NUMBER(19,0)
) TABLESPACE GESTOR_DAT;

-----------------------------------------------------------------------------------------------------

ALTER TABLE GE_SUJETOS_OBLIGADOS ADD (T_ABREVIATURA_TMP VARCHAR2(20 CHAR));
ALTER TABLE GE_SUJETOS_OBLIGADOS MODIFY (T_ABREVIATURA_1 VARCHAR2(20 CHAR));
UPDATE GE_SUJETOS_OBLIGADOS SET T_ABREVIATURA_TMP = T_ABREVIATURA_1, T_ABREVIATURA_1 = T_ABREVIATURA_3, T_ABREVIATURA_3 = '';
ALTER TABLE GE_SUJETOS_OBLIGADOS MODIFY (T_ABREVIATURA_3 VARCHAR2(5 CHAR));
UPDATE GE_SUJETOS_OBLIGADOS SET T_ABREVIATURA_3 = T_ABREVIATURA_TMP;
ALTER TABLE GE_SUJETOS_OBLIGADOS DROP (T_ABREVIATURA_TMP);

ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (T_ABREVIATURA_TMP VARCHAR2(20 CHAR));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (T_ABREVIATURA_1 VARCHAR2(20 CHAR));
UPDATE GE_SUJETOS_OBLIGADOS_H SET T_ABREVIATURA_TMP = T_ABREVIATURA_1, T_ABREVIATURA_1 = T_ABREVIATURA_3, T_ABREVIATURA_3 = '';
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (T_ABREVIATURA_3 VARCHAR2(5 CHAR));
UPDATE GE_SUJETOS_OBLIGADOS_H SET T_ABREVIATURA_3 = T_ABREVIATURA_TMP;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP (T_ABREVIATURA_TMP);

ALTER TABLE GE_SUJETOS_OBLIGADOS   ADD (SUJ_VALDOM_VIACOM_ID NUMBER(19,0), SUJ_VALDOM_TIPOLO_ID NUMBER(19,0));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (SUJ_VALDOM_VIACOM_ID NUMBER(19,0), SUJ_VALDOM_TIPOLO_ID NUMBER(19,0));



SPOOL OFF;
