rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/007_06_GRANTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DETALLE_EXPDTE_TRAM TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_DETALLE_EXPDTE_TRAM TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DETALLE_EXPDTE_TRAM_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_CFG_METADATOS_TRAM TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_CFG_METADATOS_TRAM TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_CFG_METADATOS_TRAM_H TO GE_ROL_GESTOR_DML;

--------------------------------------------------------------------------------------
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_CFG_PLAZOS_EXPDTE TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_CFG_PLAZOS_EXPDTE TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_CFG_PLAZOS_EXPDTE_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_CFG_PLAZOS_ESTILOS TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_CFG_PLAZOS_ESTILOS TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_CFG_PLAZOS_ESTILOS_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PLAZOS_EXPDTE TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_PLAZOS_EXPDTE TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PLAZOS_EXPDTE_H TO GE_ROL_GESTOR_DML;
--------------------------------------------------------------------------------------

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_CFG_PLAZOS_AUT TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_CFG_PLAZOS_AUT TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_CFG_PLAZOS_AUT_H TO GE_ROL_GESTOR_DML;

--------------------------------------------------------------------------------------

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DOCUMENTOS_EXPED_TRAMITES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_DOCUMENTOS_EXPED_TRAMITES TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DOCUMENTOS_EXPED_TRAMITES_H TO GE_ROL_GESTOR_DML;

SPOOL OFF;
