rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/012_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.12.0 --
--------------------

ALTER TABLE GE_RESOL_SUJOBL DROP COLUMN RESSUJOBL_EXP_ID;
ALTER TABLE GE_RESOL_SUJOBL_H DROP COLUMN RESSUJOBL_EXP_ID;

ALTER TABLE GE_RESOL_PERSONA DROP COLUMN RESPER_EXP_ID;
ALTER TABLE GE_RESOL_PERSONA_H DROP COLUMN RESPER_EXP_ID;

ALTER TABLE GE_RESOL_EXPEDIENTES DROP COLUMN RESEXP_VALDOMSENRES_ID;
ALTER TABLE GE_RESOL_EXPEDIENTES_H DROP COLUMN RESEXP_VALDOMSENRES_ID;

DROP TABLE GE_CFG_TIPOEXPEDIENTE CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_TIPOEXPEDIENTE_H CASCADE CONSTRAINTS;

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN D_SEGUIMIENTO_CABECERA;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN D_SEGUIMIENTO_CABECERA;

ALTER TABLE GE_CFG_EXPED_TRAMITE DROP CFGEXPTR_RESP_ID_DEFECTO;
ALTER TABLE GE_CFG_EXPED_TRAMITE_H DROP CFGEXPTR_RESP_ID_DEFECTO;

ALTER TABLE GE_CFG_EXPED_SUBTRAM DROP CFGEXPST_RESP_ID_DEFECTO;
ALTER TABLE GE_CFG_EXPED_SUBTRAM_H DROP CFGEXPST_RESP_ID_DEFECTO;

ALTER TABLE GE_CFG_EXPED_SUBTRAM DROP CFGEXPST_L_RESP_TRAM;
ALTER TABLE GE_CFG_EXPED_SUBTRAM_H DROP CFGEXPST_L_RESP_TRAM;

ALTER TABLE GE_EXPEDIENTES MODIFY (T_NOMBRE_EXPEDIENTE NOT NULL);

ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES   DROP (DOCRES_DOCEXP_ID);
ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES_H DROP (DOCRES_DOCEXP_ID);

ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES   ADD (DOCRES_DOC_ID NUMBER(19,0));
ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES_H ADD (DOCRES_DOC_ID NUMBER(19,0));

ALTER TABLE GE_ACCESOS_DOCS   DROP (L_RESOLUCION);
ALTER TABLE GE_ACCESOS_DOCS_H DROP (L_RESOLUCION);

DROP TABLE GE_CFG_AUTO_SITUACION   CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_AUTO_SITUACION_H CASCADE CONSTRAINTS;

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN DETEXTRAM_VALDOMMOTINAD_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN DETEXTRAM_VALDOMMOTINAD_ID;

ALTER TABLE GE_CFG_METADATOS_TRAM DROP COLUMN D_MOTIVO_INADMISION;
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP COLUMN D_MOTIVO_INADMISION;

ALTER TABLE GE_EXPEDIENTES DROP COLUMN EXP_VALDOM_MOTINADM_ID;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN EXP_VALDOM_MOTINADM_ID;

-- ---------------------------------

DROP TABLE GE_CFG_DOC_EXPED_DESC CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_DOC_EXPED_DESC_H CASCADE CONSTRAINTS;

-- ---------------------------------

ALTER TABLE GE_CFG_AUTO_SITUACION   DROP (L_OPERACION);
ALTER TABLE GE_CFG_AUTO_SITUACION_H DROP (L_OPERACION);

-----------------------------------
ALTER TABLE GE_CFG_TIPOEXPEDIENTE DROP COLUMN CFG_VALDOM_SERIERESOL_ID;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H DROP COLUMN CFG_VALDOM_SERIERESOL_ID;

ALTER TABLE GE_CFG_TIPOEXPEDIENTE DROP COLUMN CFG_VALDOM_TIPORESOL_ID;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H DROP COLUMN CFG_VALDOM_TIPORESOL_ID;

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN L_IMPOSICION_MEDIDAS;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN L_IMPOSICION_MEDIDAS;

------------------------------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE DROP COLUMN CFG_VALDOM_MOTRELPER_ID;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE DROP COLUMN CFG_VALDOM_MOTRELSUJ_ID;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H DROP COLUMN CFG_VALDOM_MOTRELPER_ID;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H DROP COLUMN CFG_VALDOM_MOTRELSUJ_ID;

-------------------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN DETEXPTRAM_VALDOM_PROPAPI_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN DETEXPTRAM_VALDOM_PROPAPI_ID;

ALTER TABLE GE_CFG_METADATOS_TRAM DROP COLUMN D_PROPUESTA_API;
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP COLUMN D_PROPUESTA_API;


SPOOL OFF;
