rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/012_UNDO_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.12.0 --
--------------------

alter table GE_CFG_AUTO_SITUACION_H RENAME CONSTRAINT GE_CFG_AUTO_SITUACION_H_PK TO GE_AUTO_SITUACION_H_PK;
alter table GE_CFG_EXPED_TRAMITE_H RENAME CONSTRAINT GE_CFG_EXPTRAM_H_REVAUD_FK TO GE_CFG_EXP_H_REVAUD_FK;
alter table GE_CFG_PLAZOS_AUT_H RENAME CONSTRAINT GE_CFG_PLAZOSAUT_H_REVAUD_FK TO FK55QGX7IOCTPNTIWAJ3JQEYU0W;
alter table GE_CFG_PLAZOS_EXPDTE_H RENAME CONSTRAINT GE_CFG_PLAEXP_H_REVAUD_FK TO GE_PLEXP_VDOM_TIPPLA_H_REV_FK;
alter table GE_PERSONAS_REPRESENTANTES_H RENAME CONSTRAINT GE_PERSONAS_REPRESENTANTES_H_REVAUD_FK TO GE_PRP_H_REVAUD_FK;

alter table GE_DOCUMENTOS_EXPED_TRAMITES_H drop constraint GE_DOCUMENTOS_EXPED_TRAMITES_H_PK;

alter table GE_CFG_TAREAS_H drop constraint GE_CFG_TAREAS_H_REVAUD_FK;
alter table GE_DOCUMENTOS_EXPED_TRAMITES_H drop constraint GE_DOCEXPEDTRAM_H_REVAUD_FK;
alter table GE_ELEMENTOS_SERIES_H drop constraint GE_ELEMENTOS_SERIES_H_REVAUD_FK;
alter table GE_PAISES_H drop constraint GE_PAISES_H_REVAUD_FK;
alter table GE_RESP_TRAMITACION_H drop constraint GE_RESP_TRAMITACION_H_REVAUD_FK;
alter table GE_SERIES_H drop constraint GE_SERIES_H_REVAUD_FK;
alter table GE_TAREAS_EXPEDIENTE_H drop constraint GE_TAREAS_EXPEDIENTE_H_REVAUD_FK;
alter table GE_USUARIO_RESP_H drop constraint GE_USUARIO_RESP_H_REVAUD_FK;


SPOOL OFF;
