rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/014_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.14.0 --
--------------------


ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES ADD (OBSEXP_PLA_ID NUMBER(19,0), OBSEXP_TAR_ID NUMBER(19,0), OBSEXP_TRAM_ID NUMBER(19,0));
ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES_H ADD (OBSEXP_PLA_ID NUMBER(19,0), OBSEXP_TAR_ID NUMBER(19,0), OBSEXP_TRAM_ID NUMBER(19,0));

ALTER TABLE GE_TRAMITE_EXPED ADD (TRAM_EXP_OBSEXP_ID NUMBER(19,0));
ALTER TABLE GE_TRAMITE_EXPED_H ADD (TRAM_EXP_OBSEXP_ID NUMBER(19,0));

ALTER TABLE GE_TAREAS_EXPEDIENTE ADD (TAR_EXP_OBSEXP_ID NUMBER(19,0));
ALTER TABLE GE_TAREAS_EXPEDIENTE_H ADD (TAR_EXP_OBSEXP_ID NUMBER(19,0));

ALTER TABLE GE_PLAZOS_EXPDTE ADD (PLA_EXP_OBSEXP_ID NUMBER(19,0));
ALTER TABLE GE_PLAZOS_EXPDTE_H ADD (PLA_EXP_OBSEXP_ID NUMBER(19,0));

ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN T_OBSERVACIONES;
ALTER TABLE GE_TAREAS_EXPEDIENTE DROP COLUMN T_OBSERVACIONES;
ALTER TABLE GE_PLAZOS_EXPDTE DROP COLUMN T_OBSERVACIONES;
ALTER TABLE GE_TRAMITE_EXPED_H DROP COLUMN T_OBSERVACIONES;
ALTER TABLE GE_TAREAS_EXPEDIENTE_H DROP COLUMN T_OBSERVACIONES;
ALTER TABLE GE_PLAZOS_EXPDTE_H DROP COLUMN T_OBSERVACIONES;

ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES MODIFY F_ENTRADA TIMESTAMP NULL;
ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES MODIFY  T_TEXTO VARCHAR2(4000 CHAR) NULL;

ALTER TABLE GE_DOCUMENTOS MODIFY DOC_PLA_ID NULL;

-- -----------------

ALTER TABLE GE_SUJETOS_OBLIGADOS_EXPDT ADD (T_NOMBRE_RAZONSOCIAL VARCHAR2(100 CHAR),N_TELEFONO VARCHAR2(50 CHAR),T_APELLIDOS VARCHAR2(200 CHAR),L_DPD NUMBER(1,0),T_EMAIL VARCHAR2(50 CHAR));
ALTER TABLE GE_SUJETOS_OBLIGADOS_EXPDT_H ADD (T_NOMBRE_RAZONSOCIAL VARCHAR2(100 CHAR),N_TELEFONO VARCHAR2(50 CHAR),T_APELLIDOS VARCHAR2(200 CHAR),L_DPD NUMBER(1,0),T_EMAIL VARCHAR2(50 CHAR));

-- -----------------

CREATE TABLE GE_CONEXIONES_USUARIOS (CON_ID NUMBER(19,0) NOT NULL, F_FECHA_ACCESO TIMESTAMP, F_FECHA_DESLOGADO TIMESTAMP, T_DESLOGADO VARCHAR2(255 CHAR), CON_PER_ID NUMBER(19,0), CON_USU_ID NUMBER(19,0));

-- -----------------


ALTER TABLE GE_AGRUP_EXPEDIENTES ADD (
	N_ORDEN NUMBER(19,0) DEFAULT 0 NOT NULL,
	AGREXP_VALDOM_CATEG_ID NUMBER(19,0),
	AGREXP_TRAM_ID NUMBER(19,0),
	L_VER_PEST_DOC NUMBER(1, 0) DEFAULT 1 NOT NULL
);

ALTER TABLE GE_AGRUP_EXPEDIENTES_H ADD (
	N_ORDEN NUMBER(19,0) DEFAULT 1,
	AGREXP_VALDOM_CATEG_ID NUMBER(19,0),
	AGREXP_TRAM_ID NUMBER(19,0),
	L_VER_PEST_DOC NUMBER(1, 0)
);

ALTER TABLE GE_AGRUP_DOCUMENTOS   ADD ( AGRDOC_DOC_EXP_TRAM_ID NUMBER(19, 0) );
ALTER TABLE GE_AGRUP_DOCUMENTOS_H ADD ( AGRDOC_DOC_EXP_TRAM_ID NUMBER(19, 0) );
ALTER TABLE GE_AGRUP_DOCUMENTOS  MODIFY ( AGRDOC_DOC_ID NULL );

ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES   ADD ( DOCEXP_VALDOM_CATEG_ID NUMBER(19,0) );
ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES_H ADD ( DOCEXP_VALDOM_CATEG_ID NUMBER(19,0) );

ALTER TABLE GE_TIPO_TRAMITE   ADD ( 
	L_VER_DOC_TRAM NUMBER(1, 0) DEFAULT 1 NOT NULL,
	L_VER_DOC_SUBTRAM NUMBER(1, 0) DEFAULT 0 NOT NULL
);
ALTER TABLE GE_TIPO_TRAMITE_H ADD ( 
	L_VER_DOC_TRAM NUMBER(1, 0),
	L_VER_DOC_SUBTRAM NUMBER(1, 0)
);

ALTER TABLE GE_CFG_DOC_EXPED_DESC   ADD ( CFG_VALDOM_CATEG_ID NUMBER(19,0) );
ALTER TABLE GE_CFG_DOC_EXPED_DESC_H ADD ( CFG_VALDOM_CATEG_ID NUMBER(19,0) );


UPDATE GE_DOCUMENTOS_EXPEDIENTES SET DOCEXP_VALDOM_CATEG_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'EXP' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'CAT_DOC'))
	WHERE T_DOC_TRABAJO != 'T';
UPDATE GE_DOCUMENTOS_EXPEDIENTES SET DOCEXP_VALDOM_CATEG_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'TRA' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'CAT_DOC'))
	WHERE T_DOC_TRABAJO = 'T';




ALTER TABLE GE_AGRUP_DOCUMENTOS   DROP COLUMN AGRDOC_DOC_ID ;
ALTER TABLE GE_AGRUP_DOCUMENTOS_H DROP COLUMN AGRDOC_DOC_ID;

ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES   DROP COLUMN  T_DOC_TRABAJO;
ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES_H DROP COLUMN  T_DOC_TRABAJO;

ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES   DROP COLUMN  N_ORDEN;
ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES_H DROP COLUMN  N_ORDEN;

ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES MODIFY (DOCEXP_VALDOM_CATEG_ID NOT NULL ENABLE);

ALTER TABLE GE_CFG_DOC_EXPED_DESC   DROP COLUMN  L_TRABAJO ;
ALTER TABLE GE_CFG_DOC_EXPED_DESC_H DROP COLUMN  L_TRABAJO ;
-----------------------------------------

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_BT_VINCULAR_DOC VARCHAR2(50 CHAR));

-- -----------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (L_ACUSE_RECIBO NUMBER(1,0) DEFAULT 1, DETEXPTRAM_FIRMANTE_ID NUMBER(19,0), DETEXPTRAM_VDOM_TIPFIRM_ID NUMBER(19,0));
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (L_ACUSE_RECIBO NUMBER(1,0) DEFAULT 1, DETEXPTRAM_FIRMANTE_ID NUMBER(19,0), DETEXPTRAM_VDOM_TIPFIRM_ID NUMBER(19,0));

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_ACUSE_RECIBO VARCHAR2(50 CHAR),D_FIRMANTE VARCHAR2(50 CHAR), D_TIPO_FIRMA VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_ACUSE_RECIBO VARCHAR2(50 CHAR),D_FIRMANTE VARCHAR2(50 CHAR), D_TIPO_FIRMA VARCHAR2(50 CHAR));

ALTER TABLE GE_USUARIOS ADD (L_FIRMANTE NUMBER(1,0));
ALTER TABLE GE_USUARIOS_H ADD (L_FIRMANTE NUMBER(1,0));




SPOOL OFF;
