rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/014_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.14.0 --
--------------------

ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES ADD CONSTRAINT GE_OBSEXP_PLA_FK FOREIGN KEY (OBSEXP_PLA_ID) REFERENCES GE_PLAZOS_EXPDTE;
ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES ADD CONSTRAINT GE_OBSEXP_TAR_FK FOREIGN KEY (OBSEXP_TAR_ID) REFERENCES GE_TAREAS_EXPEDIENTE;
ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES ADD CONSTRAINT GE_OBSEXP_TRAM_FK FOREIGN KEY (OBSEXP_TRAM_ID) REFERENCES GE_TRAMITE_EXPED;

ALTER TABLE GE_TRAMITE_EXPED ADD CONSTRAINT GE_TRAM_EXP_OBSEXP_FK FOREIGN KEY (TRAM_EXP_OBSEXP_ID) REFERENCES GE_OBSERVACIONES_EXPEDIENTES;
ALTER TABLE GE_TAREAS_EXPEDIENTE ADD CONSTRAINT GE_TAR_EXP_OBSEXP_FK FOREIGN KEY (TAR_EXP_OBSEXP_ID) REFERENCES GE_OBSERVACIONES_EXPEDIENTES;
ALTER TABLE GE_PLAZOS_EXPDTE ADD CONSTRAINT GE_PLA_EXP_OBSEXP_FK FOREIGN KEY (PLA_EXP_OBSEXP_ID) REFERENCES GE_OBSERVACIONES_EXPEDIENTES;
-- -----------------

ALTER TABLE GE_CONEXIONES_USUARIOS ADD CONSTRAINT GE_CON_PER_FK FOREIGN KEY (CON_PER_ID) REFERENCES GE_PERFILES;
ALTER TABLE GE_CONEXIONES_USUARIOS ADD CONSTRAINT GE_CON_USU_FK FOREIGN KEY (CON_USU_ID) REFERENCES GE_USUARIOS;

-- -----------------


ALTER TABLE GE_AGRUP_EXPEDIENTES      ADD CONSTRAINT GE_AGREXP_VALDOM_CATEG_ID_FK  FOREIGN KEY (AGREXP_VALDOM_CATEG_ID)  REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_AGRUP_EXPEDIENTES      ADD CONSTRAINT GE_AGREXP_TRAM_ID_FK          FOREIGN KEY (AGREXP_TRAM_ID)          REFERENCES GE_TRAMITE_EXPED;
ALTER TABLE GE_AGRUP_EXPEDIENTES      ADD CONSTRAINT GE_AGREXP_EXP_TRAM_CAT_UK     UNIQUE (AGREXP_EXP_ID, AGREXP_TRAM_ID, AGREXP_VALDOM_CATEG_ID);

ALTER TABLE GE_AGRUP_DOCUMENTOS       ADD CONSTRAINT GE_AGRDOC_DOC_EXP_TRAM_ID_FK  FOREIGN KEY (AGRDOC_DOC_EXP_TRAM_ID)  REFERENCES GE_DOCUMENTOS_EXPED_TRAMITES;
ALTER TABLE GE_AGRUP_DOCUMENTOS       ADD CONSTRAINT GE_AGRDOC_DOCEXPTR_AGREXP_UK  UNIQUE (AGRDOC_AGREXP_ID, AGRDOC_DOC_EXP_TRAM_ID);

ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES ADD CONSTRAINT GE_DOCEXP_VALDOM_CATEG_ID_FK  FOREIGN KEY (DOCEXP_VALDOM_CATEG_ID)  REFERENCES GE_VALORES_DOMINIOS;

ALTER TABLE GE_CFG_DOC_EXPED_DESC ADD CONSTRAINT GE_CFG_VALDOM_CATEG_ID_FK  FOREIGN KEY (CFG_VALDOM_CATEG_ID)  REFERENCES GE_VALORES_DOMINIOS;




/*-- EJECUTAR A POSTERIORI
-- HACER LOS CAMPOS NUEVOS OBLIGATORIOS
-- NO EJECUTAR AUN
/*
UPDATE GE_AGRUP_EXPEDIENTES SET AGREXP_VALDOM_CATEG_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'EXP' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'CAT_DOC'))
ALTER TABLE GE_AGRUP_EXPEDIENTES MODIFY (AGREXP_VALDOM_CATEG_ID NOT NULL ENABLE);

-- DELETE FROM GE_AGRUP_DOCUMENTOS WHERE AGRDOC_AGREXP_ID NOT IN (SELECT DOCEXP_EXP_ID FROM GE_DOCUMENTOS_EXPEDIENTES);
--UPDATE GE_AGRUP_DOCUMENTOS SET AGRDOC_DOC_EXP_TRAM_ID = ???;
ALTER TABLE GE_AGRUP_DOCUMENTOS MODIFY (AGRDOC_DOC_EXP_TRAM_ID NOT NULL ENABLE);
ALTER TABLE GE_CFG_DOC_EXPED_DESC MODIFY (CFG_VALDOM_CATEG_ID NOT NULL ENABLE );

--*/

-- ---------------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD CONSTRAINT GE_DETEXPTRAM_FIRMANTE_FK FOREIGN KEY (DETEXPTRAM_FIRMANTE_ID) REFERENCES GE_USUARIOS;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD CONSTRAINT GE_DETEXPTRAM_VDOM_TIPFIRM_FK FOREIGN KEY (DETEXPTRAM_VDOM_TIPFIRM_ID) REFERENCES GE_VALORES_DOMINIOS;




SPOOL OFF;
