rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/014_07_VISTAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.14.0 --
-------------------

    CREATE OR REPLACE VIEW GE_LISTADO_OBSERVACIONES_EXP AS SELECT
OBSEXP.OBS_ID AS OBS_ID,
OBSEXP.F_ENTRADA AS F_ENTRADA,
obsexp.obs_valdom_tipobs_id AS VALDOM_TIPOBS,
OBSEXP.OBSEXP_PLA_ID AS PLAZO,
OBSEXP.OBSEXP_TAR_ID AS TAREA,
OBSEXP.OBSEXP_TRAM_ID AS TRAMITE,
OBSEXP.T_TEXTO AS TEXTO,
obsexp.obs_exp_id AS EXPEDIENTE,
obsexp.usu_creacion AS USU_CREACION,
obsexp.usu_modificacion AS usu_modificacion,
obsexp.f_creacion AS f_creacion,
obsexp.f_modificacion AS f_modificacion
FROM GE_OBSERVACIONES_EXPEDIENTES OBSEXP
JOIN GE_VALORES_DOMINIOS VALDOMTIPOBS ON OBSEXP.OBS_VALDOM_TIPOBS_ID = VALDOMTIPOBS.VAL_DOM_ID
WHERE OBSEXP.F_ENTRADA IS NOT NULL AND (OBSEXP.T_TEXTO IS NOT NULL OR OBSEXP.T_TEXTO != '');

-- --------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GE_TRAMITES_ABIERTOS" ("TRAM_ID", "F_FECHA_INI", "D_DESC_TRAMITE", "ID_TIPO_TRAMITE", "D_DESC_TIPO_TRAMITE", "T_RESP_TRAMITE","T_RESP_ABREV_TRAMITE","D_DESC_TRAM_SUP","EXP_ID", "F_CREACION", "F_MODIFICACION", "USU_CREACION", "USU_MODIFICACION", "F_FECHA_REGISTRO", "T_TIP_EXP", "T_NUM_EXPEDIENTE", "T_SITUACION", "T_FECHA_ENTRADA", "T_PERSONA", "T_SUJETO_OBLIGADO", "T_NOMBRE_EXPEDIENTE", "ID_MATERIA", "ID_MATERIASUP", "FINALIZADOS", "T_RESPONSABLE", "T_SITUACION_ADICIONAL") AS 
  SELECT
	tramite.TRAM_EXP_ID AS TRAM_ID,
	tramite.F_FECHA_INI AS F_FECHA_INI,
	tramite.D_DESCRIPCION AS D_DESC_TRAMITE,
	tipotram.TIP_TRA_ID AS ID_TIPO_TRAMITE,
	tipotram.D_DESCRIPCION AS D_DESC_TIPO_TRAMITE,
	resptramite.D_DESCRIPCION AS T_RESP_TRAMITE,
	resptramite.D_DESC_ABREV AS T_RESP_ABREV_TRAMITE,
	tramitesup.D_DESCRIPCION AS D_DESC_TRAM_SUP,
	vista_exped.EXP_ID AS EXP_ID,
	vista_exped.F_CREACION AS F_CREACION,
	vista_exped.F_MODIFICACION AS F_MODIFICACION,
	vista_exped.USU_CREACION AS USU_CREACION,
	vista_exped.USU_MODIFICACION AS USU_MODIFICACION,
	vista_exped.F_FECHA_REGISTRO AS F_FECHA_REGISTRO,
	vista_exped.T_TIP_EXP AS T_TIP_EXP,
	vista_exped.T_NUM_EXPEDIENTE AS T_NUM_EXPEDIENTE,
	vista_exped.T_SITUACION AS T_SITUACION,
	vista_exped.T_FECHA_ENTRADA AS T_FECHA_ENTRADA,
	vista_exped.T_PERSONA AS T_PERSONA,
	vista_exped.T_SUJETO_OBLIGADO AS T_SUJETO_OBLIGADO,
    vista_exped.T_NOMBRE_EXPEDIENTE AS T_NOMBRE_EXPEDIENTE,
    vista_exped.ID_MATERIA AS ID_MATERIA,
    vista_exped.ID_MATERIASUP AS ID_MATERIASUP,
    vista_exped.FINALIZADOS AS FINALIZADOS,
    vista_exped.T_RESPONSABLE AS T_RESPONSABLE,
	vista_exped.T_SITUACION_ADICIONAL AS T_SITUACION_ADICIONAL
FROM
GE_TRAMITE_EXPED tramite
JOIN GE_TIPO_TRAMITE tipotram ON tramite.TRAM_EXP_TIP_TRA_ID = tipotram.TIP_TRA_ID
LEFT OUTER JOIN GE_EXP_PEREXP_SUJEXP vista_exped ON vista_exped.EXP_ID = tramite.TRAM_EXP_EXP_ID
LEFT OUTER JOIN GE_RESP_TRAMITACION resptramite ON tramite.TRAM_EXP_RESTRA_ID = resptramite.RESTRA_ID
LEFT OUTER JOIN GE_TRAMITE_EXPED tramitesup ON tramite.TRAM_EXP_TRAMEXPSUP_ID = tramitesup.TRAM_EXP_ID
WHERE tramite.L_ACTIVO = 1
AND tramite.L_FINALIZADO = 0 WITH READ ONLY;


-- ------------------------


 CREATE OR REPLACE VIEW GE_LISTADO_NOTIFICACIONES_TRAM AS SELECT 
TRAMEXP.TRAM_EXP_ID AS TRAM_EXP_ID,
tramexp.tram_exp_tramexpsup_id AS TRAM_EXP_SUP_ID,
tramexp.f_fecha_ini AS F_FECHA_INI,
TIPTRAM.D_DESC_ABREV AS DESC_ABREV, 
valdomresnotif.val_dom_id AS VALDOM_RESNOTIF,
valdomresnotif.val_dom_id AS VALDOM_TIPINT,
TRAMEXP.D_DESCRIPCION AS D_DESCRIPCION_TRAMEXP,
detexptram.det_exp_id as DETALLE_EXP_TRAM,
TRAMEXP.L_FINALIZADO AS L_FINALIZADO,
TRAMEXP.usu_creacion AS USU_CREACION,
TRAMEXP.usu_modificacion AS usu_modificacion,
TRAMEXP.f_creacion AS f_creacion,
TRAMEXP.f_modificacion AS f_modificacion
FROM GE_TRAMITE_EXPED TRAMEXP
LEFT OUTER JOIN GE_TIPO_TRAMITE TIPTRAM ON TRAMEXP.TRAM_EXP_TIP_TRA_ID = TIPTRAM.TIP_TRA_ID
LEFT OUTER JOIN GE_DETALLE_EXPDTE_TRAM DETEXPTRAM ON DETEXPTRAM.DETEXPTRAM_TRAMEXP_ID = TRAMEXP.TRAM_EXP_ID 
LEFT OUTER JOIN GE_VALORES_DOMINIOS VALDOMTIPINT ON DETEXPTRAM.DETEXPTRAM_VALDOMTIPINT_ID = VALDOMTIPINT.VAL_DOM_ID
LEFT OUTER JOIN GE_VALORES_DOMINIOS VALDOMRESNOTIF ON DETEXPTRAM.DETEXPTRAM_VALDOMRESNOTIF_ID = VALDOMRESNOTIF.VALDOM_DOM_ID
WHERE TRAMEXP.TRAM_EXP_TRAMEXPSUP_ID IS NOT NULL 
    AND TRAMEXP.L_ACTIVO = 1 
    AND TRAMEXP.TRAM_EXP_TIP_TRA_ID IN (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO IN ('NOT','COM'));

-- ----------------------------

 CREATE OR REPLACE VIEW GE_LISTADO_NOTIFICACIONES_TRAM AS SELECT 
TRAMEXP.TRAM_EXP_ID AS TRAM_EXP_ID,
tramexp.tram_exp_tramexpsup_id AS TRAM_EXP_SUP_ID,
tramexp.f_fecha_ini AS F_FECHA_INI,
TIPTRAM.D_DESC_ABREV AS DESC_ABREV, 
valdomresnotif.val_dom_id AS VALDOM_RESNOTIF,
valdomresnotif.val_dom_id AS VALDOM_TIPINT,
TRAMEXP.D_DESCRIPCION AS D_DESCRIPCION_TRAMEXP,
detexptram.det_exp_id as DETALLE_EXP_TRAM,
detexptram.l_acuse_recibo as L_ACUSE_RECIBO,
TRAMEXP.L_FINALIZADO AS L_FINALIZADO,
TRAMEXP.usu_creacion AS USU_CREACION,
TRAMEXP.usu_modificacion AS usu_modificacion,
TRAMEXP.f_creacion AS f_creacion,
TRAMEXP.f_modificacion AS f_modificacion
FROM GE_TRAMITE_EXPED TRAMEXP
LEFT OUTER JOIN GE_TIPO_TRAMITE TIPTRAM ON TRAMEXP.TRAM_EXP_TIP_TRA_ID = TIPTRAM.TIP_TRA_ID
LEFT OUTER JOIN GE_DETALLE_EXPDTE_TRAM DETEXPTRAM ON DETEXPTRAM.DETEXPTRAM_TRAMEXP_ID = TRAMEXP.TRAM_EXP_ID 
LEFT OUTER JOIN GE_VALORES_DOMINIOS VALDOMTIPINT ON DETEXPTRAM.DETEXPTRAM_VALDOMTIPINT_ID = VALDOMTIPINT.VAL_DOM_ID
LEFT OUTER JOIN GE_VALORES_DOMINIOS VALDOMRESNOTIF ON DETEXPTRAM.DETEXPTRAM_VALDOMRESNOTIF_ID = VALDOMRESNOTIF.VALDOM_DOM_ID
WHERE TRAMEXP.TRAM_EXP_TRAMEXPSUP_ID IS NOT NULL 
    AND TRAMEXP.L_ACTIVO = 1 
    AND TRAMEXP.TRAM_EXP_TIP_TRA_ID IN (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO IN ('NOT','COM'));


 CREATE OR REPLACE FORCE VIEW "GE_EXP_PEREXP_SUJEXP" ("EXP_ID", "F_CREACION", "F_MODIFICACION", "USU_CREACION", "USU_MODIFICACION", "F_FECHA_REGISTRO", "T_TIP_EXP", "T_NUM_EXPEDIENTE", "T_SITUACION", "T_FECHA_ENTRADA", "T_PERSONA", "T_SUJETO_OBLIGADO", "T_NOMBRE_EXPEDIENTE", "ID_MATERIA", "ID_MATERIASUP", "FINALIZADOS", "T_RESPONSABLE", "T_SITUACION_ADICIONAL") AS 
  SELECT 
	expe.EXP_ID AS EXP_ID,
	expe.F_CREACION AS F_CREACION,
	expe.F_MODIFICACION AS F_MODIFICACION,
	expe.USU_CREACION AS USU_CREACION,
	expe.USU_MODIFICACION AS USU_MODIFICACION,
	expe.F_FECHA_REGISTRO AS F_FECHA_REGISTRO,
	valortipoexp.T_ABREVIATURA AS T_TIP_EXP,
	expe.T_NUMERO_EXPEDIENTE AS T_NUM_EXPEDIENTE,
	situacionexpe.D_DESCRIPCION AS T_SITUACION,
	expe.F_FECHA_ENTRADA AS T_FECHA_ENTRADA,
	CASE WHEN persona.T_PRIMER_APELLIDO is null THEN persona.T_NOMBRE_RAZONSOCIAL
	ELSE TRIM(CONCAT(CONCAT(TRIM(CONCAT(CONCAT(persona.T_PRIMER_APELLIDO, ' '),persona.T_SEGUNDO_APELLIDO)), ', '), persona.T_NOMBRE_RAZONSOCIAL)) END AS T_PERSONA,
	sujetoobligado.D_DESCRIPCION AS T_SUJETO_OBLIGADO,
    expe.T_NOMBRE_EXPEDIENTE AS T_NOMBRE_EXPEDIENTE,
    LISTAGG('-' ||materia.val_dom_id||'-') WITHIN GROUP (ORDER BY materia.val_dom_id) AS ID_MATERIA,
    LISTAGG('-' ||materia.valdom_valdom_id||'-') WITHIN GROUP (ORDER BY materia.valdom_valdom_id) AS ID_MATERIASUP,
    situacionexpe.L_SIT_FINAL AS FINALIZADOS,
    resptramitacion.D_DESCRIPCION AS T_RESPONSABLE,
	expe.D_SIT_ADICIONAL AS T_SITUACION_ADICIONAL
FROM GE_EXPEDIENTES expe
LEFT OUTER JOIN ge_materias_expdt matexp ON expe.EXP_ID = matexp.MATEXP_EXP_ID
LEFT OUTER JOIN GE_MATERIAS_TIPEXPEDIENTES mattipexp ON matexp.MATEXP_MATTIPEXP_ID = mattipexp.MAT_ID
LEFT OUTER JOIN GE_VALORES_DOMINIOS materia ON materia.VAL_DOM_ID = mattipexp.MATTIPEXP_VALDOMMAT_ID
INNER JOIN GE_VALORES_DOMINIOS valortipoexp ON valortipoexp.VAL_DOM_ID = expe.EXP_VALDOM_TIPEXP_ID 
INNER JOIN GE_VALORES_DOMINIOS valorsituacion ON valorsituacion.VAL_DOM_ID = expe.EXP_VALDOM_SIT_ID 
INNER JOIN GE_PERSONAS_EXPEDIENTES perexpe ON  perexpe.PER_EXP_ID=expe.EXP_ID
INNER JOIN GE_SUJETOS_OBLIGADOS_EXPDT sujetoexpe ON sujetoexpe.SUJ_EXP_ID=expe.EXP_ID
INNER JOIN GE_PERSONAS persona ON persona.PER_ID =perexpe.PER_PER_ID 
INNER JOIN GE_SUJETOS_OBLIGADOS sujetoobligado ON sujetoobligado.SUJ_ID = sujetoexpe.SUJ_SUJ_ID 
INNER JOIN GE_SITUACIONES_EXPEDIENTES situacionexpe ON situacionexpe.SIT_VALDOM_TIPEXP_ID=expe.EXP_VALDOM_TIPEXP_ID 
LEFT OUTER JOIN GE_RESP_TRAMITACION resptramitacion ON expe.EXP_RESTRA_ID =resptramitacion.RESTRA_ID 
WHERE perexpe.N_PRINCIPAL =1 AND sujetoexpe.N_PRINCIPAL =1 
AND situacionexpe.SIT_VALDOM_TIPEXP_ID=expe.EXP_VALDOM_TIPEXP_ID
AND situacionexpe.SIT_VALDOM_SIT_ID=expe.EXP_VALDOM_SIT_ID
group by (expe.EXP_ID,
expe.F_CREACION,
expe.F_MODIFICACION,
expe.USU_CREACION,
expe.USU_MODIFICACION,
expe.F_FECHA_REGISTRO,
valortipoexp.T_ABREVIATURA,
expe.T_NUMERO_EXPEDIENTE,
situacionexpe.D_DESCRIPCION,
expe.F_FECHA_ENTRADA,
	CASE WHEN persona.T_PRIMER_APELLIDO is null THEN persona.T_NOMBRE_RAZONSOCIAL
	ELSE TRIM(CONCAT(CONCAT(TRIM(CONCAT(CONCAT(persona.T_PRIMER_APELLIDO, ' '),persona.T_SEGUNDO_APELLIDO)), ', '), persona.T_NOMBRE_RAZONSOCIAL)) END,
sujetoobligado.D_DESCRIPCION,
expe.T_NOMBRE_EXPEDIENTE,
situacionexpe.L_SIT_FINAL,
expe.T_NOMBRE_EXPEDIENTE, resptramitacion.D_DESCRIPCION, expe.D_SIT_ADICIONAL);

-- --------------------------------------------


CREATE OR REPLACE VIEW "GE_LISTADO_DOCUMENTOS_EXP" AS 
	SELECT
		DE.DOCEXP_ID AS DOCEXP_ID,
		DE.DOCEXP_DOC_ID AS DOC_ID,
		DE.DOCEXP_EXP_ID AS EXP_ID,
		D.T_IDEN_DOC AS T_IDEN_DOC,
		DE.D_DESCRIPCION_DOC AS D_DESCRIPCION,
		DE.D_DESC_ABREV_DOC AS D_DESC_ABREV,
		D.T_NOMBRE_FICHERO AS T_NOMBRE_FICHERO,
		D.T_EXTENSION_FICHERO AS T_EXTENSION_FICHERO,
		TD.TIP_DOC_ID AS TIP_DOC_ID,
		TD.D_DESCRIPCION AS D_DESCRIPCION_TIPO,
		D.F_CREACION AS F_CREACION,
		D.F_MODIFICACION AS F_MODIFICACION,
		D.USU_CREACION AS USU_CREACION,
		D.USU_MODIFICACION AS USU_MODIFICACION,
		D.L_EDITABLE AS L_EDITABLE,
		D.L_FIRMADO AS L_FIRMADO,
		D.L_SELLADO AS L_SELLADO,
		D.L_ANONIMIZADO AS L_ANONIMIZADO,
		D.L_ANONIMIZADO_PARCIAL AS L_ANONIMIZADO_PARCIAL,
		D.L_ACTIVO AS L_ACTIVO,
        U.T_LOGIN AS T_USUARIO_ACCESO,
        AD.F_FECHA_HORA_ACCESO,
		CAT.VAL_DOM_ID AS CAT_ID,
		CAT.D_DESCRIPCION AS CATEGORIA,
		CAT.N_ORDEN AS N_ORDEN_CAT
	FROM GE_DOCUMENTOS_EXPEDIENTES DE 
		INNER JOIN GE_DOCUMENTOS D ON DE.DOCEXP_DOC_ID = D.DOC_ID
		INNER JOIN GE_TIPOS_DOCUMENTOS TD ON D.DOC_TIPDOC_ID = TD.TIP_DOC_ID
        LEFT JOIN (SELECT ACD_DOC_ID, ACD_USU_ID, F_FECHA_HORA_ACCESO
                    FROM GE_ACCESOS_DOCS_ULTIMOS_EDIT) AD ON D.DOC_ID = AD.ACD_DOC_ID 
        LEFT JOIN GE_USUARIOS U ON AD.ACD_USU_ID = U.USU_ID
		LEFT OUTER JOIN GE_VALORES_DOMINIOS CAT ON DE.DOCEXP_VALDOM_CATEG_ID = CAT.VAL_DOM_ID
	WHERE DE.L_ACTIVO = 1 AND D.L_ACTIVO = 1;


CREATE OR REPLACE VIEW "GE_LISTADO_DOCUMENTOS_EXP_TRAM" AS 
	SELECT
		DE.DOCEXP_ID,DE.DOC_ID,DE.EXP_ID,DE.T_IDEN_DOC,DE.D_DESCRIPCION,DE.D_DESC_ABREV,DE.T_NOMBRE_FICHERO,DE.T_EXTENSION_FICHERO,DE.TIP_DOC_ID,DE.D_DESCRIPCION_TIPO,DE.F_CREACION,DE.F_MODIFICACION,DE.USU_CREACION,DE.USU_MODIFICACION, DE.T_USUARIO_ACCESO, DE.F_FECHA_HORA_ACCESO, DE.L_EDITABLE,DE.L_FIRMADO,DE.L_SELLADO,DE.L_ANONIMIZADO,DE.L_ANONIMIZADO_PARCIAL,DE.L_ACTIVO,DE.CAT_ID,DE.CATEGORIA,DE.N_ORDEN_CAT,
		DET.DETR_ID AS DOC_EXP_TRAM_ID,
		DET.T_ORIGEN AS ORIGEN_DOCEXPTR,
		DET.DETR_TRAMEXP_ID AS TRAM_EXPE_ID,
		TE.TRAM_EXP_TRAMEXPSUP_ID AS TRAM_EXPE_SUP_ID,
		TT.T_CODIGO AS T_CODIGO,
		DTT.D_NUM_RESOLUCION AS NUM_RESOL,
		AGE.AGREXP_ID AS AGR_EXP_ID,
		AGE.D_DESCRIPCION_DOC AS AGRUPACION_EXP,
		AGE.N_ORDEN AS N_ORDEN_AGR_EXP,
		AGE.L_VER_PEST_DOC,
		AGD.N_ORDEN,
		TAR.TAREXP_ID
	FROM GE_LISTADO_DOCUMENTOS_EXP DE 
		INNER JOIN GE_DOCUMENTOS_EXPED_TRAMITES DET ON DE.DOCEXP_ID = DET.DETR_DOCEXP_ID
		INNER JOIN GE_TRAMITE_EXPED TE ON DET.DETR_TRAMEXP_ID = TE.TRAM_EXP_ID
		INNER JOIN GE_TIPO_TRAMITE TT ON TT.TIP_TRA_ID = TE.TRAM_EXP_TIP_TRA_ID
		LEFT OUTER JOIN GE_DETALLE_EXPDTE_TRAM DTT ON TE.TRAM_EXP_ID = DTT.DETEXPTRAM_TRAMEXP_ID
		LEFT OUTER JOIN GE_AGRUP_DOCUMENTOS AGD ON DET.DETR_ID = AGD.AGRDOC_DOC_EXP_TRAM_ID
		LEFT OUTER JOIN GE_AGRUP_EXPEDIENTES AGE ON AGD.AGRDOC_AGREXP_ID = AGE.AGREXP_ID
		LEFT OUTER JOIN (SELECT DISTINCT T.TAREXP_ID, DET_T.DETR_DOCEXP_ID FROM GE_TAREAS_EXPEDIENTE T 
							INNER JOIN GE_VALORES_DOMINIOS TIPT ON T.TAREXP_VALDOM_TAR_ID = TIPT.VAL_DOM_ID
							INNER JOIN GE_DOMINIOS D ON TIPT.VALDOM_DOM_ID = D.DOM_ID
							INNER JOIN GE_DOCUMENTOS_EXPED_TRAMITES DET_T ON DET_T.DETR_ID = T.TAREXP_DOCEXP_TRA_ID
							WHERE T.L_ACTIVA = 1 AND T.T_SITUACION = 'P' 
							AND TIPT.C_CODIGO = 'REV' AND D.C_CODIGO='TAREAS') TAR
						ON DE.DOCEXP_ID = TAR.DETR_DOCEXP_ID
						;






SPOOL OFF;
