rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/013_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.13.0 --
--------------------



ALTER TABLE GE_TRAMITE_EXPED ADD (F_FECHA_TRAMITE TIMESTAMP, D_INF_RELEVANTE VARCHAR2(255 CHAR));
ALTER TABLE GE_TRAMITE_EXPED_H ADD (F_FECHA_TRAMITE TIMESTAMP, D_INF_RELEVANTE VARCHAR2(255 CHAR));

-- --------------------------------

ALTER TABLE GE_CFG_TAREAS ADD (
	L_TAREA_MANUAL NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_AVISO NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_BLOQUEO_DISTINTO_RESP NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_BLOQUEO_MISMO_RESP NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_INFORME_CAMBIO_RESP NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_MODIF_DESCRIPCION NUMBER(1,0) DEFAULT 1 NOT NULL,
	L_FINAL_ALTA_TRAM NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_FINAL_ALTA_TAREA NUMBER(1,0) DEFAULT 0 NOT NULL,

	CFGTAR_VALDOM_TIP_TAR_CAMB_ID  NUMBER(19,0),
	CFGTAR_RESP_TAREA_VUELTA_ID NUMBER(19,0)
	);
	
ALTER TABLE GE_CFG_TAREAS_H ADD (
	L_TAREA_MANUAL NUMBER(1,0),
	L_AVISO NUMBER(1,0),
	L_BLOQUEO_DISTINTO_RESP NUMBER(1,0),
	L_BLOQUEO_MISMO_RESP NUMBER(1,0),
	L_INFORME_CAMBIO_RESP NUMBER(1,0),
	L_MODIF_DESCRIPCION NUMBER(1,0),
	L_FINAL_ALTA_TRAM NUMBER(1,0),
	L_FINAL_ALTA_TAREA NUMBER(1,0),
	
	CFGTAR_VALDOM_TIP_TAR_CAMB_ID  NUMBER(19,0),
	CFGTAR_RESP_TAREA_VUELTA_ID NUMBER(19,0)
	);

ALTER TABLE GE_TAREAS_EXPEDIENTE ADD (
	L_AVISO NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_BLOQUEO_DISTINTO_RESP NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_BLOQUEO_MISMO_RESP NUMBER(1,0) DEFAULT 0 NOT NULL
	);

ALTER TABLE GE_TAREAS_EXPEDIENTE_h ADD (
	L_AVISO NUMBER(1,0),
	L_BLOQUEO_DISTINTO_RESP NUMBER(1,0),
	L_BLOQUEO_MISMO_RESP NUMBER(1,0)
	);


-- -----------------

ALTER TABLE GE_TIPO_TRAMITE ADD (T_INSTRUCCIONES VARCHAR2(4000 CHAR), L_MODIF_DESCRIPCION NUMBER(1,0) DEFAULT 0, C_COLOR_SUB_TRAMITE VARCHAR2(255 CHAR), C_COLOR_TRAMITE VARCHAR2(255 CHAR),L_TIPO_INTERESADO_BLOQUEADO NUMBER(1,0),TIPTRA_VALDOM_TIPINT_ID NUMBER(19,0));
ALTER TABLE GE_TIPO_TRAMITE_H ADD (T_INSTRUCCIONES VARCHAR2(4000 CHAR), L_MODIF_DESCRIPCION NUMBER(1,0) DEFAULT 0, C_COLOR_SUB_TRAMITE VARCHAR2(255 CHAR), C_COLOR_TRAMITE VARCHAR2(255 CHAR),L_TIPO_INTERESADO_BLOQUEADO NUMBER(1,0),TIPTRA_VALDOM_TIPINT_ID NUMBER(19,0));

-- -----------------
ALTER TABLE GE_TRAMITE_EXPED ADD (D_SIT_ADICIONAL VARCHAR2(255 CHAR));
ALTER TABLE GE_TRAMITE_EXPED_H ADD (D_SIT_ADICIONAL VARCHAR2(255 CHAR));

ALTER TABLE GE_EXPEDIENTES ADD (D_SIT_ADICIONAL VARCHAR2(255 CHAR));
ALTER TABLE GE_EXPEDIENTES_H ADD (D_SIT_ADICIONAL VARCHAR2(255 CHAR));

-- ------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (
T_EXTRACTO CLOB,
L_EXTRACTO_EXPDTE NUMBER(1,0) DEFAULT 0 NOT NULL,
T_ANTECEDENTES CLOB,
L_ANTEC_EXPDTE NUMBER(1,0) DEFAULT 0 NOT NULL
);

ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (
T_EXTRACTO CLOB,
L_EXTRACTO_EXPDTE NUMBER(1,0),
T_ANTECEDENTES CLOB,
L_ANTEC_EXPDTE NUMBER(1,0)
);

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (
D_EXTRACTO VARCHAR(50 CHAR),
D_EXTRACTO_EXPDTE VARCHAR(50 CHAR),
D_ANTECEDENTES VARCHAR(50 CHAR), 
D_ANTEC_EXPDTE VARCHAR(50 CHAR)
);

ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (
D_EXTRACTO VARCHAR(50 CHAR),
D_EXTRACTO_EXPDTE VARCHAR(50 CHAR),
D_ANTECEDENTES VARCHAR(50 CHAR), 
D_ANTEC_EXPDTE VARCHAR(50 CHAR)
);

-- ----------------------

ALTER TABLE GE_EXPEDIENTES ADD ( EXP_USR_MOD_MOTIVO NUMBER(19,0), F_FECHA_HORA_MOD_MOTIVO TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES_H ADD ( EXP_USR_MOD_MOTIVO NUMBER(19,0), F_FECHA_HORA_MOD_MOTIVO TIMESTAMP);

-- ------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (D_NUMERO_PSAN VARCHAR2(50 CHAR));
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (D_NUMERO_PSAN VARCHAR2(50 CHAR));

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_NUMERO_PSAN VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_BT_GENERAR_EXP VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_BT_VINCULAR_EXP VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_NUMERO_PSAN VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_BT_GENERAR_EXP VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_BT_VINCULAR_EXP VARCHAR2(50 CHAR));





SPOOL OFF;
