rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/013_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.13.0 --
--------------------


ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT GE_CFG_TAR_VDOM_TP_TAR_CM_ID_FK  FOREIGN KEY (CFGTAR_VALDOM_TIP_TAR_CAMB_ID)  REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT GE_CFG_TAR_RESP_TAR_VTA_ID_FK  FOREIGN KEY (CFGTAR_RESP_TAREA_VUELTA_ID)  REFERENCES GE_RESP_TRAMITACION;

ALTER TABLE GE_TIPO_TRAMITE ADD CONSTRAINT GE_TIPTRA_VALDOM_TIPINT_ID_FK FOREIGN KEY (TIPTRA_VALDOM_TIPINT_ID) REFERENCES GE_VALORES_DOMINIOS;

-- -----------------

ALTER TABLE GE_EXPEDIENTES ADD CONSTRAINT GE_EXP_USR_MOD_MOTIVO_FK FOREIGN KEY (EXP_USR_MOD_MOTIVO) REFERENCES GE_USUARIOS;




SPOOL OFF;
