rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/003_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.3.0 --
-------------------

DROP TABLE GE_DOMINIOS CASCADE CONSTRAINTS;
DROP TABLE GE_DOMINIOS_H CASCADE CONSTRAINTS;

DROP TABLE GE_VALORES_DOMINIOS CASCADE CONSTRAINTS;
DROP TABLE GE_VALORES_DOMINIOS_H CASCADE CONSTRAINTS;

DROP TABLE GE_EXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_EXPEDIENTES_H CASCADE CONSTRAINTS;

DROP TABLE GE_PERSONAS_EXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_PERSONAS_EXPEDIENTES_H CASCADE CONSTRAINTS;

ALTER TABLE GE_PERSONAS DROP COLUMN PER_VALDOM_SEX_ID;
ALTER TABLE GE_PERSONAS_H DROP COLUMN PER_VALDOM_SEX_ID;

ALTER TABLE GE_PERSONAS DROP COLUMN PER_VALDOM_TIPPER_ID;
ALTER TABLE GE_PERSONAS_H DROP COLUMN PER_VALDOM_TIPPER_ID;

DROP TABLE GE_MATERIAS_TIPEXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_MATERIAS_TIPEXPEDIENTES_H CASCADE CONSTRAINTS;

DROP TABLE GE_SUJETOS_OBLIGADOS_EXPDT CASCADE CONSTRAINTS;
DROP TABLE GE_SUJETOS_OBLIGADOS_EXPDT_H CASCADE CONSTRAINTS;

SPOOL OFF;
