rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/003_UNDO_07_VISTAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

DROP VIEW GE_EXP_PEREXP_SUJEXP;

DROP VIEW GE_LISTADO_MAT_TIPEXP;

SPOOL OFF;
