rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/010_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.10.0 --
--------------------

ALTER TABLE GE_PLAZOS_EXPDTE DROP COLUMN PLAEXP_VALDOM_TIPPLA_ID;
ALTER TABLE GE_PLAZOS_EXPDTE_H DROP COLUMN PLAEXP_VALDOM_TIPPLA_ID; 
ALTER TABLE GE_PLAZOS_EXPDTE ADD PLAEXP_CFGPLAEXP_ID (NUMBER(19,0));
ALTER TABLE GE_PLAZOS_EXPDTE_H ADD PLAEXP_CFGPLAEXP_ID (NUMBER(19,0));

ALTER TABLE GE_TIPO_TRAMITE DROP COLUMN L_INFORMAL;
ALTER TABLE GE_TIPO_TRAMITE_H DROP COLUMN L_INFORMAL;

--------------------
-- DROPS QUE FALTAN EN UNDOS DE SPRINTS ANTERIORES --
--------------------

DROP TABLE GE_COMUNICACIONES;
DROP TABLE GE_MATERIAS;
DROP TABLE GE_MOTIVOSRELACION;
DROP TABLE GE_SEXO;
DROP TABLE GE_TIPOEXPEDIENTES;
DROP TABLE GE_TIPOSPERSONAS;

DROP TABLE GE_COMUNICACIONES_H;
DROP TABLE GE_MATERIAS_H;
DROP TABLE GE_MOTIVOSRELACION_H;
DROP TABLE GE_SEXO_H;
DROP TABLE GE_TIPOEXPEDIENTES_H;
DROP TABLE GE_TIPOSPERSONAS_H;

-- --------------------------------------------------------
-- Comportamiento C011

ALTER TABLE GE_DETALLE_EXPDTE_TRAM   DROP (VALDOM_CANAL_INF_ENT_ID, VALDOM_CANAL_INF_SAL_ID, D_CANAL_ENTRADA);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP (VALDOM_CANAL_INF_ENT_ID, VALDOM_CANAL_INF_SAL_ID, D_CANAL_ENTRADA);

ALTER TABLE GE_CFG_METADATOS_TRAM   DROP (D_CANAL_INF_ENTRADA, D_CANAL_INF_SALIDA);
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP (D_CANAL_INF_ENTRADA, D_CANAL_INF_SALIDA);

-- --------------------------------------------------------
-- Comportamiento C014

ALTER TABLE GE_EXPEDIENTES   DROP (EXP_VALDOM_INSTAPI_ID);
ALTER TABLE GE_EXPEDIENTES_H DROP (EXP_VALDOM_INSTAPI_ID);

ALTER TABLE GE_DETALLE_EXPDTE_TRAM   DROP (DET_VALDOM_INSTAPI_ID, L_API);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP (DET_VALDOM_INSTAPI_ID, L_API);

ALTER TABLE GE_CFG_METADATOS_TRAM   DROP (D_API, D_INSTRUCTOR_API);
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP (D_API, D_INSTRUCTOR_API);

--- -------------------------------------------------------
-- Ampliación de campos de texto largo (restaurar)

ALTER TABLE GE_PLAZOS_EXPDTE MODIFY T_OBSERVACIONES VARCHAR2(255 CHAR);
ALTER TABLE GE_PLAZOS_EXPDTE_H MODIFY T_OBSERVACIONES VARCHAR2(255 CHAR);

ALTER TABLE GE_EXPEDIENTES MODIFY T_MOTIVO VARCHAR2(500 CHAR);
ALTER TABLE GE_EXPEDIENTES_H MODIFY T_MOTIVO VARCHAR2(500 CHAR);

ALTER TABLE GE_TRAMITE_EXPED MODIFY T_OBSERVACIONES VARCHAR2(255 CHAR);
ALTER TABLE GE_TRAMITE_EXPED_H MODIFY T_OBSERVACIONES VARCHAR2(255 CHAR);

ALTER TABLE GE_TAREAS_EXPEDIENTE MODIFY T_OBSERVACIONES VARCHAR2(500 CHAR);
ALTER TABLE GE_TAREAS_EXPEDIENTE_H MODIFY T_OBSERVACIONES VARCHAR2(500 CHAR);

ALTER TABLE GE_TAREAS_EXPEDIENTE MODIFY T_INDICACIONES_SIG VARCHAR2(500 CHAR);
ALTER TABLE GE_TAREAS_EXPEDIENTE_H MODIFY T_INDICACIONES_SIG VARCHAR2(500 CHAR);

ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES MODIFY T_TEXTO VARCHAR2(500 CHAR);
ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES_H MODIFY T_TEXTO VARCHAR2(500 CHAR);



SPOOL OFF;
