rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/010_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

---------------------
-- VERSION 0.10.0 --
---------------------

DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND
PLAAUT_TIPTRAMSUP_ID IS NULL AND V_ORIGEN = 'E' AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RES' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA'))
AND D_ACCION_ESPECIAL IS NULL AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'DN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA_TEMP'))
AND V_TIPO_ACCION = 'C' AND PLAAUT_TIPTRAM_ID IS NULL;

DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND
PLAAUT_TIPTRAMSUP_ID IS NULL AND V_ORIGEN = 'E' AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'ACU' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA'))
AND D_ACCION_ESPECIAL IS NULL AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'DN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA_TEMP'))
AND V_TIPO_ACCION = 'C' AND PLAAUT_TIPTRAM_ID IS NULL;

DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND
PLAAUT_TIPTRAMSUP_ID IS NULL AND V_ORIGEN = 'F' AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RES' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA'))
AND D_ACCION_ESPECIAL IS NULL AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'DN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA_TEMP'))
AND V_TIPO_ACCION = 'C' AND PLAAUT_TIPTRAM_ID IS NULL;

DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND
PLAAUT_TIPTRAMSUP_ID IS NULL AND V_ORIGEN = 'F' AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'ACU' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA'))
AND D_ACCION_ESPECIAL IS NULL AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'DN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA_TEMP'))
AND V_TIPO_ACCION = 'C' AND PLAAUT_TIPTRAM_ID IS NULL;

DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND
PLAAUT_TIPTRAMSUP_ID IS NULL AND V_ORIGEN = 'E' AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RES' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA'))
AND D_ACCION_ESPECIAL IS NULL AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'DN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA_TEMP'))
AND V_TIPO_ACCION = 'C' AND PLAAUT_TIPTRAM_ID IS NULL;

DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND
PLAAUT_TIPTRAMSUP_ID IS NULL AND V_ORIGEN = 'E' AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'ACU' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA'))
AND D_ACCION_ESPECIAL IS NULL AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'DN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA_TEMP'))
AND V_TIPO_ACCION = 'C' AND PLAAUT_TIPTRAM_ID IS NULL;

DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND
PLAAUT_TIPTRAMSUP_ID IS NULL AND V_ORIGEN = 'F' AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RES' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA'))
AND D_ACCION_ESPECIAL IS NULL AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'DN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA_TEMP'))
AND V_TIPO_ACCION = 'C' AND PLAAUT_TIPTRAM_ID IS NULL;

DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND
PLAAUT_TIPTRAMSUP_ID IS NULL AND V_ORIGEN = 'F' AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'ACU' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA'))
AND D_ACCION_ESPECIAL IS NULL AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'DN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA_TEMP'))
AND V_TIPO_ACCION = 'C' AND PLAAUT_TIPTRAM_ID IS NULL;

DELETE FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'COMINF';
DELETE FROM GE_CFG_EXPED_TRAMITE WHERE T_CODIGO 'RCECOMINF01';
DELETE FROM GE_CFG_EXPED_TRAMITE WHERE T_CODIGO 'RCOCOMINF01';
DELETE FROM GE_CFG_EXPED_TRAMITE WHERE T_CODIGO 'PSANCOMINF01';

DELETE FROM GE_CFG_METADATOS_TRAM WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCO') AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'COMINF');
DELETE FROM GE_CFG_METADATOS_TRAM WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCE') AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'COMINF');
DELETE FROM GE_CFG_METADATOS_TRAM WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'PSAN') AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'COMINF');


DELETE FROM GE_CFG_TAREAS WHERE CFGTAR_VALDOM_TIP_EXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'EPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TAREAS');
DELETE FROM GE_CFG_DOC_EXPED_TRAM WHERE CFGDOC_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));

DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'PDT';
DELETE FROM GE_TIPOS_DOCUMENTOS WHERE T_CODIGO = 'PDT';
DELETE FROM GE_CFG_EXPED_SUBTRAM WHERE CFG_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_CFG_EXPED_TRAMITE WHERE CFG_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_SITUACIONES_EXPEDIENTES WHERE SIT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SIT');

DELETE FROM GE_SERIES WHERE T_CODIGO_SERIE = 'XPCSEC';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'XPC';
DELETE FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP');



DELETE FROM GE_CFG_PLAZOS_ESTILOS WHERE PLAEST_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PSAN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PSAN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_CFG_PLAZOS_EXPDTE WHERE PLAEXP_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PSAN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_CFG_METADATOS_TRAM WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PSAN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));



DELETE FROM GE_CFG_DOC_EXPED_TRAM WHERE CFGDOC_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PSAN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));

DELETE FROM GE_CFG_EXPED_SUBTRAM WHERE CFG_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PSAN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_CFG_EXPED_TRAMITE WHERE CFG_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PSAN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));
DELETE FROM GE_SITUACIONES_EXPEDIENTES WHERE SIT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'PSAN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP'));


DELETE FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'INIPSAN';
DELETE FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'PRES';
DELETE FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'ALEG';

DELETE FROM GE_SERIES WHERE T_CODIGO_SERIE = 'PSANSEC';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'PSAN';
DELETE FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP');


UPDATE GE_VALORES_DOMINIOS SET D_DESCRIPCION = 'Reclamación de Protección de Datos por ejercicio de derechos', T_ABREVIATURA = 'Rcl_der', L_BLOQUEADO = 1 WHERE C_CODIGO = 'RCE' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP');
UPDATE GE_VALORES_DOMINIOS SET D_DESCRIPCION = 'Reclamación de Protección de Datos por otras infracciones', T_ABREVIATURA = 'Rcl_infr', L_BLOQUEADO = 1 WHERE C_CODIGO = 'RCO' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP');


DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'REHABTRAM');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'REHABTRAM';


DELETE FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'CA' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SIT');
DELETE FROM GE_SITUACIONES_EXPEDIENTES WHERE SIT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND C_CODREL = 'XPCCA01';
INSERT INTO GE_SITUACIONES_EXPEDIENTES (SIT_ID, F_CREACION, USU_CREACION, C_CODREL, SIT_VALDOM_TIPEXP_ID, SIT_VALDOM_SIT_ID, D_DESCRIPCION, D_DESC_ABREV, N_NIVEL_ANIDAMIENTO, N_ORDEN, SIT_SIT_SUPER_ID, L_ACTIVO, L_SIT_INICIAL, L_SIT_FINAL)  VALUES (S_SITUACIONES_EXPEDIENTES.NEXTVAL, SYSDATE, (SELECT USER FROM DUAL), 'XPCFN01', (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')), (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'FN' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SIT')), 'Finalizado','FN', 2, 1, (SELECT SIT_ID FROM GE_SITUACIONES_EXPEDIENTES WHERE C_CODREL = 'XPCPD01'), 1, 0, 1);

-- --------------------------------------------------------
-- Comportamiento C011

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'CANCOMINF');
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'CANCOMINF';

-- --------------------------------------------------------
-- Comportamiento C014

DELETE FROM GE_CFG_PLAZOS_AUT 
WHERE   PLAAUT_TIPTRAM_ID =   (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'ACIAPI')
	AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'NOT' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_PLA'))
	AND PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'RCO' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_EXP'))
	AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'DN' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_PLA_TEMP'))
;
DELETE FROM GE_CFG_PLAZOS_AUT 
WHERE   PLAAUT_TIPTRAM_ID =   (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'ACIAPI')
	AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'RES' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_PLA'))
	AND PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'RCO' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_EXP'))
	AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'DN' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_PLA_TEMP'))
;

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'INSTAPI');
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'INSTAPI';

-- -----------------------------------
-- Comportamiento C017
DELETE FROM GE_CFG_EXPED_TRAMITE WHERE T_CODIGO = 'RCOCOMF01';
DELETE FROM GE_CFG_EXPED_TRAMITE WHERE T_CODIGO = 'RCECOMF01';
DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_TIPTRAM_ID IN (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'COMFORM');
DELETE FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'COMFORM';

-- --------------------------------------------------------
-- metadatos tramite COMFORM

DELETE FROM GE_CFG_METADATOS_TRAM WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCO') AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'COMFORM');

DELETE FROM GE_CFG_METADATOS_TRAM WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCE') AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'COMFORM');

DELETE FROM GE_CFG_METADATOS_TRAM WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'PSAN') AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'COMFORM');



--------------------------------------------------------------------
-- ACTUALIZACIÓN FORMATO SERIE EXPEDIENTES PENDIENTE CALIFICACIÓN --
--------------------------------------------------------------------

UPDATE GE_SERIES SET T_PATRON = 'DPC-2022/(3)' WHERE T_CODIGO_SERIE = 'XPCSEC';



SPOOL OFF;
