rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/015_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.15.0 --
--------------------
ALTER TABLE GE_CONEXIONES_USUARIOS ADD (T_IP_CONEXION VARCHAR2(50 CHAR) NULL, T_EQUIPO_CONEXION VARCHAR2(50 CHAR) NULL);

-- -----------------------------------

ALTER TABLE GE_DOCUMENTOS   ADD ( F_ULT_EDICION TIMESTAMP, DOC_USU_EDITA_ID NUMBER(10,0) );
ALTER TABLE GE_DOCUMENTOS_H ADD ( F_ULT_EDICION TIMESTAMP, DOC_USU_EDITA_ID NUMBER(10,0) );
COMMENT ON COLUMN GE_DOCUMENTOS.F_ULT_EDICION       IS 'Fecha de la última vez que se editó y se modificó el fichero de documento asociado.';
COMMENT ON COLUMN GE_DOCUMENTOS.DOC_USU_EDITA_ID    IS 'ID del último usuario que editó y modificó el fichero de documento asociado.';

-- -----------------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (F_FECHA_REGISTRO TIMESTAMP);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (F_FECHA_REGISTRO TIMESTAMP);

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_FECHA_REGISTRO VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_FECHA_REGISTRO VARCHAR2(50 CHAR));

-- -----------------
ALTER TABLE GE_EXPEDIENTES ADD (L_TRAMITACION_ANONIMA NUMBER(1,0) DEFAULT 0 NOT NULL, L_ABSTENCION_RECUSACION NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE GE_EXPEDIENTES_H ADD (L_TRAMITACION_ANONIMA NUMBER(1,0), L_ABSTENCION_RECUSACION NUMBER(1,0));

-- -----------------

ALTER TABLE GE_USUARIOS ADD (T_UID_SSO VARCHAR2 (50 CHAR) NULL);
ALTER TABLE GE_USUARIOS_H ADD (T_UID_SSO VARCHAR2 (50 CHAR) NULL);

-- ----------------

ALTER TABLE GE_EXPEDIENTES ADD (D_DESC_SEG1 VARCHAR2(20 CHAR) NULL, D_INF_SEG1 VARCHAR2(50 CHAR) NULL, D_DESC_SEG2 VARCHAR2(20 CHAR) NULL, D_INF_SEG2 VARCHAR2(50 CHAR) NULL, D_DESC_SEG3 VARCHAR2(20 CHAR) NULL, D_INF_SEG3 VARCHAR2(50 CHAR) NULL);
ALTER TABLE GE_EXPEDIENTES_H ADD (D_DESC_SEG1 VARCHAR2(20 CHAR) NULL, D_INF_SEG1 VARCHAR2(50 CHAR) NULL, D_DESC_SEG2 VARCHAR2(20 CHAR) NULL, D_INF_SEG2 VARCHAR2(50 CHAR) NULL, D_DESC_SEG3 VARCHAR2(20 CHAR) NULL, D_INF_SEG3 VARCHAR2(50 CHAR) NULL);

------------

ALTER TABLE GE_EXPEDIENTES ADD (T_DESCRIPCION VARCHAR2(4000 CHAR));
ALTER TABLE GE_EXPEDIENTES ADD (EXP_USR_MOD_DESC NUMBER(19,0));
ALTER TABLE GE_EXPEDIENTES ADD (F_FECHA_HORA_MOD_DESC TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES ADD (F_FECHA_INFRACCION TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES ADD (L_INFRACCION_CONT NUMBER(1,0) DEFAULT 0);
ALTER TABLE GE_EXPEDIENTES ADD (EXP_VALDOM_GRAV NUMBER(19,0));
ALTER TABLE GE_EXPEDIENTES ADD (F_FECHA_PRESCRIPCIOM TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES ADD (F_FECHA_SOLIC_EJ TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES ADD (L_RESPUESTA_SOLIC NUMBER(1,0) DEFAULT 0);
ALTER TABLE GE_EXPEDIENTES ADD (L_RESPUESTA_INSAT NUMBER(1,0) DEFAULT 0 );
ALTER TABLE GE_EXPEDIENTES ADD (F_FECHA_RESP_SOLIC_EJ TIMESTAMP);

ALTER TABLE GE_EXPEDIENTES_H ADD (T_DESCRIPCION VARCHAR2(4000 CHAR));
ALTER TABLE GE_EXPEDIENTES_H ADD (EXP_USR_MOD_DESC NUMBER(19,0));
ALTER TABLE GE_EXPEDIENTES_H ADD (F_FECHA_HORA_MOD_DESC TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES_H ADD (F_FECHA_INFRACCION TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES_H ADD (L_INFRACCION_CONT NUMBER(1,0) DEFAULT 0);
ALTER TABLE GE_EXPEDIENTES_H ADD (EXP_VALDOM_GRAV NUMBER(19,0));
ALTER TABLE GE_EXPEDIENTES_H ADD (F_FECHA_PRESCRIPCIOM TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES_H ADD (F_FECHA_SOLIC_EJ TIMESTAMP);
ALTER TABLE GE_EXPEDIENTES_H ADD (L_RESPUESTA_SOLIC NUMBER(1,0) DEFAULT 0);
ALTER TABLE GE_EXPEDIENTES_H ADD (L_RESPUESTA_INSAT NUMBER(1,0) DEFAULT 0 );
ALTER TABLE GE_EXPEDIENTES_H ADD (F_FECHA_RESP_SOLIC_EJ TIMESTAMP);

ALTER TABLE GE_EXPEDIENTES MODIFY T_MOTIVO VARCHAR2(500 CHAR);
ALTER TABLE GE_EXPEDIENTES_H MODIFY T_MOTIVO VARCHAR2(500 CHAR);

ALTER TABLE GE_EXPEDIENTES ADD (EXP_VALDOM_ORIGREC NUMBER(19,0));
ALTER TABLE GE_EXPEDIENTES_H ADD (EXP_VALDOM_ORIGREC NUMBER(19,0));



SPOOL OFF;
