rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/015_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.15.0 --
--------------------


ALTER TABLE GE_DOCUMENTOS   ADD CONSTRAINT DOC_USU_EDITA_FK FOREIGN KEY (DOC_USU_EDITA_ID)  REFERENCES GE_USUARIOS;

---------

ALTER TABLE GE_EXPEDIENTES ADD CONSTRAINT GE_EXP_USR_MOD_DESC_FK FOREIGN KEY (EXP_USR_MOD_DESC) REFERENCES GE_USUARIOS;
ALTER TABLE GE_EXPEDIENTES ADD CONSTRAINT GE_EXP_VALDOM_GRAV_FK FOREIGN KEY (EXP_VALDOM_GRAV) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_EXPEDIENTES ADD CONSTRAINT GE_EXP_VALDOM_ORIGREC_FK FOREIGN KEY (EXP_VALDOM_ORIGREC) REFERENCES GE_VALORES_DOMINIOS;



SPOOL OFF;
