rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/010_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.10.0 --
--------------------

ALTER TABLE GE_PLAZOS_EXPDTE ADD CONSTRAINT GE_PLAEXP_VALDOMTIPPLA_FK FOREIGN KEY (PLAEXP_VALDOM_TIPPLA_ID) REFERENCES GE_VALORES_DOMINIOS;

-- Comportamiento C011
ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD CONSTRAINT GE_VALDOM_CANAL_INF_ENT_ID_FK FOREIGN KEY (VALDOM_CANAL_INF_ENT_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD CONSTRAINT GE_VALDOM_CANAL_INF_SAL_ID_FK FOREIGN KEY (VALDOM_CANAL_INF_SAL_ID) REFERENCES GE_VALORES_DOMINIOS;

-- Comportamiento C014
ALTER TABLE GE_EXPEDIENTES         ADD CONSTRAINT GE_EXP_VALDOM_INSTAPI_ID_FK FOREIGN KEY (EXP_VALDOM_INSTAPI_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD CONSTRAINT GE_DET_VALDOM_INSTAPI_ID_FK FOREIGN KEY (DET_VALDOM_INSTAPI_ID) REFERENCES GE_VALORES_DOMINIOS;


SPOOL OFF;
