rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/011_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.11.0 --
--------------------


ALTER TABLE GE_TRAMITE_EXPED ADD TRAM_EXP_USU_ALTA_ID NUMBER(19,0);
ALTER TABLE GE_TRAMITE_EXPED_H ADD TRAM_EXP_USU_ALTA_ID NUMBER(19,0);


CREATE TABLE GE_RESOLUCIONES (RES_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ANONIMIZADA NUMBER(1,0) DEFAULT 0, T_CODIGO_RESOL VARCHAR2(50 CHAR), F_FECHA_PUBLI_WEB TIMESTAMP, F_FECHA_RESOLUCION TIMESTAMP, N_VERSION NUMBER(19,0), L_NOTIFICADA_TOTAL NUMBER(1,0) DEFAULT 0, D_RESUMEN VARCHAR2(400 CHAR), RESOL_VALDOMTIPORESOL_ID NUMBER(19,0), RESOL_VALDOMSENTRESOL_ID NUMBER(19,0));
CREATE TABLE GE_RESOLUCIONES_H (RES_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ANONIMIZADA NUMBER(1,0), T_CODIGO_RESOL VARCHAR2(255 CHAR), F_FECHA_PUBLI_WEB TIMESTAMP, F_FECHA_RESOLUCION TIMESTAMP, N_VERSION NUMBER(19,0), L_NOTIFICADA_TOTAL NUMBER(1,0), D_RESUMEN VARCHAR2(255 CHAR), RESOL_VALDOMTIPORESOL_ID NUMBER(19,0), RESOL_VALDOMSENTRESOL_ID NUMBER(19,0));

CREATE TABLE GE_RESOL_EXPEDIENTES (RESEXP_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), RESEXP_EXP_ID NUMBER(19,0), RESEXP_RES_ID NUMBER(19,0), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(1,0) NOT NULL);
CREATE TABLE GE_RESOL_EXPEDIENTES_H (RESEXP_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), RESEXP_EXP_ID NUMBER(19,0), RESEXP_RES_ID NUMBER(19,0), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(1,0));

CREATE TABLE GE_RESOL_SUJOBL (RESSUJOBL_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), F_FECHA_NOTIFICACION TIMESTAMP, RESSUJOBL_RES_ID NUMBER(19,0), RESSUJOBL_SUJOBL_ID NUMBER(19,0), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(1,0) NOT NULL);
CREATE TABLE GE_RESOL_SUJOBL_H (RESSUJOBL_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), F_FECHA_NOTIFICACION TIMESTAMP, RESSUJOBL_RES_ID NUMBER(19,0), RESSUJOBL_SUJOBL_ID NUMBER(19,0), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(1,0));

CREATE TABLE GE_RESOL_PERSONA (RESPER_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), F_FECHA_NOTIFICACION TIMESTAMP, RESPER_PER_ID NUMBER(19,0), RESPER_RES_ID NUMBER(19,0), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(1,0) NOT NULL);
CREATE TABLE GE_RESOL_PERSONA_H (RESPER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), F_FECHA_NOTIFICACION TIMESTAMP, RESPER_PER_ID NUMBER(19,0), RESPER_RES_ID NUMBER(19,0), N_VERSION NUMBER(19,0), N_PRINCIPAL NUMBER(1,0));

CREATE TABLE GE_ARTICULOS_AFECTAD_RESOL (ART_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), N_VERSION NUMBER(19,0), ART_RES_ID NUMBER(19,0) NOT NULL, ART_VALDOM_ART_ID NUMBER(19,0) NOT NULL);
CREATE TABLE GE_ARTICULOS_AFECTAD_RESOL_H (ART_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), ART_RES_ID NUMBER(19,0), ART_VALDOM_ART_ID NUMBER(19,0));

CREATE TABLE GE_DERECH_RECLAM_RESOL (DER_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), N_VERSION NUMBER(19,0), DER_RES_ID NUMBER(19,0) NOT NULL, DER_VALDOM_DERRECL_ID NUMBER(19,0) NOT NULL);
CREATE TABLE GE_DERECH_RECLAM_RESOL_H (DER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), DER_RES_ID NUMBER(19,0), DER_VALDOM_DERRECL_ID NUMBER(19,0));
	
CREATE TABLE GE_DOCUMENTOS_RESOLUCIONES (DOCRES_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ANONIMIZADO NUMBER(1,0) DEFAULT 0, F_FECHA_PUBLI_WEB TIMESTAMP, N_VERSION NUMBER(19,0), DOCRES_DOC_ID NUMBER(19,0), DOCRES_RES_ID NUMBER(19,0));
CREATE TABLE GE_DOCUMENTOS_RESOLUCIONES_H (DOCRES_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ANONIMIZADO NUMBER(1,0), F_FECHA_PUBLI_WEB TIMESTAMP, N_VERSION NUMBER(19,0), DOCRES_DOC_ID NUMBER(19,0), DOCRES_RES_ID NUMBER(19,0));

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (F_FECHA_RESOLUCION TIMESTAMP);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (F_FECHA_RESOLUCION TIMESTAMP);

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_FECHA_RESOLUCION VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_FECHA_RESOLUCION VARCHAR2(50 CHAR));

-- -------------------------------------

ALTER TABLE GE_TAREAS_EXPEDIENTE   ADD (L_URGENTE NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE GE_TAREAS_EXPEDIENTE_H ADD (L_URGENTE NUMBER(1,0));

ALTER TABLE GE_EXPEDIENTES   ADD ( T_EXPEDIENTE_IDENTIFICADO VARCHAR2(255) );
ALTER TABLE GE_EXPEDIENTES_H ADD ( T_EXPEDIENTE_IDENTIFICADO VARCHAR2(255) );


CREATE TABLE GE_ACCESOS_DOCS (
	ACD_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0), 
	F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), 
	ACD_DOC_ID NUMBER(19,0) NOT NULL,
	N_VERSION_DOC NUMBER(19,0) NOT NULL,
	ACD_USU_ID NUMBER(19,0) NOT NULL,
	F_FECHA_HORA_ACCESO TIMESTAMP NOT NULL,
	ACD_VALDOMTIPACC_ID NUMBER(19,0) NOT NULL,
	ACD_EXP_ID NUMBER(19,0) NOT NULL,
	ACD_TRAM_ID NUMBER(19,0),
	L_EVOLUCION NUMBER(1,0) DEFAULT 0 NOT NULL, 
	ACD_TAREA_ID NUMBER(19,0)
);

CREATE TABLE GE_ACCESOS_DOCS_H (
	ACD_ID NUMBER(19,0), N_VERSION NUMBER(19,0), 
	REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0),
	ACD_DOC_ID NUMBER(19,0),
	N_VERSION_DOC NUMBER(19,0),
	ACD_USU_ID NUMBER(19,0),
	F_FECHA_HORA_ACCESO TIMESTAMP,
	ACD_VALDOMTIPACC_ID NUMBER(19,0),
	ACD_EXP_ID NUMBER(19,0),
	ACD_TRAM_ID NUMBER(19,0),
	L_EVOLUCION NUMBER(1,0), 
	ACD_TAREA_ID NUMBER(19,0)
);

--------------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (DETEXPTRAM_VALDOMTIPRES_ID NUMBER(19,0));
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (DETEXPTRAM_VALDOMTIPRES_ID NUMBER(19,0));

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_TIPO_RESOLUCION VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_TIPO_RESOLUCION VARCHAR2(50 CHAR));


-- -----------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM   ADD (DETEXPTRAM_VALDOMRESNOTIF_ID NUMBER(19, 0));
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (DETEXPTRAM_VALDOMRESNOTIF_ID NUMBER(19, 0));

-- ----------------------------

ALTER TABLE GE_PERFILES ADD ( D_DESCRIPCION_CORTA VARCHAR2(25 CHAR));
ALTER TABLE GE_PERFILES_H ADD ( D_DESCRIPCION_CORTA VARCHAR2(25 CHAR));



ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN T_RESPONSABLE;


SPOOL OFF;
