rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/011_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.11.0 --
-------------------

CREATE SEQUENCE S_RESOLUCION START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_RESOL_EXPEDIENTES START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_RESOL_SUJOBL START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_RESOL_PERS START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_ARTICULOS_AFECTAD_RESOL START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_DERECH_RECLAM_RESOL START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_DOCUMENTOS_RESOLUCIONES START WITH 1 INCREMENT BY  1;

CREATE SEQUENCE S_ACCESOS_DOCS START WITH 1 INCREMENT BY  1;

SPOOL OFF;
