rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/011_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.11.0 --
--------------------


ALTER TABLE GE_RESOLUCIONES ADD CONSTRAINT GE_RESOL_VALDOMTIPORESOL_FK FOREIGN KEY (RESOL_VALDOMTIPORESOL_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_RESOLUCIONES ADD CONSTRAINT GE_RESOL_VALDOMSENTRESOL_FK FOREIGN KEY (RESOL_VALDOMSENTRESOL_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_RESOLUCIONES_H ADD CONSTRAINT GE_RESOLUCIONES_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_RESOL_EXPEDIENTES ADD CONSTRAINT GE_RESEXP_EXP_ID_FK FOREIGN KEY (RESEXP_EXP_ID) REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_RESOL_EXPEDIENTES ADD CONSTRAINT GE_RESEXP_RES_ID_FK FOREIGN KEY (RESEXP_RES_ID) REFERENCES GE_RESOLUCIONES;
ALTER TABLE GE_RESOL_EXPEDIENTES_H ADD CONSTRAINT GE_RESOL_EXPED_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_RESOL_SUJOBL ADD CONSTRAINT GE_RESSUJOBL_RES_ID_FK FOREIGN KEY (RESSUJOBL_RES_ID) REFERENCES GE_RESOLUCIONES;
ALTER TABLE GE_RESOL_SUJOBL ADD CONSTRAINT GE_RESSUJOBL_SUJOBL_ID_FK FOREIGN KEY (RESSUJOBL_SUJOBL_ID) REFERENCES GE_SUJETOS_OBLIGADOS;
ALTER TABLE GE_RESOL_SUJOBL_H ADD CONSTRAINT GE_RESOL_SUJOBL_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_RESOL_PERSONA ADD CONSTRAINT GE_RESPER_PER_ID_FK FOREIGN KEY (RESPER_PER_ID) REFERENCES GE_PERSONAS;
ALTER TABLE GE_RESOL_PERSONA ADD CONSTRAINT GE_RESPER_RES_ID_FK FOREIGN KEY (RESPER_RES_ID) REFERENCES GE_RESOLUCIONES;
ALTER TABLE GE_RESOL_PERSONA_H ADD CONSTRAINT GE_RESOL_PERSONA_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_ARTICULOS_AFECTAD_RESOL ADD CONSTRAINT GE_ART_RES_FK FOREIGN KEY (ART_RES_ID) REFERENCES GE_RESOLUCIONES;
ALTER TABLE GE_ARTICULOS_AFECTAD_RESOL ADD CONSTRAINT GE_ART_VALDOM_ART_FK FOREIGN KEY (ART_VALDOM_ART_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_ARTICULOS_AFECTAD_RESOL_H ADD CONSTRAINT GE_ART_AFEC_RESOL_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_DERECH_RECLAM_RESOL ADD CONSTRAINT GE_DER_RES_FK FOREIGN KEY (DER_RES_ID) REFERENCES GE_RESOLUCIONES;
ALTER TABLE GE_DERECH_RECLAM_RESOL ADD CONSTRAINT GE_DER_VALDOM_DERRECLAM_FK FOREIGN KEY (DER_VALDOM_DERRECL_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_DERECH_RECLAM_RESOL_H ADD CONSTRAINT GE_DER_RECL_RES_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES ADD CONSTRAINT DOCRES_DOC_FK FOREIGN KEY (DOCRES_DOC_ID) REFERENCES GE_DOCUMENTOS;
ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES ADD CONSTRAINT DOCRES_RES_FK FOREIGN KEY (DOCRES_RES_ID) REFERENCES GE_RESOLUCIONES;
ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES_H ADD CONSTRAINT GE_DOC_RESOL_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

-- ----------

ALTER TABLE GE_ACCESOS_DOCS ADD CONSTRAINT GE_ACD_DOC_ID_FK   FOREIGN KEY (ACD_DOC_ID)   REFERENCES GE_DOCUMENTOS;
ALTER TABLE GE_ACCESOS_DOCS ADD CONSTRAINT GE_ACD_USU_ID_FK   FOREIGN KEY (ACD_USU_ID)   REFERENCES GE_USUARIOS;
ALTER TABLE GE_ACCESOS_DOCS ADD CONSTRAINT GE_ACD_VALDOMTIPACC_FK FOREIGN KEY (ACD_VALDOMTIPACC_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_ACCESOS_DOCS ADD CONSTRAINT GE_ACD_EXP_ID_FK   FOREIGN KEY (ACD_EXP_ID)   REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_ACCESOS_DOCS ADD CONSTRAINT GE_ACD_TRAM_ID_FK  FOREIGN KEY (ACD_TRAM_ID)  REFERENCES GE_TRAMITE_EXPED;
ALTER TABLE GE_ACCESOS_DOCS ADD CONSTRAINT GE_ACD_TAREA_ID_FK FOREIGN KEY (ACD_TAREA_ID) REFERENCES GE_TAREAS_EXPEDIENTE;

ALTER TABLE GE_ACCESOS_DOCS_H ADD CONSTRAINT GE_ACCESOS_DOCS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

-- ----------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD CONSTRAINT GE_DETEXPTRAM_VALDOMRESNOTIF_FK FOREIGN KEY (DETEXPTRAM_VALDOMRESNOTIF_ID) REFERENCES GE_VALORES_DOMINIOS;

SPOOL OFF;
