rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/011_06_GRANTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.11.0 --
-------------------

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_RESOLUCIONES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_RESOLUCION TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_RESOLUCIONES_H TO GE_ROL_GESTOR_DML;


GRANT SELECT, UPDATE, INSERT, DELETE ON GE_RESOL_EXPEDIENTES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_RESOL_EXPEDIENTES TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_RESOL_EXPEDIENTES_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_RESOL_SUJOBL TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_RESOL_SUJOBL TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_RESOL_SUJOBL_H TO GE_ROL_GESTOR_DML;


GRANT SELECT, UPDATE, INSERT, DELETE ON GE_RESOL_PERSONA TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_RESOL_PERS TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_RESOL_PERSONA_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_ARTICULOS_AFECTAD_RESOL TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_ARTICULOS_AFECTAD_RESOL TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_ARTICULOS_AFECTAD_RESOL_H TO GE_ROL_GESTOR_DML;


GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DERECH_RECLAM_RESOL TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_DERECH_RECLAM_RESOL TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DERECH_RECLAM_RESOL_H TO GE_ROL_GESTOR_DML;


GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DOCUMENTOS_RESOLUCIONES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_DOCUMENTOS_RESOLUCIONES TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DOCUMENTOS_RESOLUCIONES_H TO GE_ROL_GESTOR_DML;

-- -----------

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_ACCESOS_DOCS TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_ACCESOS_DOCS TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_ACCESOS_DOCS_H TO GE_ROL_GESTOR_DML;

-- -----------

GRANT SELECT ON GE_LISTADO_RESOLUCIONES TO GE_ROL_GESTOR_DML;




SPOOL OFF;
