rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/FORMACION_GRS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

----------------------------
-- VERSION GONZALO RANDO --
----------------------------

CREATE TABLE GESTOR.FOR_PRUEBAS_GRS (
	PRU_ID NUMBER(19,0) NOT NULL, 
	F_CREACION TIMESTAMP, 
	F_MODIFICACION TIMESTAMP, 
	N_VERSION NUMBER(19,0), 
	USU_CREACION VARCHAR2(25 CHAR), 
	USU_MODIFICACION VARCHAR2(25 CHAR), 
	L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, 
	C_CODIGO VARCHAR2(50 CHAR) NOT NULL, 
	D_DESCRIPCION VARCHAR2(255 CHAR) NOT NULL,
	FORPRU_GRS_USU NUMBER(19,0)
) TABLESPACE GESTOR_DAT;

COMMENT ON TABLE GESTOR.FOR_PRUEBAS_GRS IS 'Tabla para ejercicio de pruebas';
COMMENT ON COLUMN GESTOR.FOR_PRUEBAS_GRS.PRU_ID IS 'PK';
COMMENT ON COLUMN GESTOR.FOR_PRUEBAS_GRS.F_CREACION IS 'Fecha de creación del registro';
COMMENT ON COLUMN GESTOR.FOR_PRUEBAS_GRS.L_ACTIVA IS 'Indica si el elemento está o no activo';
COMMENT ON COLUMN GESTOR.FOR_PRUEBAS_GRS.D_DESCRIPCION IS 'Descripción del registro';
COMMENT ON COLUMN GESTOR.FOR_PRUEBAS_GRS.FORPRU_GRS_USU IS 'FK de usuarios';

CREATE TABLE GESTOR.FOR_PRUEBAS_GRS_H (
	PRU_ID NUMBER(19,0) NOT NULL, 
	REV NUMBER(19,0) NOT NULL, 
	REVTYPE NUMBER(3,0),  
	N_VERSION NUMBER(19,0), 
	L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, 
	C_CODIGO VARCHAR2(2 CHAR) NOT NULL, 
	D_DESCRIPCION VARCHAR2(255 CHAR) NOT NULL,
	FORPRU_GRS_USU NUMBER(19,0)
) TABLESPACE GESTOR_DAT;

CREATE SEQUENCE GESTOR.S_FOR_PRUEBAS_GRS START WITH 1 INCREMENT BY  1;

ALTER TABLE GESTOR.FOR_PRUEBAS_GRS ADD CONSTRAINT GESTOR.FOR_PRUEBAS_GRS_PK PRIMARY KEY (PRU_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GESTOR.FOR_PRUEBAS_GRS ADD CONSTRAINT GESTOR.FOR_PRUEBAS_GRS_H_PK PRIMARY KEY (PRU_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GESTOR.FOR_PRUEBAS_GRS_H ADD CONSTRAINT GESTOR.FOR_PRUEBAS_GRS_USU FOREIGN KEY (FORPRU_GRS_USU) REFERENCES GE_USUARIOS;
ALTER TABLE GESTOR.FOR_PRUEBAS_GRS ADD CONSTRAINT GESTOR.FOR_PRUEBAS_GRS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;


INSERT INTO GESTOR.FOR_PRUEBAS_GRS (PRU_ID, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (GESTOR.S_FOR_PRUEBAS_GRS.NEXTVAL, SYSDATE, (SELECT USER FROM DUAL), 'P1', 'Prueba 1', 1);
INSERT INTO GESTOR.FOR_PRUEBAS_GRS (PRU_ID, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (GESTOR.S_FOR_PRUEBAS_GRS.NEXTVAL, SYSDATE, (SELECT USER FROM DUAL), 'P2', 'Prueba 2', 1);
INSERT INTO GESTOR.FOR_PRUEBAS_GRS (PRU_ID, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (GESTOR.S_FOR_PRUEBAS_GRS.NEXTVAL, SYSDATE, (SELECT USER FROM DUAL), 'P3', 'Prueba 3', 1);
INSERT INTO GESTOR.FOR_PRUEBAS_GRS (PRU_ID, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION, FORPRU_GRS_USU) VALUES (GESTOR.S_FOR_PRUEBAS_GRS.NEXTVAL, SYSDATE, (SELECT USER FROM DUAL), 'P4', 'Prueba 4', 1, (SELECT USU_ID FROM GESTOR.GE_USUARIOS WHERE T_LOGIN = 'gonzalo.rando'));

GRANT SELECT, UPDATE, INSERT, DELETE ON GESTOR.FOR_PRUEBAS_GRS TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON GESTOR.S_FOR_PRUEBAS_GRS TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GESTOR.FOR_PRUEBAS_GRS_H TO GE_ROL_GESTOR_DML;

SPOOL OFF;
