rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/FORMACION_GRS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

----------------------------
-- VERSION GONZALO RANDO --
----------------------------

--Añadimos la columna--
ALTER TABLE GESTOR.GE_TIPO_TRAMITE ADD L_ALTA_MASIVA NUMBER(1,0) DEFAULT 0 NOT NULL;


--Select con todos los valores--
SELECT * FROM GESTOR.GE_TIPO_TRAMITE gtt
	WHERE gtt.D_DESC_ABREV = 'Notif' OR
		gtt.D_DESC_ABREV = 'Firma Doc';

		
--Cambiar los valores--
UPDATE 
(SELECT * FROM GESTOR.GE_TIPO_TRAMITE gtt
	WHERE gtt.D_DESC_ABREV = 'Notif' OR
		gtt.D_DESC_ABREV = 'Firma Doc') t
SET t.L_ALTA_MASIVA=1;



--Creacion de permisos--
INSERT INTO GESTOR.GE_PERMISOS (PER_ID, F_CREACION, USU_CREACION, L_ACTIVA, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (GESTOR.S_PERMISOS.NEXTVAL,SYSDATE,  (SELECT TIP_TRA_ID FROM GESTOR.GE_TIPO_TRAMITE gtt WHERE T_CODIGO = 'ERR'), 1, 'TIPO_TRAMITE_GRS', 'Permisos para tipos de tramites Gonzalo Rando Serna', 1);
INSERT INTO GESTOR.GE_PERMISOS_PERFILES (PERM_PERF_ID, F_CREACION, USU_CREACION, L_ACTIVA, N_VERSION, PERMPERF_PERF_ID, PERMPERF_PERM_ID) VALUES (GESTOR.S_PERMISOS_PERFILES.NEXTVAL,SYSDATE,  (SELECT TIP_TRA_ID FROM GESTOR.GE_TIPO_TRAMITE gtt WHERE T_CODIGO = 'ERR'), 1, 1,(SELECT PER_ID FROM GESTOR.GE_PERFILES gp WHERE C_CODIGO = 'ADMIN'), (SELECT PER_ID FROM GESTOR.GE_PERMISOS gp WHERE C_CODIGO = 'TIPO_TRAMITE_GRS'));

SPOOL OFF;
