rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/FORMACION_GRS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

----------------------------
-- VERSION GONZALO RANDO --
----------------------------

--Añadimos la columna--
ALTER TABLE GESTOR.GE_DETALLE_EXPDTE_TRAM ADD L_ESPERA_DOC NUMBER(1,0) DEFAULT 0 NOT NULL;


--Inserts--
INSERT INTO GESTOR.GE_DETALLE_EXPDTE_TRAM (DET_EXP_ID, DETEXPTRAM_TRAMEXP_ID, L_ACTIVO , F_CREACION, USU_CREACION, N_VERSION) VALUES (GESTOR.S_DETALLE_EXPDTE_TRAM.NEXTVAL, 22, 1,  SYSDATE, (SELECT USER FROM DUAL), 1);
INSERT INTO GESTOR.GE_DETALLE_EXPDTE_TRAM (DET_EXP_ID, DETEXPTRAM_TRAMEXP_ID, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (GESTOR.S_DETALLE_EXPDTE_TRAM.NEXTVAL, 23, 1,  SYSDATE, (SELECT USER FROM DUAL), 1);
INSERT INTO GESTOR.GE_DETALLE_EXPDTE_TRAM (DET_EXP_ID, DETEXPTRAM_TRAMEXP_ID, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (GESTOR.S_DETALLE_EXPDTE_TRAM.NEXTVAL, 24, 1,  SYSDATE, (SELECT USER FROM DUAL), 1);
INSERT INTO GESTOR.GE_DETALLE_EXPDTE_TRAM (DET_EXP_ID, DETEXPTRAM_TRAMEXP_ID, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (GESTOR.S_DETALLE_EXPDTE_TRAM.NEXTVAL, 25, 1,  SYSDATE, (SELECT USER FROM DUAL), 1);


--Tipo tramite correcto--
INSERT INTO GESTOR.GE_TRAMITE_EXPED (TRAM_EXP_ID, TRAM_EXP_EXP_ID, TRAM_EXP_TIP_TRA_ID, N_NIVEL, TRAM_EXP_TRAMEXPSUP_ID, F_FECHA_INI, L_FINALIZADO, L_ACTIVO) VALUES (GESTOR.S_FOR_PRUEBAS_GRS.NEXTVAL, 1, (SELECT TIP_TRA_ID FROM GESTOR.GE_TIPO_TRAMITE gtt WHERE T_CODIGO = 'TRDPD'),1,1, SYSDATE, 0, 1);;
--Tipo tramite incorrecto--
INSERT INTO GESTOR.GE_TRAMITE_EXPED (TRAM_EXP_ID, TRAM_EXP_EXP_ID, TRAM_EXP_TIP_TRA_ID, N_NIVEL, TRAM_EXP_TRAMEXPSUP_ID, F_FECHA_INI, L_FINALIZADO, L_ACTIVO) VALUES (GESTOR.S_FOR_PRUEBAS_GRS.NEXTVAL, 1, (SELECT TIP_TRA_ID FROM GESTOR.GE_TIPO_TRAMITE gtt WHERE T_CODIGO = 'ERR'),1,1, SYSDATE, 0, 1);;


--Select con todos los valores--
SELECT * FROM GESTOR.GE_DETALLE_EXPDTE_TRAM gdet
	LEFT JOIN GESTOR.GE_TRAMITE_EXPED gte
		ON gdet.DETEXPTRAM_TRAMEXP_ID = gte.TRAM_EXP_ID
	LEFT JOIN GESTOR.GE_TIPO_TRAMITE gtt 
		ON gte.TRAM_EXP_TIP_TRA_ID = gtt.TIP_TRA_ID
	WHERE gtt.T_CODIGO = 'TRDPD' OR
		gtt.T_CODIGO = 'SUB' OR
		gtt.T_CODIGO = 'REQINF' OR
		gtt.T_CODIGO = 'PETINFRTE' OR
		gtt.T_CODIGO = 'PETINFTER' OR
		gtt.T_CODIGO = 'REQCUMPL' OR
		gtt.T_CODIGO = 'RREQCUMPL' OR
		gtt.T_CODIGO = 'TRREC' OR
		gtt.T_CODIGO = 'RREQINF';

		
--Cambiar los valores--
UPDATE 
(SELECT * FROM GESTOR.GE_DETALLE_EXPDTE_TRAM gdet
	LEFT JOIN GESTOR.GE_TRAMITE_EXPED gte
		ON gdet.DETEXPTRAM_TRAMEXP_ID = gte.TRAM_EXP_ID
	LEFT JOIN GESTOR.GE_TIPO_TRAMITE gtt 
		ON gte.TRAM_EXP_TIP_TRA_ID = gtt.TIP_TRA_ID
	WHERE gtt.T_CODIGO = 'TRDPD' OR
		gtt.T_CODIGO = 'SUB' OR
		gtt.T_CODIGO = 'REQINF' OR
		gtt.T_CODIGO = 'PETINFRTE' OR
		gtt.T_CODIGO = 'PETINFTER' OR
		gtt.T_CODIGO = 'REQCUMPL' OR
		gtt.T_CODIGO = 'RREQCUMPL' OR
		gtt.T_CODIGO = 'TRREC' OR
		gtt.T_CODIGO = 'RREQINF'
) t
SET t.L_ESPERA_DOC=1;



SPOOL OFF;
