rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/002_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.2.0 --
-------------------

DROP TABLE GE_TIPOS_AGRUPACIONES CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOS_AGRUPACIONES_H CASCADE CONSTRAINTS;

ALTER TABLE GE_COMUNICACIONES_H DROP COLUMN N_VERSION;
ALTER TABLE GE_LOCALIDADES_H DROP COLUMN N_VERSION;
ALTER TABLE GE_MATERIAS_H DROP COLUMN N_VERSION;
ALTER TABLE GE_MOTIVOSRELACION_H DROP COLUMN N_VERSION;
ALTER TABLE GE_PARAMETROS_H DROP COLUMN N_VERSION;
ALTER TABLE GE_PERSONAS_H DROP COLUMN N_VERSION;
ALTER TABLE GE_PERSONASCOMUNICACIONES_H DROP COLUMN N_VERSION;
ALTER TABLE GE_PROVINCIAS_H DROP COLUMN N_VERSION;
ALTER TABLE GE_SEXO_H DROP COLUMN N_VERSION;
ALTER TABLE GE_TIPOEXPEDIENTES_H DROP COLUMN N_VERSION;
ALTER TABLE GE_TIPOSPERSONAS_H DROP COLUMN N_VERSION;
ALTER TABLE GE_REVAUD ADD NUM_VERSION number(19,0);

DROP TABLE GE_SUJETOS_OBLIGADOS CASCADE CONSTRAINTS;
DROP TABLE GE_SUJETOS_OBLIGADOS_H CASCADE CONSTRAINTS;

SPOOL OFF;
