rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/002_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-- SE MODIFICAN LAS DESCRIPCIONES DE LAS TABLAS A MODO FRASE Y SE MODIFICA EL VALOR DE VERSION
-- SEXO 
UPDATE GE_SEXO SET D_DESCRIPCION = 'MUJER', N_VERSION = 1 WHERE D_DESCRIPCION = 'Mujer';
UPDATE GE_SEXO SET D_DESCRIPCION = 'HOMBRE', N_VERSION = 1 WHERE D_DESCRIPCION = 'Hombre';
-- TIPOS EXPEDIENTES
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'RECLAMACIÓN EN MATERIA DE DERECHO DE ACCESO A LA INFORMACIÓN PÚBLICA.' WHERE D_DESCRIPCION = 'Reclamación en materia de derecho de acceso a la información pública.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'DENUNCIA POR INCUMPLIMIENTO DE LAS EXIGENCIAS DE PUBLICIDAD L_ACTIVA.' WHERE D_DESCRIPCION = 'Denuncia por incumplimiento de las exigencias de publicidad l_activa.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'RECLAMACIÓN POR INFRACCIÓN DE LA NORMATIVA DE PROTECCIÓN DE DATOS.' WHERE D_DESCRIPCION = 'Reclamación por infracción de la normativa de protección de datos.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'NOTIFICACIÓN DE UNA VIOLACIÓN DE LA SEGURIDAD DE LOS DATOS PERSONALES A LA AUTORIDAD DE CONTROL.' WHERE D_DESCRIPCION = 'Notificación de una violación de la seguridad de los datos personales a la autoridad de control.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'COMUNICACIÓN A LA AUTORIDAD DE CONTROL DE LA DESIGNACIÓN, CESE O MODIFICACIÓN DE DATOS DEL DELEGADO DE PROTECCIÓN DE DATOS (DPD).' WHERE D_DESCRIPCION = 'Comunicación a la autoridad de control de la designación, cese o modificación de datos del delegado de protección de datos (dpd).';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'SOLICITUD DE INFORMACIÓN PÚBLICA DEL CONSEJO.' WHERE D_DESCRIPCION = 'Solicitud de información pública del consejo.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'EJERCICIO DE LOS DERECHOS RELATIVOS A LA PROTECCIÓN DE LAS PERSONAS FÍSICAS EN LO QUE RESPECTA AL TRATAMIENTO DE LOS DATOS PERSONALES REALIZADOS POR EL CONSEJO.' WHERE D_DESCRIPCION = 'Ejercicio de los derechos relativos a la protección de las personas físicas en lo que respecta al tratamiento de los datos personales realizados por el consejo.';
-- PERSONAS 
UPDATE GE_TIPOSPERSONAS SET D_DESCRIPCION = 'FÍSICA', N_VERSION = 1 WHERE D_DESCRIPCION = 'Física';
UPDATE GE_TIPOSPERSONAS SET D_DESCRIPCION = 'JURÍDICA', N_VERSION = 1 WHERE D_DESCRIPCION = 'Jurídica';

-- SE ACTUALIZA EL N_VERSION PARA QUE COMIENCE EL VERSIONADO CON EL VALOR UNO
UPDATE GE_COMUNICACIONES SET N_VERSION = 1 WHERE D_DESCRIPCION = 'NOTIFIC@';
UPDATE GE_COMUNICACIONES SET N_VERSION = 1 WHERE D_DESCRIPCION = 'POSTAL';
UPDATE GE_COMUNICACIONES SET N_VERSION = 1 WHERE D_DESCRIPCION = 'PENDIENTE DETERMINAR';

SPOOL OFF;











