rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_UNDO_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.5.0 --
-------------------

CREATE SEQUENCE S_COMUNICACIONES START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_MATERIA START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_MOTIVOSRELACION START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_SEXO START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_TIPOEXPEDIENTE START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_TIPOSPERSONAS START WITH 1 INCREMENT BY  1;

DROP SEQUENCE S_PERSONAS_REPRESENTANTES;

DROP SEQUENCE S_ARTICULOS_AFECTADOS_EXPDT;
DROP SEQUENCE S_DERECHOS_RECLAMADOS_EXPDT;

DROP SEQUENCE S_USUARIOS;
DROP SEQUENCE S_USUARIOS_PERFILES;
DROP SEQUENCE S_PERFILES;
DROP SEQUENCE S_PERMISOS;
DROP SEQUENCE S_PERMISOS_PERFILES;

SPOOL OFF;
