rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_UNDO_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.5.0 --
-------------------

ALTER TABLE GE_COMUNICACIONES_H ADD CONSTRAINT GE_COMUNICACIONES_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_MATERIAS ADD CONSTRAINT GE_MATERIA_TIPOEXPEDIENTES_FK FOREIGN KEY (MAT_TIP_ID) REFERENCES GE_TIPOEXPEDIENTES;
ALTER TABLE GE_MATERIAS_H ADD CONSTRAINT GE_MATERIAS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_MOTIVOSRELACION_H ADD CONSTRAINT GE_MOTIVOSRELACION_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_SEXO_H ADD CONSTRAINT GE_SEXO_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_TIPOEXPEDIENTES_H ADD CONSTRAINT GE_TIPOEXPEDIENTES_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_TIPOSPERSONAS_H ADD CONSTRAINT GE_TIPOSPERSONAS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_SERIES MODIFY (SER_ELESER_ID NOT NULL ENABLE);
ALTER TABLE GE_SERIES ADD CONSTRAINT GE_SER_ELESER_FK FOREIGN KEY (SER_ELESER_ID) REFERENCES GE_ELEMENTOS_SERIES;

SPOOL OFF;
