rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'AUT_COMP');
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_ADM');
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'ARTICULO');
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'DER_RECL');
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'AUT_COMP';
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_ADM';
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'ARTICULO';
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'DER_RECL';

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador');
DELETE FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador';

UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 0 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de expedientes');
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 0 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de expedientes');


-- GE_COMUNICACIONES
INSERT INTO GE_COMUNICACIONES (COM_ID, F_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_COMUNICACIONES.NEXTVAL, SYSDATE, 'NOTIF', 'NOTIFIC@', 0);
INSERT INTO GE_COMUNICACIONES (COM_ID, F_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_COMUNICACIONES.NEXTVAL, SYSDATE, 'POS', 'POSTAL', 0);
INSERT INTO GE_COMUNICACIONES (COM_ID, F_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_COMUNICACIONES.NEXTVAL, SYSDATE, 'PDTE', 'PENDIENTE DETERMINAR', 0);
-- GE_SEXO
INSERT INTO GE_SEXO (SEX_ID, F_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_SEXO.NEXTVAL, SYSDATE, 'M', 'Mujer', 1);
INSERT INTO GE_SEXO (SEX_ID, F_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_SEXO.NEXTVAL, SYSDATE, 'H', 'Hombre', 1);
-- GE_TIPOSPERSONAS
INSERT INTO GE_TIPOSPERSONAS (TIPPER_ID, F_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_TIPOSPERSONAS.NEXTVAL, SYSDATE, 'FIS', 'Física', 1);
INSERT INTO GE_TIPOSPERSONAS (TIPPER_ID, F_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_TIPOSPERSONAS.NEXTVAL, SYSDATE, 'JUR', 'Jurídica', 1);

--GE_TIPOEXPEDIENTES
INSERT INTO GE_TIPOEXPEDIENTES (TIP_ID, C_CODIGO,D_DESCRIPCION,N_VERSION,L_ACTIVA) VALUES (S_TIPOEXPEDIENTE.NEXTVAL,'T_RCL_DER','RECLAMACIÓN EN MATERIA DE DERECHO DE ACCESO A LA INFORMACIÓN PÚBLICA.','0','1');
INSERT INTO GE_TIPOEXPEDIENTES (TIP_ID, C_CODIGO,D_DESCRIPCION,N_VERSION,L_ACTIVA) VALUES (S_TIPOEXPEDIENTE.NEXTVAL,'T_DEN_PUB','DENUNCIA POR INCUMPLIMIENTO DE LAS EXIGENCIAS DE PUBLICIDAD L_ACTIVA.','0','1');
INSERT INTO GE_TIPOEXPEDIENTES (TIP_ID, C_CODIGO,D_DESCRIPCION,N_VERSION,L_ACTIVA) VALUES (S_TIPOEXPEDIENTE.NEXTVAL,'PD_RCL_INF','RECLAMACIÓN POR INFRACCIÓN DE LA NORMATIVA DE PROTECCIÓN DE DATOS.','0','1');
INSERT INTO GE_TIPOEXPEDIENTES (TIP_ID, C_CODIGO,D_DESCRIPCION,N_VERSION,L_ACTIVA) VALUES (S_TIPOEXPEDIENTE.NEXTVAL,'PD_NOT_SEG','NOTIFICACIÓN DE UNA VIOLACIÓN DE LA SEGURIDAD DE LOS DATOS PERSONALES A LA AUTORIDAD DE CONTROL.','0','1');
INSERT INTO GE_TIPOEXPEDIENTES (TIP_ID, C_CODIGO,D_DESCRIPCION,N_VERSION,L_ACTIVA) VALUES (S_TIPOEXPEDIENTE.NEXTVAL,'PD_COM_DEL','COMUNICACIÓN A LA AUTORIDAD DE CONTROL DE LA DESIGNACIÓN, CESE O MODIFICACIÓN DE DATOS DEL DELEGADO DE PROTECCIÓN DE DATOS (DPD).','0','1');
INSERT INTO GE_TIPOEXPEDIENTES (TIP_ID, C_CODIGO,D_DESCRIPCION,N_VERSION,L_ACTIVA) VALUES (S_TIPOEXPEDIENTE.NEXTVAL,'SG_SOL_INF','SOLICITUD DE INFORMACIÓN PÚBLICA DEL CONSEJO.','0','1');
INSERT INTO GE_TIPOEXPEDIENTES (TIP_ID, C_CODIGO,D_DESCRIPCION,N_VERSION,L_ACTIVA) VALUES (S_TIPOEXPEDIENTE.NEXTVAL,'SG_EJE_DER','EJERCICIO DE LOS DERECHOS RELATIVOS A LA PROTECCIÓN DE LAS PERSONAS FÍSICAS EN LO QUE RESPECTA AL TRATAMIENTO DE LOS DATOS PERSONALES REALIZADOS POR EL CONSEJO.','0','1');

-- TIPOS EXPEDIENTES
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Reclamación en materia de derecho de acceso a la información pública.' WHERE D_DESCRIPCION = 'RECLAMACIÓN EN MATERIA DE DERECHO DE ACCESO A LA INFORMACIÓN PÚBLICA.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Denuncia por incumplimiento de las exigencias de publicidad l_activa.' WHERE D_DESCRIPCION = 'DENUNCIA POR INCUMPLIMIENTO DE LAS EXIGENCIAS DE PUBLICIDAD L_ACTIVA.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Reclamación por infracción de la normativa de protección de datos.' WHERE D_DESCRIPCION = 'RECLAMACIÓN POR INFRACCIÓN DE LA NORMATIVA DE PROTECCIÓN DE DATOS.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Notificación de una violación de la seguridad de los datos personales a la autoridad de control.' WHERE D_DESCRIPCION = 'NOTIFICACIÓN DE UNA VIOLACIÓN DE LA SEGURIDAD DE LOS DATOS PERSONALES A LA AUTORIDAD DE CONTROL.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Comunicación a la autoridad de control de la designación, cese o modificación de datos del delegado de protección de datos (dpd).' WHERE D_DESCRIPCION = 'COMUNICACIÓN A LA AUTORIDAD DE CONTROL DE LA DESIGNACIÓN, CESE O MODIFICACIÓN DE DATOS DEL DELEGADO DE PROTECCIÓN DE DATOS (DPD).';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Solicitud de información pública del consejo.' WHERE D_DESCRIPCION = 'SOLICITUD DE INFORMACIÓN PÚBLICA DEL CONSEJO.';
UPDATE GE_TIPOEXPEDIENTES SET D_DESCRIPCION = 'Ejercicio de los derechos relativos a la protección de las personas físicas en lo que respecta al tratamiento de los datos personales realizados por el consejo.' WHERE D_DESCRIPCION = 'EJERCICIO DE LOS DERECHOS RELATIVOS A LA PROTECCIÓN DE LAS PERSONAS FÍSICAS EN LO QUE RESPECTA AL TRATAMIENTO DE LOS DATOS PERSONALES REALIZADOS POR EL CONSEJO.';



-- PAISES
DELETE FROM GE_PAISES;
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'FR', 'Francia');
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ES', 'España');
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IT', 'Italia');

--Actualizar para los bloqueos de los Valores de Dominio
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 0 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'FIS') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de personas');
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 0 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'JUR') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de personas');




SPOOL OFF;
