rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/013_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.13.0 --
--------------------



ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN F_FECHA_TRAMITE;
ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN D_INF_RELEVANTE;
ALTER TABLE GE_TRAMITE_EXPED_H DROP COLUMN F_FECHA_TRAMITE;
ALTER TABLE GE_TRAMITE_EXPED_H DROP COLUMN D_INF_RELEVANTE;

-- --------------------------------------


ALTER TABLE GE_CFG_TAREAS DROP (
	L_TAREA_MANUAL,
	L_AVISO,
	L_BLOQUEO_DISTINTO_RESP,
	L_BLOQUEO_MISMO_RESP,
	L_INFORME_CAMBIO_RESP,
	L_MODIF_DESCRIPCION,
	L_FINAL_ALTA_TRAM,
	L_FINAL_ALTA_TAREA,
 	
	CFGTAR_VALDOM_TIP_TAR_CAMB_ID ,
	CFGTAR_RESP_TAREA_VUELTA_ID
	);
	
ALTER TABLE GE_CFG_TAREAS_H DROP (
	L_TAREA_MANUAL,
	L_AVISO,
	L_BLOQUEO_DISTINTO_RESP,
	L_BLOQUEO_MISMO_RESP,
	L_INFORME_CAMBIO_RESP,
	L_MODIF_DESCRIPCION,
	L_FINAL_ALTA_TRAM,
	L_FINAL_ALTA_TAREA,
	
	CFGTAR_VALDOM_TIP_TAR_CAMB_ID ,
	CFGTAR_RESP_TAREA_VUELTA_ID
	);

ALTER TABLE GE_TAREAS_EXPEDIENTE DROP (
	L_AVISO,
	L_BLOQUEO_DISTINTO_RESP,
	L_BLOQUEO_MISMO_RESP
	);

ALTER TABLE GE_TAREAS_EXPEDIENTE_H DROP (
	L_AVISO,
	L_BLOQUEO_DISTINTO_RESP,
	L_BLOQUEO_MISMO_RESP
	);

-- -----------------

ALTER TABLE GE_TIPO_TRAMITE DROP COLUMN T_INSTRUCCIONES;
ALTER TABLE GE_TIPO_TRAMITE DROP COLUMN L_MODIF_DESCRIPCION;
ALTER TABLE GE_TIPO_TRAMITE DROP COLUMN C_COLOR_SUB_TRAMITE;
ALTER TABLE GE_TIPO_TRAMITE DROP COLUMN C_COLOR_TRAMITE;
ALTER TABLE GE_TIPO_TRAMITE DROP COLUMN L_TIPO_INTERESADO_BLOQUEADO;
ALTER TABLE GE_TIPO_TRAMITE DROP COLUMN TIPTRA_VALDOM_TIPINT_ID;

ALTER TABLE GE_TIPO_TRAMITE_H DROP COLUMN T_INSTRUCCIONES;
ALTER TABLE GE_TIPO_TRAMITE_H DROP COLUMN L_MODIF_DESCRIPCION;
ALTER TABLE GE_TIPO_TRAMITE_H DROP COLUMN C_COLOR_SUB_TRAMITE;
ALTER TABLE GE_TIPO_TRAMITE_H DROP COLUMN C_COLOR_TRAMITE;
ALTER TABLE GE_TIPO_TRAMITE_H DROP COLUMN L_TIPO_INTERESADO_BLOQUEADO;
ALTER TABLE GE_TIPO_TRAMITE_H DROP COLUMN TIPTRA_VALDOM_TIPINT_ID;

-- ------------------

ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN D_SIT_ADICIONAL;
ALTER TABLE GE_TRAMITE_EXPED_H DROP COLUMN D_SIT_ADICIONAL;

ALTER TABLE GE_EXPEDIENTES DROP COLUMN D_SIT_ADICIONAL;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN D_SIT_ADICIONAL;

-- ------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM   DROP (T_EXTRACTO , L_EXTRACTO_EXPDTE , T_ANTECEDENTES , L_ANTEC_EXPDTE);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP (T_EXTRACTO , L_EXTRACTO_EXPDTE , T_ANTECEDENTES , L_ANTEC_EXPDTE);

ALTER TABLE GE_CFG_METADATOS_TRAM   DROP (D_EXTRACTO, D_EXTRACTO_EXPDTE, D_ANTECEDENTES, D_ANTEC_EXPDTE);
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP (D_EXTRACTO, D_EXTRACTO_EXPDTE, D_ANTECEDENTES, D_ANTEC_EXPDTE);

-- -----------------

ALTER TABLE GE_EXPEDIENTES DROP COLUMN EXP_USR_MOD_MOTIVO;
ALTER TABLE GE_EXPEDIENTES DROP COLUMN F_FECHA_HORA_MOD_MOTIVO;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN EXP_USR_MOD_MOTIVO;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN F_FECHA_HORA_MOD_MOTIVO;

--------------------------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN D_NUMERO_PSAN;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN D_NUMERO_PSAN;

ALTER TABLE GE_CFG_METADATOS_TRAM DROP COLUMN D_NUMERO_PSAN;
ALTER TABLE GE_CFG_METADATOS_TRAM DROP COLUMN D_BT_GENERAR_EXP;
ALTER TABLE GE_CFG_METADATOS_TRAM DROP COLUMN D_BT_VINCULAR_EXP;
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP COLUMN D_NUMERO_PSAN;
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP COLUMN D_BT_GENERAR_EXP;
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP COLUMN D_BT_VINCULAR_EXP;



SPOOL OFF;
