rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/012_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.12.0 --
--------------------

ALTER TABLE GE_RESOL_SUJOBL ADD (RESSUJOBL_EXP_ID NUMBER(19,0));
ALTER TABLE GE_RESOL_SUJOBL_H ADD (RESSUJOBL_EXP_ID NUMBER(19,0));

ALTER TABLE GE_RESOL_PERSONA ADD (RESPER_EXP_ID NUMBER(19,0));
ALTER TABLE GE_RESOL_PERSONA_H ADD (RESPER_EXP_ID NUMBER(19,0));

ALTER TABLE GE_RESOL_EXPEDIENTES ADD (RESEXP_VALDOMSENRES_ID NUMBER(19,0));
ALTER TABLE GE_RESOL_EXPEDIENTES_H ADD (RESEXP_VALDOMSENRES_ID NUMBER(19,0));

CREATE TABLE GE_CFG_TIPOEXPEDIENTE (
CFG_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), N_VERSION NUMBER(19,0), 
CFG_VALDOM_TIP_EXP_ID NUMBER(19, 0),
CFG_VALDOM_TIP_AREA_CTPDA_ID NUMBER(19, 0),
CFG_TIP_TRA_SEG_1_ID NUMBER(19, 0),
CFG_TIP_TRA_SEG_2_ID NUMBER(19, 0),
CFG_TIP_TRA_SEG_3_ID NUMBER(19, 0)
) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_CFG_TIPOEXPEDIENTE_H (
CFG_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), 
CFG_VALDOM_TIP_EXP_ID NUMBER(19, 0),
CFG_VALDOM_TIP_AREA_CTPDA_ID NUMBER(19, 0),
CFG_TIP_TRA_SEG_1_ID NUMBER(19, 0),
CFG_TIP_TRA_SEG_2_ID NUMBER(19, 0),
CFG_TIP_TRA_SEG_3_ID NUMBER(19, 0)
) TABLESPACE GESTOR_DAT;

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD D_SEGUIMIENTO_CABECERA VARCHAR(50);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD D_SEGUIMIENTO_CABECERA VARCHAR(50);

ALTER TABLE GE_CFG_EXPED_TRAMITE ADD CFGEXPTR_RESP_ID_DEFECTO NUMBER(19,0);
ALTER TABLE GE_CFG_EXPED_SUBTRAM ADD CFGEXPST_RESP_ID_DEFECTO NUMBER(19,0);
ALTER TABLE GE_CFG_EXPED_TRAMITE_H ADD CFGEXPTR_RESP_ID_DEFECTO NUMBER(19,0);
ALTER TABLE GE_CFG_EXPED_SUBTRAM_H ADD CFGEXPST_RESP_ID_DEFECTO NUMBER(19,0);

ALTER TABLE GE_CFG_EXPED_SUBTRAM ADD CFGEXPST_L_RESP_TRAM NUMBER(1,0);
ALTER TABLE GE_CFG_EXPED_SUBTRAM_H ADD CFGEXPST_L_RESP_TRAM NUMBER(1,0);

ALTER TABLE GE_EXPEDIENTES MODIFY (T_NOMBRE_EXPEDIENTE NULL);

-- ----------------------------------------

ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES ADD (DOCRES_DOCEXP_ID NUMBER(19,0));
ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES_H ADD (DOCRES_DOCEXP_ID NUMBER(19,0));

ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES DROP (DOCRES_DOC_ID);
ALTER TABLE GE_DOCUMENTOS_RESOLUCIONES_H DROP (DOCRES_DOC_ID);

-- ----------------------------------------

ALTER TABLE GE_ACCESOS_DOCS ADD (L_RESOLUCION NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE GE_ACCESOS_DOCS_H ADD (L_RESOLUCION NUMBER(1,0));

-- --------------------------------------------------

CREATE TABLE GE_CFG_AUTO_SITUACION (
	AUS_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0), 
	F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), 
	AUS_VALDOM_TIP_EXP_ID NUMBER(19,0) NOT NULL,
	AUS_TIP_TRA_ID NUMBER(19,0) NOT NULL,
	AUS_VALDOM_SIT_ORI_ID NUMBER(19,0) NOT NULL,
	T_CONDICION VARCHAR2(50 CHAR),
	AUS_VALDOM_SIT_DEST_ID NUMBER(19,0) NOT NULL
);

CREATE TABLE GE_CFG_AUTO_SITUACION_H (
	AUS_ID NUMBER(19,0), N_VERSION NUMBER(19,0), 
	REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0),
	AUS_VALDOM_TIP_EXP_ID NUMBER(19,0),
	AUS_TIP_TRA_ID NUMBER(19,0),
	AUS_VALDOM_SIT_ORI_ID NUMBER(19,0),
	T_CONDICION VARCHAR2(50 CHAR),
	AUS_VALDOM_SIT_DEST_ID NUMBER(19,0)
);

-- ---------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (DETEXTRAM_VALDOMMOTINAD_ID NUMBER(19,0));
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (DETEXTRAM_VALDOMMOTINAD_ID NUMBER(19,0));

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_MOTIVO_INADMISION VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_MOTIVO_INADMISION VARCHAR2(50 CHAR));

ALTER TABLE GE_EXPEDIENTES ADD (EXP_VALDOM_MOTINADM_ID NUMBER(19,0));
ALTER TABLE GE_EXPEDIENTES_H ADD (EXP_VALDOM_MOTINADM_ID NUMBER(19,0));

-- ---------------------

CREATE TABLE GE_CFG_DOC_EXPED_DESC (
	CFGDE_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0), 
	F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), 
	CFGDE_DOC_ID NUMBER(19,0) NOT NULL,
	N_ORDEN NUMBER(19,0) DEFAULT 0 NOT NULL,
	D_DESCRIPCION VARCHAR2(255 CHAR),
	D_DESC_ABREV VARCHAR2(50 CHAR),
	
	L_TRABAJO      NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_EDITABLE     NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_ANONIMIZADO  NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_ANON_PARCIAL NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_FIRMADO      NUMBER(1,0) DEFAULT 0 NOT NULL,
	L_SELLADO      NUMBER(1,0) DEFAULT 0 NOT NULL
);

CREATE TABLE GE_CFG_DOC_EXPED_DESC_H (
	CFGDE_ID NUMBER(19,0), N_VERSION NUMBER(19,0), 
	REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0),
	CFGDE_DOC_ID NUMBER(19,0),
	N_ORDEN NUMBER(19,0),
	D_DESCRIPCION VARCHAR2(255 CHAR),
	D_DESC_ABREV VARCHAR2(50 CHAR),
	
	L_TRABAJO      NUMBER(1,0),
	L_EDITABLE     NUMBER(1,0),
	L_ANONIMIZADO  NUMBER(1,0),
	L_ANON_PARCIAL NUMBER(1,0),
	L_FIRMADO      NUMBER(1,0),
	L_SELLADO      NUMBER(1,0)
);

-- ---------------------------------

ALTER TABLE GE_CFG_AUTO_SITUACION   ADD (L_OPERACION VARCHAR2(1 CHAR) DEFAULT 'F' NOT NULL);
ALTER TABLE GE_CFG_AUTO_SITUACION_H ADD (L_OPERACION VARCHAR2(1 CHAR) DEFAULT 'F');

---------------------------------------

COMMENT ON TABLE GE_DATOS_TMP_USUARIO IS 'Tabla de uso temporal en el onlyOffice para almacenar temporalmente los datos del usuario a pintar';

ALTER TABLE GE_ACCESOS_DOCS_H MODIFY ( ACD_ID NOT NULL); 
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (L_ERRONEO NULL);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (L_DPD NULL);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (L_UNIDAD_TRANSPARENCIA NULL);

----------------------------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD (CFG_VALDOM_SERIERESOL_ID NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD (CFG_VALDOM_SERIERESOL_ID NUMBER(19,0));

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD (CFG_VALDOM_TIPORESOL_ID NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD (CFG_VALDOM_TIPORESOL_ID NUMBER(19,0));

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (L_IMPOSICION_MEDIDAS NUMBER(1,0) DEFAULT 0);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (L_IMPOSICION_MEDIDAS NUMBER(1,0) DEFAULT 0);

-----------------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD (CFG_VALDOM_MOTRELPER_ID NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD (CFG_VALDOM_MOTRELSUJ_ID NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD (CFG_VALDOM_MOTRELPER_ID NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD (CFG_VALDOM_MOTRELSUJ_ID NUMBER(19,0));

---------------------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (DETEXPTRAM_VALDOM_PROPAPI_ID NUMBER(19,0));
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (DETEXPTRAM_VALDOM_PROPAPI_ID NUMBER(19,0));

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_PROPUESTA_API VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_PROPUESTA_API VARCHAR2(50 CHAR));

SPOOL OFF;
