rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/012_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.12.0 --
-------------------


CREATE SEQUENCE S_CFG_TIPOEXPEDIENTE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE S_CFG_AUTO_SITUACION START WITH 1 INCREMENT BY  1;

CREATE SEQUENCE S_CFG_DOC_EXPED_DESC START WITH 1 INCREMENT BY 1;



SPOOL OFF;

