rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/012_03_INDICES.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.12.0 --
-------------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE    ADD CONSTRAINT GE_CFG_TIPOEXPEDIENTE_PK   PRIMARY KEY (CFG_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H  ADD CONSTRAINT GE_CFG_TIPOEXPEDIENTE_H_PK PRIMARY KEY (CFG_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_CFG_AUTO_SITUACION   ADD CONSTRAINT GE_AUTO_SITUACION_PK   PRIMARY KEY (AUS_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_CFG_AUTO_SITUACION_H ADD CONSTRAINT GE_AUTO_SITUACION_H_PK PRIMARY KEY (AUS_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_CFG_DOC_EXPED_DESC   ADD CONSTRAINT GE_CFG_DOC_EXPED_DESC_PK   PRIMARY KEY (CFGDE_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_CFG_DOC_EXPED_DESC_H ADD CONSTRAINT GE_CFG_DOC_EXPED_DESC_H_PK PRIMARY KEY (CFGDE_ID, REV) USING INDEX TABLESPACE GESTOR_IND;



SPOOL OFF;
