rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/004_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

CREATE TABLE GE_ELEMENTOS_SERIES ( ELEM_SER_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, N_VERSION NUMBER(19,0), USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), T_TIPO VARCHAR2(10 CHAR) NOT NULL, T_DESCRIPCION VARCHAR2(100 CHAR), T_CODIGO_SERIE VARCHAR2(25 CHAR) NOT NULL, F_FECHA_INICIAL DATE NOT NULL, F_FECHA_FINAL DATE) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_ELEMENTOS_SERIES_H ( ELEM_SER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), T_TIPO VARCHAR2(10 CHAR), T_DESCRIPCION VARCHAR2(100 CHAR), T_CODIGO_SERIE VARCHAR2(25 CHAR), F_FECHA_INICIAL DATE, F_FECHA_FINAL DATE) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_SERIES ( SER_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, N_VERSION NUMBER(19,0), USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), SER_ELESER_ID NUMBER(19,0) NOT NULL, F_FECHA_INICIAL DATE NOT NULL, F_FECHA_FINAL DATE NOT NULL, N_NUMERO_INICIAL NUMBER(19,0) NOT NULL, N_NUMERO_FINAL NUMBER(19,0) NOT NULL, T_PATRON VARCHAR2(100 CHAR) NOT NULL, N_MARGEN_AVISO NUMBER(19,0), N_INCREMENTO NUMBER(5,0) DEFAULT 1 NOT NULL, N_ULTIMO_NUMERO NUMBER(19,0) NOT NULL, F_ULTIMA_FECHA DATE DEFAULT TO_DATE('01/01/2016', 'DD/MM/YYYY') NOT NULL, L_SECUENCIA_FECHA NUMBER(1,0) DEFAULT 0 NOT NULL) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_SERIES_H ( SER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), SER_ELESER_ID NUMBER(19,0) NOT NULL, F_FECHA_INICIAL DATE, F_FECHA_FINAL DATE, N_NUMERO_INICIAL NUMBER(19,0), N_NUMERO_FINAL NUMBER(19,0), T_PATRON VARCHAR2(100 CHAR), N_MARGEN_AVISO NUMBER(19,0), N_INCREMENTO NUMBER(5,0), N_ULTIMO_NUMERO NUMBER(19,0), F_ULTIMA_FECHA DATE, L_SECUENCIA_FECHA NUMBER(1,0)) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_EXPEDIENTES_RELACIONADOS (EXR_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), N_VERSION NUMBER(19,0), EXR_VALDOM_MOT_ID NUMBER(19,0) NOT NULL, EXR_EXPRELAC_ID NUMBER(19,0) NOT NULL, EXR_EXPORIGEN_ID NUMBER(19,0) NOT NULL) TABLESPACE GESTOR_DAT; 
CREATE TABLE GE_EXPEDIENTES_RELACIONADOS_H (EXR_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), EXR_VALDOM_MOT_ID NUMBER(19,0), EXR_EXPRELAC_ID NUMBER(19,0), EXR_EXPORIGEN_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT; 

ALTER TABLE GE_VALORES_DOMINIOS DROP COLUMN N_ORDEN;
ALTER TABLE GE_VALORES_DOMINIOS DROP COLUMN N_NIVEL_ANIDAMIENTO;
ALTER TABLE GE_VALORES_DOMINIOS ADD N_ORDEN NUMBER(3);
ALTER TABLE GE_VALORES_DOMINIOS ADD N_NIVEL_ANIDAMIENTO NUMBER(3);

ALTER TABLE GE_PERSONAS   DROP COLUMN PER_TIPPER_ID;
ALTER TABLE GE_PERSONAS_H DROP COLUMN PER_TIPPER_ID;
ALTER TABLE GE_PERSONAS   ADD (N_TELEFONO_MOVIL NUMBER(19,0), PER_VALDOM_VIACOM_ID NUMBER(19,0));
ALTER TABLE GE_PERSONAS_H ADD (N_TELEFONO_MOVIL NUMBER(19,0), PER_VALDOM_VIACOM_ID NUMBER(19,0));
ALTER TABLE GE_PERSONAS   RENAME COLUMN N_TELEFONO TO N_TELEFONO_FIJO;
ALTER TABLE GE_PERSONAS_H RENAME COLUMN N_TELEFONO TO N_TELEFONO_FIJO;

CREATE TABLE GE_PAISES (PAI_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0), F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), C_CODIGO VARCHAR2(2 CHAR), D_DESCRIPCION VARCHAR2(255 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1) ;
CREATE TABLE GE_PAISES_H (PAI_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), C_CODIGO VARCHAR2(2 CHAR), D_DESCRIPCION VARCHAR2(255 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1) ;

ALTER TABLE GE_PERSONAS   ADD (PER_PAI_ID NUMBER(19,0), D_DESCRIPCION_MUNICIPIO VARCHAR2(100 CHAR)); 
ALTER TABLE GE_PERSONAS_H ADD (PER_PAI_ID NUMBER(19,0), D_DESCRIPCION_MUNICIPIO VARCHAR2(100 CHAR));

ALTER TABLE GE_SUJETOS_OBLIGADOS   ADD (SUJ_PAI_ID NUMBER(19,0), D_DESCRIPCION_MUNICIPIO VARCHAR2(100 CHAR));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (SUJ_PAI_ID NUMBER(19,0), D_DESCRIPCION_MUNICIPIO VARCHAR2(100 CHAR));

ALTER TABLE GE_PERSONAS   ADD C_CODIGO_POSTAL VARCHAR(5);
ALTER TABLE GE_PERSONAS_H ADD C_CODIGO_POSTAL VARCHAR(5);
ALTER TABLE GE_PERSONAS   DROP COLUMN N_CODIGO_POSTAL;
ALTER TABLE GE_PERSONAS_H DROP COLUMN N_CODIGO_POSTAL;

ALTER TABLE GE_SUJETOS_OBLIGADOS   ADD (SUJ_LOC_ID NUMBER(19,0));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (SUJ_LOC_ID NUMBER(19,0));
ALTER TABLE GE_SUJETOS_OBLIGADOS   DROP (T_LOCALIDAD);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP (T_LOCALIDAD);

CREATE TABLE GE_OBSERVACIONES_EXPEDIENTES ( OBS_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), N_VERSION NUMBER(19,0), OBS_EXP_ID NUMBER(19,0) NOT NULL, OBS_VALDOM_TIPOBS_ID NUMBER(19,0) NOT NULL, F_ENTRADA TIMESTAMP NOT NULL, T_TEXTO VARCHAR2(500 CHAR) NOT NULL ) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_OBSERVACIONES_EXPEDIENTES_H ( OBS_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), OBS_EXP_ID NUMBER(19,0), OBS_VALDOM_TIPOBS_ID NUMBER(19,0), F_ENTRADA TIMESTAMP, T_TEXTO VARCHAR2(500 CHAR) ) TABLESPACE GESTOR_DAT;


SPOOL OFF;