rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/004_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

CREATE SEQUENCE S_ELEMENTOS_SERIES START WITH 1 INCREMENT BY  1;

CREATE SEQUENCE S_SERIES START WITH 1 INCREMENT BY  1;

CREATE SEQUENCE S_EXPEDIENTES_RELACIONADOS START WITH 1 INCREMENT BY  1;

CREATE SEQUENCE S_PAISES START WITH 1 INCREMENT BY  1;

CREATE SEQUENCE S_OBSERVACIONES_EXPEDIENTES START WITH 1 INCREMENT BY  1;

SPOOL OFF;