rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/004_03_INDICES.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_ELEMENTOS_SERIES ADD CONSTRAINT GE_ELEMENTOS_SERIES_PK PRIMARY KEY (ELEM_SER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_ELEMENTOS_SERIES_H ADD CONSTRAINT GE_ELEMENTOS_SERIES_H_PK PRIMARY KEY (ELEM_SER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_SERIES ADD CONSTRAINT GE_SERIES_PK PRIMARY KEY (SER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_SERIES_H ADD CONSTRAINT GE_SERIES_H_PK PRIMARY KEY (SER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_EXPEDIENTES_RELACIONADOS   ADD CONSTRAINT GE_EXPEDIENTES_RELACIONADOS_PK PRIMARY KEY (EXR_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_EXPEDIENTES_RELACIONADOS_H ADD CONSTRAINT GE_EXPEDIENTES_RELAC_H_PK PRIMARY KEY (EXR_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_PAISES   ADD CONSTRAINT GE_PAISES_PK   PRIMARY KEY (PAI_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PAISES_H ADD CONSTRAINT GE_PAISES_H_PK PRIMARY KEY (PAI_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES ADD CONSTRAINT GE_OBSERVACION_EXPEDIENTES_PK PRIMARY KEY (OBS_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES_H ADD CONSTRAINT GE_OBSERVACIO_EXPEDIENTE_H_PK PRIMARY KEY (OBS_ID, REV) USING INDEX TABLESPACE GESTOR_IND;


SPOOL OFF;