rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/004_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_SERIES ADD CONSTRAINT GE_SER_ELESER_FK FOREIGN KEY (SER_ELESER_ID) REFERENCES GE_ELEMENTOS_SERIES;

ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONA_VALDOM_VIACOM_FK FOREIGN KEY (PER_VALDOM_VIACOM_ID) REFERENCES GE_VALORES_DOMINIOS;

ALTER TABLE GE_EXPEDIENTES_RELACIONADOS ADD CONSTRAINT GE_EXR_EXPRELAC_FK FOREIGN KEY (EXR_EXPRELAC_ID) REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_EXPEDIENTES_RELACIONADOS ADD CONSTRAINT GE_EXR_EXPORIGEN_FK FOREIGN KEY (EXR_EXPORIGEN_ID) REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_EXPEDIENTES_RELACIONADOS ADD CONSTRAINT GE_EXR_VALDOM_MOT_FK FOREIGN KEY (EXR_VALDOM_MOT_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_EXPEDIENTES_RELACIONADOS_H ADD CONSTRAINT GE_EXR_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_PAISES MODIFY (C_CODIGO NOT NULL ENABLE);
ALTER TABLE GE_PAISES MODIFY (D_DESCRIPCION NOT NULL ENABLE);
ALTER TABLE GE_PAISES MODIFY (L_ACTIVA NOT NULL ENABLE);

ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONA_PAIS_FK FOREIGN KEY (PER_PAI_ID) REFERENCES GE_PAISES;

ALTER TABLE GE_SUJETOS_OBLIGADOS ADD CONSTRAINT GE_SUJOBLI_PAIS_FK FOREIGN KEY (SUJ_PAI_ID) REFERENCES GE_PAISES;
ALTER TABLE GE_SUJETOS_OBLIGADOS ADD CONSTRAINT GE_SUJOBLI_LOCALIDAD_FK FOREIGN KEY (SUJ_LOC_ID) REFERENCES GE_LOCALIDADES;

ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES ADD CONSTRAINT GE_OBS_EXP_FK FOREIGN KEY (OBS_EXP_ID) REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES ADD CONSTRAINT GE_OBS_VALDOM_TIPOBS_FK FOREIGN KEY (OBS_VALDOM_TIPOBS_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_OBSERVACIONES_EXPEDIENTES_H ADD CONSTRAINT GE_OBS_EXP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;


SPOOL OFF;