rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/004_06_GRANTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


GRANT SELECT, UPDATE, INSERT, DELETE ON GE_ELEMENTOS_SERIES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_ELEMENTOS_SERIES TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_ELEMENTOS_SERIES_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_SERIES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_SERIES TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_SERIES_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_EXPEDIENTES_RELACIONADOS TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_EXPEDIENTES_RELACIONADOS TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_EXPEDIENTES_RELACIONADOS_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PAISES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_PAISES TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PAISES_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_OBSERVACIONES_EXPEDIENTES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_OBSERVACIONES_EXPEDIENTES TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_OBSERVACIONES_EXPEDIENTES_H TO GE_ROL_GESTOR_DML;


SPOOL OFF;