rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/008_03_INDICES.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


ALTER TABLE GE_RESP_TRAMITACION   ADD CONSTRAINT GE_RESP_TRAMITACION_PK   PRIMARY KEY (RESTRA_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_RESP_TRAMITACION_H ADD CONSTRAINT GE_RESP_TRAMITACION_H_PK PRIMARY KEY (RESTRA_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_USUARIO_RESP   ADD CONSTRAINT GE_USUARIO_RESP_PK   PRIMARY KEY (USRES_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_USUARIO_RESP_H ADD CONSTRAINT GE_USUARIO_RESP_H_PK PRIMARY KEY (USRES_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_CFG_TAREAS   ADD CONSTRAINT S_CFG_TAREAS_PK   PRIMARY KEY (CFGTAR_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_CFG_TAREAS_H ADD CONSTRAINT S_CFG_TAREAS_H_PK PRIMARY KEY (CFGTAR_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_TAREAS_EXPEDIENTE   ADD CONSTRAINT GE_TAREAS_EXPEDIENTE_PK   PRIMARY KEY (TAREXP_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TAREAS_EXPEDIENTE_H ADD CONSTRAINT GE_TAREAS_EXPEDIENTE_H_PK PRIMARY KEY (TAREXP_ID, REV) USING INDEX TABLESPACE GESTOR_IND;




SPOOL OFF;
