rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/008_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_RESP_TRAMITACION ADD CONSTRAINT GE_RESP_TRAMITACION_SUP_FK FOREIGN KEY (RESTRA_ID_RESP_SUPERIOR) REFERENCES GE_RESP_TRAMITACION;
ALTER TABLE GE_RESP_TRAMITACION ADD CONSTRAINT GE_RESP_TRAMITACION_CODIGO_UK UNIQUE (T_COD_RESP);

ALTER TABLE GE_USUARIO_RESP ADD CONSTRAINT GE_USUARIO_RESP_USU_FK     FOREIGN KEY (USRRES_USU_ID)     REFERENCES GE_USUARIOS;
ALTER TABLE GE_USUARIO_RESP ADD CONSTRAINT GE_USUARIO_RESP_RESP_TR_FK FOREIGN KEY (USRRES_RESP_TR_ID) REFERENCES GE_RESP_TRAMITACION;

ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT GE_CFG_TAREAS_TIP_EXP_FK      FOREIGN KEY (CFGTAR_VALDOM_TIP_EXP_ID)      REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT GE_CFG_TAREAS_TIP_TRA_FK      FOREIGN KEY (CFGTAR_TIP_TRA_ID)             REFERENCES  GE_TIPO_TRAMITE;
ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT GE_CFG_TAREAS_TIP_SUBTRA_FK   FOREIGN KEY (CFGTAR_TIP_SUBTRA_ID)          REFERENCES  GE_TIPO_TRAMITE;
ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT GE_CFG_TAREAS_TIP_TAR_FK      FOREIGN KEY (CFGTAR_VALDOM_TIP_TAR_ID)      REFERENCES  GE_VALORES_DOMINIOS;
ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT GE_CFG_TAREAS_TIP_TAR_ORIG_FK FOREIGN KEY (CFGTAR_VALDOM_TIP_TAR_ORIG_ID) REFERENCES  GE_VALORES_DOMINIOS;
ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT GE_CFG_TAREAS_RESP_DEFECTO_FK FOREIGN KEY (CFGTAR_RESP_ID_DEFECTO)        REFERENCES GE_RESP_TRAMITACION;

ALTER TABLE GE_TAREAS_EXPEDIENTE ADD CONSTRAINT GE_TAREAS_EXP_EXP_FK          FOREIGN KEY (TAREXP_EXP_ID)        REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_TAREAS_EXPEDIENTE ADD CONSTRAINT GE_TAREAS_EXP_TRA_FK          FOREIGN KEY (TAREXP_TRA_ID)        REFERENCES GE_TRAMITE_EXPED;
ALTER TABLE GE_TAREAS_EXPEDIENTE ADD CONSTRAINT GE_TAREAS_EXP_DOCEXP_TRA_FK   FOREIGN KEY (TAREXP_DOCEXP_TRA_ID) REFERENCES GE_DOCUMENTOS_EXPED_TRAMITES;
ALTER TABLE GE_TAREAS_EXPEDIENTE ADD CONSTRAINT GE_TAREAS_EXP_TAR_FK          FOREIGN KEY (TAREXP_VALDOM_TAR_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_TAREAS_EXPEDIENTE ADD CONSTRAINT GE_TAREAS_EXP_RESP_FK         FOREIGN KEY (TAREXP_RESP_ID)       REFERENCES GE_RESP_TRAMITACION;
ALTER TABLE GE_TAREAS_EXPEDIENTE ADD CONSTRAINT GE_TAREAS_EXP_USU_CREA_FK     FOREIGN KEY (TAREXP_USU_ID_CREA)   REFERENCES GE_USUARIOS;
ALTER TABLE GE_TAREAS_EXPEDIENTE ADD CONSTRAINT GE_TAREAS_EXP_USU_CIERRA_FK   FOREIGN KEY (TAREXP_USU_ID_CIERRA) REFERENCES GE_USUARIOS;


ALTER TABLE GE_PLAZOS_EXPDTE ADD CONSTRAINT GE_PLAEXP_CFGPLAEXP_FK FOREIGN KEY (PLAEXP_CFGPLAEXP_ID) REFERENCES GE_CFG_PLAZOS_EXPDTE;
ALTER TABLE GE_PLAZOS_EXPDTE ADD CONSTRAINT GE_PLAEXP_EXP_FK FOREIGN KEY (PLAEXP_EXP_ID) REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_PLAZOS_EXPDTE_H ADD CONSTRAINT GE_PLAEXP_H_REV_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;


-- RESTRICCIONES UNIQUE PARA PERMISOS Y PERFILES
ALTER TABLE GE_PERMISOS ADD CONSTRAINT GE_PERMISOS_CODIGO_UK UNIQUE (C_CODIGO);
ALTER TABLE GE_PERFILES ADD CONSTRAINT GE_PERFILES_CODIGO_UK UNIQUE (C_CODIGO);

-- ELIMINAMOS ENTRADAS DUPLICADAS EN LA TABLA GE_PERMISOS_PERFILES
DELETE FROM GE_PERMISOS_PERFILES
WHERE ROWID NOT IN
	(SELECT MIN(ROWID) FROM GE_PERMISOS_PERFILES
	GROUP BY PERMPERF_PERF_ID, PERMPERF_PERM_ID);

ALTER TABLE GE_PERMISOS_PERFILES ADD CONSTRAINT GE_PERMISOS_PERFILES_UK UNIQUE (PERMPERF_PERF_ID, PERMPERF_PERM_ID);



SPOOL OFF;
