rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/001_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.1.0 --
-------------------

CREATE SEQUENCE S_COMUNICACIONES START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_LOCALIDADES START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_MATERIA START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_MOTIVOSRELACION START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_PARAMETRO START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_PERSONAS START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_PERSONASCOMUNICACIONES START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_PROVINCIAS START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_REVAUD START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_SEXO START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_TIPOEXPEDIENTE START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_TIPOSPERSONAS START WITH 1 INCREMENT BY  1;

SPOOL OFF;
