rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/001_03_INDICES.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.1.0 --
-------------------

ALTER TABLE GE_COMUNICACIONES ADD CONSTRAINT GE_COMUNICACIONES_PK PRIMARY KEY (COM_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_COMUNICACIONES_H ADD CONSTRAINT GE_COMUNICACIONES_H_PK PRIMARY KEY (COM_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_LOCALIDADES ADD CONSTRAINT GE_LOCALIDADES_PK PRIMARY KEY (LOC_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_LOCALIDADES_H ADD CONSTRAINT GE_LOCALIDADES_H_PK PRIMARY KEY (LOC_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_MATERIAS ADD CONSTRAINT GE_MATERIAS_PK PRIMARY KEY (MAT_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_MATERIAS_H ADD CONSTRAINT GE_MATERIAS_H_PK PRIMARY KEY (MAT_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_MOTIVOSRELACION ADD CONSTRAINT GE_MOTIVOSRELACION_PK  PRIMARY KEY (MOT_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_MOTIVOSRELACION_H ADD CONSTRAINT GE_MOTIVOSRELACION_H_PK PRIMARY KEY (MOT_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PARAMETROS ADD CONSTRAINT GE_PARAMETROS_PK PRIMARY KEY (PAR_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PARAMETROS_H ADD CONSTRAINT GE_PARAMETROS_H_PK PRIMARY KEY (PAR_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONAS_PK PRIMARY KEY (PER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERSONAS_H ADD CONSTRAINT GE_PERSONAS_H_PK PRIMARY KEY (PER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERSONASCOMUNICACIONES ADD CONSTRAINT GE_PERSONASCOMUNICACIONES_PK PRIMARY KEY (PER_VIACOM_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERSONASCOMUNICACIONES_H ADD CONSTRAINT GE_PERSONASCOMUNICACIONES_H_PK PRIMARY KEY (PER_VIACOM_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PROVINCIAS ADD CONSTRAINT GE_PROVINCIAS_PK PRIMARY KEY (PRO_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PROVINCIAS_H ADD CONSTRAINT GE_PROVINCIAS_H_PK PRIMARY KEY (PRO_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_REVAUD ADD CONSTRAINT GE_REVAUD_PK PRIMARY KEY (REV_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_SEXO ADD CONSTRAINT GE_SEXO_PK PRIMARY KEY (SEX_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_SEXO_H ADD CONSTRAINT GE_SEXO_H_PK PRIMARY KEY (SEX_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TIPOEXPEDIENTES ADD CONSTRAINT GE_TIPOEXPEDIENTES_PK PRIMARY KEY (TIP_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TIPOEXPEDIENTES_H ADD CONSTRAINT GE_TIPOEXPEDIENTES_H_PK PRIMARY KEY (TIP_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TIPOSPERSONAS ADD CONSTRAINT GE_TIPOSPERSONAS_PK PRIMARY KEY (TIPPER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TIPOSPERSONAS_H ADD CONSTRAINT GE_TIPOSPERSONAS_H_PK PRIMARY KEY (TIPPER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

SPOOL OFF;
