rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/001_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.1.0 --
-------------------

ALTER TABLE GE_PARAMETROS ADD CONSTRAINT GE_PARAMETROS_UK UNIQUE (T_CAMPO);
ALTER TABLE GE_COMUNICACIONES_H ADD CONSTRAINT GE_COMUNICACIONES_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_LOCALIDADES ADD CONSTRAINT GE_LOCALIDAD_PROVINCIA_FK FOREIGN KEY (LOC_PRO_ID) REFERENCES GE_PROVINCIAS;
ALTER TABLE GE_LOCALIDADES_H ADD CONSTRAINT GE_LOCALIDADES_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_MATERIAS ADD CONSTRAINT GE_MATERIA_TIPOEXPEDIENTES_FK FOREIGN KEY (MAT_TIP_ID) REFERENCES GE_TIPOEXPEDIENTES;
ALTER TABLE GE_MATERIAS_H ADD CONSTRAINT GE_MATERIAS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_MOTIVOSRELACION_H ADD CONSTRAINT GE_MOTIVOSRELACION_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_PARAMETROS_H ADD CONSTRAINT GE_PARAMETROS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONA_LOCALIDAD_FK FOREIGN KEY (PER_LOC_ID) REFERENCES GE_LOCALIDADES;
ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONA_PROVINCIA_FK FOREIGN KEY (PER_PRO_ID) REFERENCES GE_PROVINCIAS;
ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONA_SEXO_FK FOREIGN KEY (PER_SEX_ID) REFERENCES GE_SEXO;
ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONA_TIPOPERSONA_FK FOREIGN KEY (PER_TIPPER_ID) REFERENCES GE_TIPOSPERSONAS;
ALTER TABLE GE_PERSONAS_H ADD CONSTRAINT GE_PERSONAS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_PERSONASCOMUNICACIONES ADD CONSTRAINT GE_PERSONACOMU_COMUNICACION_FK FOREIGN KEY (PERVIA_COM_ID) REFERENCES GE_COMUNICACIONES;
ALTER TABLE GE_PERSONASCOMUNICACIONES ADD CONSTRAINT GE_PERSONACOMUNICAC_PERSONA_FK FOREIGN KEY (PERVIA_PER_ID) REFERENCES GE_PERSONAS;
ALTER TABLE GE_PERSONASCOMUNICACIONES_H ADD CONSTRAINT GE_PERCOMUNICACION_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_PROVINCIAS_H ADD CONSTRAINT GE_PROVINCIAS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_SEXO_H ADD CONSTRAINT GE_SEXO_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_TIPOEXPEDIENTES_H ADD CONSTRAINT GE_TIPOEXPEDIENTES_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_TIPOSPERSONAS_H ADD CONSTRAINT GE_TIPOSPERSONAS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

SPOOL OFF;
