
rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_SERIES   ADD (T_CODIGO_SERIE VARCHAR2(25 CHAR));
ALTER TABLE GE_SERIES_H ADD (T_CODIGO_SERIE VARCHAR2(25 CHAR));

-- se añade aquí el script de update para poder insertar valor en la nueva columna con el valor de una columna que se borrará a continuación
UPDATE GE_SERIES SET T_CODIGO_SERIE = 
(SELECT T_CODIGO_SERIE FROM GE_ELEMENTOS_SERIES WHERE GE_ELEMENTOS_SERIES.ELEM_SER_ID = GE_SERIES.SER_ELESER_ID);

ALTER TABLE GE_SERIES   DROP COLUMN SER_ELESER_ID;
ALTER TABLE GE_SERIES_H DROP COLUMN SER_ELESER_ID;

CREATE TABLE GE_ARTICULOS_AFECTADOS_EXPDT ( ART_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0), ART_EXP_ID NUMBER(19,0) NOT NULL, ART_VALDOM_ARTAFECT_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR) ) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_ARTICULOS_AFECTADOS_EXPDT_H ( ART_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), ART_EXP_ID NUMBER(19,0), ART_VALDOM_ARTAFECT_ID NUMBER(19,0) ) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_DERECHOS_RECLAMADOS_EXPDT ( DER_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0), DER_EXP_ID NUMBER(19,0) NOT NULL, DER_VALDOM_DERRECL_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR) ) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_DERECHOS_RECLAMADOS_EXPDT_H ( DER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), DER_EXP_ID NUMBER(19,0), DER_VALDOM_DERRECL_ID NUMBER(19,0) ) TABLESPACE GESTOR_DAT;
ALTER TABLE GE_EXPEDIENTES ADD( L_COMPETENCIA_CTPDA NUMBER(1,0), EXP_VALDOM_AUTCOMP_ID NUMBER(19,0), L_AEPD NUMBER(1,0), EXP_VALDOM_TIPADM_ID NUMBER(19,0), L_IMPOSICION_MEDIDAS NUMBER(1,0), L_API NUMBER(1,0), L_OPOSICION_PERSONA NUMBER(1,0) DEFAULT 0, L_OPOSICION_REPRESENTANTE NUMBER(1,0) DEFAULT 0 );
ALTER TABLE GE_EXPEDIENTES_H ADD( L_COMPETENCIA_CTPDA NUMBER(1,0), EXP_VALDOM_AUTCOMP_ID NUMBER(19,0), L_AEPD NUMBER(1,0), EXP_VALDOM_TIPADM_ID NUMBER(19,0), L_IMPOSICION_MEDIDAS NUMBER(1,0), L_API NUMBER(1,0), L_OPOSICION_PERSONA NUMBER(1,0), L_OPOSICION_REPRESENTANTE NUMBER(1,0) );
ALTER TABLE GE_SUJETOS_OBLIGADOS_EXPDT ADD( SUJ_PER_ID NUMBER(19,0) );
ALTER TABLE GE_SUJETOS_OBLIGADOS_EXPDT_H ADD( SUJ_PER_ID NUMBER(19,0) );

CREATE TABLE GE_PERSONAS_REPRESENTANTES (PRP_ID NUMBER(19,0) NOT NULL, N_VERSION NUMBER(19,0), F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR),  PRP_PER_ID NUMBER(19,0) NOT NULL, PRP_PER_REP_ID NUMBER(19,0) NOT NULL, L_PRINCIPAL NUMBER(1,0) DEFAULT 0 NOT NULL);
CREATE TABLE GE_PERSONAS_REPRESENTANTES_H (PRP_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), N_VERSION NUMBER(19,0), F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), PRP_PER_ID NUMBER(19,0), PRP_PER_REP_ID NUMBER(19,0), L_PRINCIPAL NUMBER(1,0));

ALTER TABLE GE_PERSONAS   ADD (PER_VALDOM_TIPIDE_ID NUMBER(19,0));
ALTER TABLE GE_PERSONAS_H ADD (PER_VALDOM_TIPIDE_ID NUMBER(19,0));

ALTER TABLE GE_SUJETOS_OBLIGADOS   ADD (SUJ_VALDOM_TIPIDE_ID NUMBER(19,0));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (SUJ_VALDOM_TIPIDE_ID NUMBER(19,0));

DROP TABLE GE_COMUNICACIONES CASCADE CONSTRAINTS;
DROP TABLE GE_COMUNICACIONES_H CASCADE CONSTRAINTS;
DROP TABLE GE_MATERIAS CASCADE CONSTRAINTS;
DROP TABLE GE_MATERIAS_H CASCADE CONSTRAINTS;
DROP TABLE GE_MOTIVOSRELACION CASCADE CONSTRAINTS;
DROP TABLE GE_MOTIVOSRELACION_H CASCADE CONSTRAINTS;
DROP TABLE GE_SEXO CASCADE CONSTRAINTS;
DROP TABLE GE_SEXO_H CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOEXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOEXPEDIENTES_H CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOSPERSONAS CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOSPERSONAS_H CASCADE CONSTRAINTS;

ALTER TABLE GE_PERSONAS DROP COLUMN PER_SEX_ID;

CREATE TABLE GE_USUARIOS (USU_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, T_CONTRASENYA VARCHAR2(50 CHAR) NOT NULL, T_EMAIL VARCHAR2(100 CHAR), T_IDENTIFICADOR VARCHAR2(9 CHAR) NOT NULL, T_LOGIN VARCHAR2(50 CHAR) NOT NULL, N_VERSION NUMBER(19,0), T_NOMBRE VARCHAR2(100 CHAR) NOT NULL, T_PRIMER_APELLIDO VARCHAR2(100 CHAR) NOT NULL, T_SEGUNDO_APELLIDO VARCHAR2(100 CHAR), N_TELEFONO NUMBER(19,0), USU_VALDOM_TIPIDE_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_USUARIOS_H (USU_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACTIVA NUMBER(1,0), T_CONTRASENYA VARCHAR2(255 CHAR), T_EMAIL VARCHAR2(255 CHAR), T_IDENTIFICADOR VARCHAR2(255 CHAR), T_LOGIN VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0), T_NOMBRE VARCHAR2(255 CHAR), T_PRIMER_APELLIDO VARCHAR2(255 CHAR), T_SEGUNDO_APELLIDO VARCHAR2(255 CHAR), N_TELEFONO NUMBER(19,0), USU_VALDOM_TIPIDE_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_PERFILES (PER_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, C_CODIGO VARCHAR2(10 CHAR) NOT NULL, D_DESCRIPCION VARCHAR2(50 CHAR) NOT NULL, N_VERSION NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_PERFILES_H (PER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACTIVA NUMBER(1,0), C_CODIGO VARCHAR2(255 CHAR), D_DESCRIPCION VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_USUARIOS_PERFILES (USU_PER_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, N_VERSION NUMBER(19,0), USUPER_PER_ID NUMBER(19,0) NOT NULL, USUPER_USU_ID NUMBER(19,0) NOT NULL) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_USUARIOS_PERFILES_H (USU_PER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACTIVA NUMBER(1,0), N_VERSION NUMBER(19,0), USUPER_PER_ID NUMBER(19,0), USUPER_USU_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_PERMISOS (PER_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, C_CODIGO VARCHAR2(20 CHAR) NOT NULL, D_DESCRIPCION VARCHAR2(50 CHAR) NOT NULL, N_VERSION NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_PERMISOS_H (PER_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACTIVA NUMBER(1,0), C_CODIGO VARCHAR2(255 CHAR), D_DESCRIPCION VARCHAR2(255 CHAR), N_VERSION NUMBER(19,0)) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_PERMISOS_PERFILES (PERM_PERF_ID NUMBER(19,0) NOT NULL, F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL, N_VERSION NUMBER(19,0), PERMPERF_PERF_ID NUMBER(19,0) NOT NULL, PERMPERF_PERM_ID NUMBER(19,0) NOT NULL) TABLESPACE GESTOR_DAT;
CREATE TABLE GE_PERMISOS_PERFILES_H (PERM_PERF_ID NUMBER(19,0) NOT NULL, REV NUMBER(19,0) NOT NULL, REVTYPE NUMBER(3,0), L_ACTIVA NUMBER(1,0), N_VERSION NUMBER(19,0), PERMPERF_PERF_ID NUMBER(19,0), PERMPERF_PERM_ID NUMBER(19,0)) TABLESPACE GESTOR_DAT;


ALTER TABLE GE_PAISES MODIFY D_DESCRIPCION VARCHAR2(255 CHAR);
ALTER TABLE GE_PAISES_H MODIFY D_DESCRIPCION VARCHAR2(255 CHAR);


ALTER TABLE GE_USUARIOS  ADD (F_FECHA_ULTIMO_ACCESO TIMESTAMP);
ALTER TABLE GE_USUARIOS_H ADD (F_FECHA_ULTIMO_ACCESO TIMESTAMP);



SPOOL OFF;
