rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.5.0 --
-------------------

DROP SEQUENCE S_COMUNICACIONES;
DROP SEQUENCE S_MATERIA;
DROP SEQUENCE S_MOTIVOSRELACION;
DROP SEQUENCE S_SEXO;
DROP SEQUENCE S_TIPOEXPEDIENTE;
DROP SEQUENCE S_TIPOSPERSONAS;

CREATE SEQUENCE S_PERSONAS_REPRESENTANTES START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_ARTICULOS_AFECTADOS_EXPDT START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_DERECHOS_RECLAMADOS_EXPDT START WITH 1 INCREMENT BY  1;

CREATE SEQUENCE S_USUARIOS START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_PERFILES START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_PERMISOS START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_USUARIOS_PERFILES START WITH 1 INCREMENT BY  1;
CREATE SEQUENCE S_PERMISOS_PERFILES START WITH 1 INCREMENT BY  1;

DROP SEQUENCE S_PAISES;
CREATE SEQUENCE S_PAISES START WITH 1 INCREMENT BY  1;

SPOOL OFF;
