rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_03_INDICES.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_ARTICULOS_AFECTADOS_EXPDT ADD CONSTRAINT GE_ARTICULO_AFECTADO_EXPDT_PK PRIMARY KEY (ART_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_ARTICULOS_AFECTADOS_EXPDT_H ADD CONSTRAINT GE_ARTICUL_AFECTAD_EXPDT_H_PK PRIMARY KEY (ART_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_DERECHOS_RECLAMADOS_EXPDT ADD CONSTRAINT GE_DERECHO_RECLAMADO_EXPDT_PK PRIMARY KEY (DER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_DERECHOS_RECLAMADOS_EXPDT_H ADD CONSTRAINT GE_DERECH_RECLAMAD_EXPDT_H_PK PRIMARY KEY (DER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_PERSONAS_REPRESENTANTES   ADD CONSTRAINT GE_PERSONAS_REPRESENTANTE_PK   PRIMARY KEY (PRP_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERSONAS_REPRESENTANTES_H ADD CONSTRAINT GE_PERSONAS_REPRESENTANTE_H_PK PRIMARY KEY (PRP_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_USUARIOS ADD CONSTRAINT GE_USUARIOS_PK PRIMARY KEY (USU_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_USUARIOS_H ADD CONSTRAINT GE_USUARIOS_H_PK PRIMARY KEY (USU_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERFILES ADD CONSTRAINT GE_PERFILES_PK PRIMARY KEY (PER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERFILES_H ADD CONSTRAINT GE_PERFILES_H_PK PRIMARY KEY (PER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_USUARIOS_PERFILES ADD CONSTRAINT GE_USUARIOS_PERFILES_PK PRIMARY KEY (USU_PER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_USUARIOS_PERFILES_H ADD CONSTRAINT GE_USUARIOS_PERFILES_H_PK PRIMARY KEY (USU_PER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERMISOS ADD CONSTRAINT GE_PERMISOS_PK PRIMARY KEY (PER_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERMISOS_H ADD CONSTRAINT GE_PERMISOS_H_PK PRIMARY KEY (PER_ID, REV) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERMISOS_PERFILES ADD CONSTRAINT GE_PERMISOS_PERFILES_PK PRIMARY KEY (PERM_PERF_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PERMISOS_PERFILES_H ADD CONSTRAINT GE_PERMISOS_PERFILES_H_PK PRIMARY KEY (PERM_PERF_ID, REV) USING INDEX TABLESPACE GESTOR_IND;


SPOOL OFF;