rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_SERIES MODIFY (T_CODIGO_SERIE NOT NULL ENABLE);

ALTER TABLE GE_ARTICULOS_AFECTADOS_EXPDT ADD CONSTRAINT GE_ART_EXP_FK FOREIGN KEY (ART_EXP_ID) REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_ARTICULOS_AFECTADOS_EXPDT ADD CONSTRAINT GE_ART_VALDOM_ARTAFECT_FK FOREIGN KEY (ART_VALDOM_ARTAFECT_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_ARTICULOS_AFECTADOS_EXPDT_H ADD CONSTRAINT GE_ART_EXP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_DERECHOS_RECLAMADOS_EXPDT ADD CONSTRAINT GE_DER_EXP_FK FOREIGN KEY (DER_EXP_ID) REFERENCES GE_EXPEDIENTES;
ALTER TABLE GE_DERECHOS_RECLAMADOS_EXPDT ADD CONSTRAINT GE_DER_VALDOM_DERRECL_FK FOREIGN KEY (DER_VALDOM_DERRECL_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_DERECHOS_RECLAMADOS_EXPDT_H ADD CONSTRAINT GE_DER_EXP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_EXPEDIENTES ADD CONSTRAINT GE_EXP_VALDOM_AUTCOMP_FK FOREIGN KEY (EXP_VALDOM_AUTCOMP_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_EXPEDIENTES ADD CONSTRAINT GE_EXP_VALDOM_TIPADM_FK FOREIGN KEY (EXP_VALDOM_TIPADM_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_SUJETOS_OBLIGADOS_EXPDT ADD CONSTRAINT GE_SUJ_PER_FK FOREIGN KEY (SUJ_PER_ID) REFERENCES GE_PERSONAS;

ALTER TABLE GE_PERSONAS_REPRESENTANTES ADD CONSTRAINT GE_PRP_PERSONA_FK FOREIGN KEY (PRP_PER_ID)
  REFERENCES GE_PERSONAS (PER_ID) ENABLE; 

ALTER TABLE GE_PERSONAS_REPRESENTANTES ADD CONSTRAINT GE_PRP_PERSONA_REP_FK FOREIGN KEY (PRP_PER_REP_ID)
  REFERENCES GE_PERSONAS (PER_ID) ENABLE;  	

ALTER TABLE GE_PERSONAS_REPRESENTANTES_H ADD CONSTRAINT GE_PRP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_PERSONAS ADD CONSTRAINT GE_PERSONA_VALDOM_TIPIDE_FK FOREIGN KEY (PER_VALDOM_TIPIDE_ID) REFERENCES GE_VALORES_DOMINIOS;

ALTER TABLE GE_SUJETOS_OBLIGADOS ADD CONSTRAINT GE_SUJOBLI_VALDOM_TIPIDE_FK FOREIGN KEY (SUJ_VALDOM_TIPIDE_ID) REFERENCES GE_VALORES_DOMINIOS;

ALTER TABLE GE_USUARIOS ADD CONSTRAINT GE_USUARIO_VALDOM_TIPIDE_FK FOREIGN KEY (USU_VALDOM_TIPIDE_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_USUARIOS_H ADD CONSTRAINT GE_USUARIOS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_PERFILES_H ADD CONSTRAINT GE_PERFILES_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_PERMISOS_H ADD CONSTRAINT GE_PERMISOS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_PERMISOS_PERFILES ADD CONSTRAINT GE_PERMPERF_PERF_FK FOREIGN KEY (PERMPERF_PERF_ID) REFERENCES GE_PERFILES;
ALTER TABLE GE_PERMISOS_PERFILES ADD CONSTRAINT GE_PERMPERF_PERM_FK FOREIGN KEY (PERMPERF_PERM_ID) REFERENCES GE_PERMISOS;
ALTER TABLE GE_PERMISOS_PERFILES_H ADD CONSTRAINT GE_PERM_PERF_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_USUARIOS_PERFILES ADD CONSTRAINT GE_USUPER_PER_FK FOREIGN KEY (USUPER_PER_ID) REFERENCES GE_PERFILES;
ALTER TABLE GE_USUARIOS_PERFILES ADD CONSTRAINT GE_USUPER_USU_FK FOREIGN KEY (USUPER_USU_ID) REFERENCES GE_USUARIOS;
ALTER TABLE GE_USUARIOS_PERFILES_H ADD CONSTRAINT GE_USU_PERF_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;


SPOOL OFF;