rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

INSERT INTO GE_DOMINIOS (DOM_ID, C_CODIGO, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO_MAX, L_BLOQUEADO, L_VISIBLE, L_PUNTO_MENU, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_DOMINIOS.NEXTVAL,'AUT_COMP', 'Autoridad competente',0,0,1,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_DOMINIOS (DOM_ID, C_CODIGO, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO_MAX, L_BLOQUEADO, L_VISIBLE, L_PUNTO_MENU, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_DOMINIOS.NEXTVAL,'TIP_ADM', 'Tipos de admisión',0,0,1,0,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_DOMINIOS (DOM_ID, C_CODIGO, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO_MAX, L_BLOQUEADO, L_VISIBLE, L_PUNTO_MENU, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_DOMINIOS.NEXTVAL,'ARTICULO', 'Artículo afectado',0,0,1,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_DOMINIOS (DOM_ID, C_CODIGO, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO_MAX, L_BLOQUEADO, L_VISIBLE, L_PUNTO_MENU, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_DOMINIOS.NEXTVAL,'DER_RECL', 'Derecho reclamado',0,0,1,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Autoridad competente'), 'AEPD','Agencia Española de Protección de Datos','AEPD',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Autoridad competente')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Autoridad competente'), 'AVPD','Agencia Vasca de Protección de Datos','AVPD',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Autoridad competente')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Autoridad competente'), 'APDCAT','Autoridad Catalana de Protección de Datos','APDCAT',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Autoridad competente')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de admisión'), 'FOR','Formal','Frml',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de admisión')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de admisión'), 'DE_HEC','De hecho','D. hcho',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de admisión')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de admisión'), 'INA','Inadmisión','Inadm',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de admisión')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Artículo afectado'), 'RGPD15','Artículo 15 RGPD','RGPD15',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Artículo afectado')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Artículo afectado'), 'RGPD16','Artículo 16 RGPD','RGPD16',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Artículo afectado')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Artículo afectado'), 'RGPD17','Artículo 17 RGPD','RGPD17',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Artículo afectado')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Derecho reclamado'), 'ACC','Derecho de Acceso','ACC',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Derecho reclamado')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Derecho reclamado'), 'REC','Derecho de Rectificación','REC',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Derecho reclamado')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Derecho reclamado'), 'SUP','Derecho de Supresión','SUP',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Derecho reclamado')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_DOMINIOS (DOM_ID, C_CODIGO, D_DESCRIPCION, N_NIVEL_ANIDAMIENTO_MAX, L_BLOQUEADO, L_VISIBLE, L_PUNTO_MENU, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_DOMINIOS.NEXTVAL,'TIP_IDE','Tipo de identificador',0,0,1,0,SYSDATE, (SELECT USER FROM DUAL), 0);

INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador'),'NIF','NIF',  'NIF', 0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador'),'NIE','NIE',  'NIE', 0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador'),'OTR','Otros','Otrs',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador'),'CIF','CIF','CIF',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 1 WHERE C_CODIGO IN ('NIF', 'CIF', 'NIE');

--Actualizar para los bloqueos de los Valores de Dominio
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 1 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de expedientes');
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 1 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de expedientes');

-- Establecer valor de tipo identificador 'Otros' para las personas jurídicas.
UPDATE GE_PERSONAS SET PER_VALDOM_TIPIDE_ID =   (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'OTR' AND VALDOM_DOM_ID = ((SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador'))) WHERE PER_VALDOM_TIPPER_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'JUR');

INSERT INTO GE_PERFILES (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERFILES.NEXTVAL,'ADMIN','Administrador',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERFILES (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERFILES.NEXTVAL,'ADM_FUNC','Administrador Funcional',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERFILES (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERFILES.NEXTVAL,'ADMTTVO','Administrativo',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERFILES (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERFILES.NEXTVAL,'GES','Gestor',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERFILES (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERFILES.NEXTVAL,'CON','Consulta',1,SYSDATE, (SELECT USER FROM DUAL), 0);

INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'PARAM','Parámetros',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'LIST_DOM','Listado de dominios',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'LIST_VALDOM','Listado de valores de dominio',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'FORM_VALDOM','Formulario de valores de dominio',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'LIST_TIPAGRUP','Listado de tipos de agrupación',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'FORM_TIPAGRUP','Formulario de tipos de agrupación',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'LIST_SUJOBL','Listado de sujetos obligados',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'NEW_SUJOBL','Nuevo sujeto obligado',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'FORM_SUJOBL','Formulario de sujetos obligados',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'SAVE_SUJOBL','Guardar sujeto obligado',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'LIST_PERS','Listado de personas',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'NEW_PERS','Nueva persona',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'FORM_PERS','Formulario de personas',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'SAVE_PERS','Guardar persona',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'LIST_EXP','Listado de expedientes',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'NEW_EXP','Nuevo expediente',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'FORM_EXP','Formulario de expedientes',1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS.NEXTVAL,'SAVE_EXP','Guardar expediente',1,SYSDATE, (SELECT USER FROM DUAL), 0);


INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
		VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'PARAM'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_DOM'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_VALDOM'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_VALDOM'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_TIPAGRUP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_TIPAGRUP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);


INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_DOM'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_VALDOM'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_VALDOM'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADM_FUNC'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);

INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMTTVO'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		


INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'GES'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'GES'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'GES'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'GES'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'GES'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'GES'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'GES'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'GES'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);		

INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'CON'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);	
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'CON'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_SUJOBL'),1,SYSDATE, (SELECT USER FROM DUAL), 0);	
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'CON'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);	
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'CON'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_PERS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);	
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'CON'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);	
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) 
	VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'CON'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'FORM_EXP'),1,SYSDATE, (SELECT USER FROM DUAL), 0);	
		
UPDATE GE_PERSONAS SET PER_PAI_ID = NULL;
UPDATE GE_SUJETOS_OBLIGADOS SET SUJ_PAI_ID = NULL;

DELETE FROM GE_PAISES;
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AF', 'Afganistán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AL', 'Albania',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'DE', 'Alemania',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AD', 'Andorra',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AO', 'Angola',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AI', 'Anguila',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AG', 'Antigua y Barbuda',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AQ', 'Antártida',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SA', 'Arabia Saudita',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'DZ', 'Argelia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AR', 'Argentina',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AM', 'Armenia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AW', 'Aruba',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AU', 'Australia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AT', 'Austria',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AZ', 'Azerbaiyán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BS', 'Bahamas (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BD', 'Bangladés',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BB', 'Barbados',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BH', 'Baréin',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BZ', 'Belice',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BJ', 'Benín',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BM', 'Bermudas',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BY', 'Bielorrusia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BO', 'Bolivia, Estado Plurinacional de',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BQ', 'Bonaire, San Eustaquio y Saba',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BA', 'Bosnia y Herzegovina',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BW', 'Botsuana',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BR', 'Brasil',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BN', 'Brunéi Darussalam',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BG', 'Bulgaria',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BF', 'Burkina Faso',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BI', 'Burundi',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BT', 'Bután',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BE', 'Bélgica',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CV', 'Cabo Verde',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KH', 'Camboya',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CM', 'Camerún',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CA', 'Canadá',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'QA', 'Catar',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TD', 'Chad',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CL', 'Chile',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CN', 'China',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CY', 'Chipre',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CO', 'Colombia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KM', 'Comoras',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CG', 'Congo',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CD', 'Congo (la República Democrática del)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KP', 'Corea (la República Democrática Popular de)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KR', 'Corea (la República de)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CR', 'Costa Rica',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CI', 'Cote d Ivoire',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'HR', 'Croacia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CU', 'Cuba',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CW', 'Curaçao',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'DK', 'Dinamarca',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'DM', 'Dominica',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'EC', 'Ecuador',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'EG', 'Egipto',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SV', 'El Salvador',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AE', 'Emiratos Árabes Unidos (Los)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ER', 'Eritrea',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SK', 'Eslovaquia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SI', 'Eslovenia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ES', 'España',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'US', 'Estados Unidos (los)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'EE', 'Estonia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ET', 'Etiopía',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PH', 'Filipinas (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'FI', 'Finlandia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'FJ', 'Fiyi',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'FR', 'Francia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GA', 'Gabón',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GM', 'Gambia (La)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GE', 'Georgia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GS', 'Georgia del sur y las islas sandwich del sur',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GH', 'Ghana',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GI', 'Gibraltar',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GD', 'Granada',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GR', 'Grecia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GL', 'Groenlandia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GP', 'Guadalupe',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GU', 'Guam',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GT', 'Guatemala',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GF', 'Guayana Francesa',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GG', 'Guernsey',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GN', 'Guinea',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GQ', 'Guinea Ecuatorial',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GW', 'Guinea-Bisáu',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GY', 'Guyana',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'HT', 'Haití',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'HN', 'Honduras',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'HK', 'Hong Kong',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'HU', 'Hungría',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IN', 'India',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ID', 'Indonesia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IQ', 'Irak',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IE', 'Irlanda',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IR', 'Irán (la República Islámica de)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BV', 'Isla Bouvet',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'HM', 'Isla Heard e Islas McDonald',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NF', 'Isla Norfolk',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IM', 'Isla de Man',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CX', 'Isla de Navidad',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IS', 'Islandia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KY', 'Islas Caimán (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CC', 'Islas Cocos (Keeling)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CK', 'Islas Cook (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'FO', 'Islas Feroe (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'FK', 'Islas Malvinas [Falkland] (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MP', 'Islas Marianas del Norte (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MH', 'Islas Marshall (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SB', 'Islas Salomón (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TC', 'Islas Turcas y Caicos (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'VG', 'Islas Vírgenes (Británicas)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'VI', 'Islas Vírgenes (EE.UU.)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'UM', 'Islas de Ultramar Menores de Estados Unidos (las)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AX', 'Islas Åland',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IL', 'Israel',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IT', 'Italia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'JM', 'Jamaica',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'JP', 'Japón',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'JE', 'Jersey',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'JO', 'Jordania',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KZ', 'Kazajistán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KE', 'Kenia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KG', 'Kirguistán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KI', 'Kiribati',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KW', 'Kuwait',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LA', 'Lao, (la) República Democrática Popular',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LS', 'Lesoto',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LV', 'Letonia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LR', 'Liberia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LY', 'Libia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LI', 'Liechtenstein',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LT', 'Lituania',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LU', 'Luxemburgo',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LB', 'Líbano',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MO', 'Macao',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MK', 'Macedonia (la antigua República Yugoslava de)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MG', 'Madagascar',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MY', 'Malasia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MW', 'Malaui',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MV', 'Maldivas',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MT', 'Malta',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ML', 'Malí',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MA', 'Marruecos',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MQ', 'Martinica',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MU', 'Mauricio',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MR', 'Mauritania',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'YT', 'Mayotte',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'FM', 'Micronesia (los Estados Federados de)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MD', 'Moldavia (la República de)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MN', 'Mongolia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ME', 'Montenegro',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MS', 'Montserrat',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MZ', 'Mozambique',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MM', 'Myanmar',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MX', 'México',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MC', 'Mónaco',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NA', 'Namibia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NR', 'Nauru',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NP', 'Nepal',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NI', 'Nicaragua',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NG', 'Nigeria',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NU', 'Niue',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NO', 'Noruega',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NC', 'Nueva Caledonia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NZ', 'Nueva Zelanda',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NE', 'Níger (el)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'OM', 'Omán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PK', 'Pakistán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PW', 'Palaos',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PS', 'Palestina, Estado de',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PA', 'Panamá',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PG', 'Papúa Nueva Guinea',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PY', 'Paraguay',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'NL', 'Países Bajos (los)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PE', 'Perú',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PN', 'Pitcairn',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PF', 'Polinesia Francesa',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PL', 'Polonia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PT', 'Portugal',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PR', 'Puerto Rico',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'GB', 'Reino Unido (el)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CF', 'República Centroafricana (la)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CZ', 'República Checa (la)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'DO', 'República Dominicana (la)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'RE', 'Reunión',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'RW', 'Ruanda',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'RO', 'Rumania',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'RU', 'Rusia, (la) Federación de',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'EH', 'Sahara Occidental',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'WS', 'Samoa',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'AS', 'Samoa Americana',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'BL', 'San Bartolomé',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'KN', 'San Cristóbal y Nieves',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SM', 'San Marino',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'MF', 'San Martín (parte francesa)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'PM', 'San Pedro y Miquelón',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'VC', 'San Vicente y las Granadinas',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SH', 'Santa Helena, Ascensión y Tristán de Acuña',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LC', 'Santa Lucía',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'VA', 'Santa Sede[Estado de la Ciudad del Vaticano] (la)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ST', 'Santo Tomé y Príncipe',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SN', 'Senegal',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'RS', 'Serbia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SC', 'Seychelles',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SL', 'Sierra Leona',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SG', 'Singapur',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SX', 'Sint Maarten (parte holandesa)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SY', 'Siria, (la) República Árabe',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SO', 'Somalia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'LK', 'Sri Lanka',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SZ', 'Suazilandia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ZA', 'Sudáfrica',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SD', 'Sudán (el)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SS', 'Sudán del Sur',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SE', 'Suecia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'CH', 'Suiza',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SR', 'Surinam',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'SJ', 'Svalbard y Jan Mayen',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TH', 'Tailandia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TW', 'Taiwán (Provincia de China)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TZ', 'Tanzania, República Unida de',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TJ', 'Tayikistán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'IO', 'Territorio Británico del Océano Índico (el)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TF', 'Territorios Australes Franceses (los)',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TL', 'Timor-Leste',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TG', 'Togo',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TK', 'Tokelau',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TO', 'Tonga',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TT', 'Trinidad y Tobago',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TM', 'Turkmenistán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TR', 'Turquía',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TV', 'Tuvalu',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'TN', 'Túnez',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'UA', 'Ucrania',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'UG', 'Uganda',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'UY', 'Uruguay',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'UZ', 'Uzbekistán',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'VU', 'Vanuatu',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'VE', 'Venezuela, República Bolivariana de',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'VN', 'Viet Nam',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'WF', 'Wallis y Futuna',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'YE', 'Yemen',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'DJ', 'Yibuti',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ZM', 'Zambia',1);
INSERT INTO GE_PAISES (PAI_ID, N_VERSION, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION,L_ACTIVA) VALUES (S_PAISES.NEXTVAL, 0, SYSDATE, (SELECT USER FROM DUAL), 'ZW', 'Zimbabue',1);


--Actualizar para los bloqueos de los Valores de Dominio
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 1 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'FIS') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de personas');
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 1 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'JUR') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipos de personas');

--Actualizar para los bloqueos de los Valores de Dominio
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 1 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'CIF') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador');
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 1 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'NIF') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador');
UPDATE GE_VALORES_DOMINIOS SET L_BLOQUEADO = 1 WHERE VAL_DOM_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'NIE') AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Tipo de identificador');

SPOOL OFF;
