rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/005_06_GRANTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_ARTICULOS_AFECTADOS_EXPDT TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_ARTICULOS_AFECTADOS_EXPDT TO GE_ROL_GESTOR_DML; 
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_ARTICULOS_AFECTADOS_EXPDT_H TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DERECHOS_RECLAMADOS_EXPDT TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_DERECHOS_RECLAMADOS_EXPDT TO GE_ROL_GESTOR_DML;
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DERECHOS_RECLAMADOS_EXPDT_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PERSONAS_REPRESENTANTES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_PERSONAS_REPRESENTANTES TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PERSONAS_REPRESENTANTES_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_USUARIOS TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_USUARIOS TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_USUARIOS_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PERFILES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_PERFILES TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PERFILES_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PERMISOS TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_PERMISOS TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PERMISOS_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_USUARIOS_PERFILES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_USUARIOS_PERFILES TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_USUARIOS_PERFILES_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PERMISOS_PERFILES TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_PERMISOS_PERFILES TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_PERMISOS_PERFILES_H TO GE_ROL_GESTOR_DML;


SPOOL OFF;