rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/011_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.11.0 --
--------------------


ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN TRAM_EXP_USU_ALTA_ID;
ALTER TABLE GE_TRAMITE_EXPED_H DROP COLUMN TRAM_EXP_USU_ALTA_ID;

DROP TABLE GE_RESOLUCIONES CASCADE CONSTRAINTS;
DROP TABLE GE_RESOLUCIONES_H CASCADE CONSTRAINTS;

DROP TABLE GE_RESOL_EXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_RESOL_EXPEDIENTES_H CASCADE CONSTRAINTS;

DROP TABLE GE_RESOL_SUJOBL CASCADE CONSTRAINTS;
DROP TABLE GE_RESOL_SUJOBL_H CASCADE CONSTRAINTS;

DROP TABLE GE_RESOL_PERSONA CASCADE CONSTRAINTS;
DROP TABLE GE_RESOL_PERSONA_H CASCADE CONSTRAINTS;

DROP TABLE GE_ARTICULOS_AFECTAD_RESOL CASCADE CONSTRAINTS;
DROP TABLE GE_ARTICULOS_AFECTAD_RESOL_H CASCADE CONSTRAINTS;

DROP TABLE GE_DERECH_RECLAM_RESOL CASCADE CONSTRAINTS;
DROP TABLE GE_DERECH_RECLAM_RESOL_H CASCADE CONSTRAINTS;

DROP TABLE GE_DOCUMENTOS_RESOLUCIONES CASCADE CONSTRAINTS;
DROP TABLE GE_DOCUMENTOS_RESOLUCIONES_H CASCADE CONSTRAINTS;

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN F_FECHA_RESOLUCION;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN F_FECHA_RESOLUCION;


ALTER TABLE GE_CFG_METADATOS_TRAM DROP COLUMN D_FECHA_RESOLUCION;
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP COLUMN D_FECHA_RESOLUCION;

-- ------------------------

ALTER TABLE GE_TAREAS_EXPEDIENTE   DROP COLUMN L_URGENTE;
ALTER TABLE GE_TAREAS_EXPEDIENTE_H DROP COLUMN L_URGENTE;

ALTER TABLE GE_EXPEDIENTES   DROP COLUMN  T_EXPEDIENTE_IDENTIFICADO;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN T_EXPEDIENTE_IDENTIFICADO;

-- ------------------------

DROP TABLE GE_ACCESOS_DOCS CASCADE CONSTRAINTS;
DROP TABLE GE_ACCESOS_DOCS_H CASCADE CONSTRAINTS;

---------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN DETEXPTRAM_VALDOMTIPRES_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN DETEXPTRAM_VALDOMTIPRES_ID;

ALTER TABLE GE_CFG_METADATOS_TRAM DROP COLUMN D_TIPO_RESOLUCION;
ALTER TABLE GE_CFG_METADATOS_TRAM_H DROP COLUMN D_TIPO_RESOLUCION;

-- ------------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM   DROP (DETEXPTRAM_VALDOMRESNOTIF_ID);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP (DETEXPTRAM_VALDOMRESNOTIF_ID);

-- ------------------------

ALTER TABLE GE_PERFILES DROP ( D_DESCRIPCION_CORTA);
ALTER TABLE GE_PERFILES_H DROP ( D_DESCRIPCION_CORTA);

ALTER TABLE GE_TRAMITE_EXPED ADD T_RESPONSABLE VARCHAR2(255 CHAR);

---------------------------------

COMMENT ON TABLE GE_DATOS_TMP_USUARIO IS '';

ALTER TABLE GE_ACCESOS_DOCS_H MODIFY ( ACD_ID NULL); 
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (L_ERRONEO NOT NULL);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (L_DPD NOT NULL);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (L_UNIDAD_TRANSPARENCIA NOT NULL);

SPOOL OFF;
