rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/011_UNDO_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


-------------------
-- VERSION 0.11.0 --
-------------------

DROP SEQUENCE S_RESOLUCION;
DROP SEQUENCE S_RESOL_EXPEDIENTES;
DROP SEQUENCE S_RESOL_SUJOBL;
DROP SEQUENCE S_RESOL_PERS;
DROP SEQUENCE S_ARTICULOS_AFECTAD_RESOL;
DROP SEQUENCE S_DERECH_RECLAM_RESOL;
DROP SEQUENCE S_DOCUMENTOS_RESOLUCIONES;

DROP SEQUENCE S_ACCESOS_DOCS;


SPOOL OFF;
