rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/011_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

---------------------
-- VERSION 0.11.0 --
---------------------


DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIPORESOL');
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'TIPORESOL';

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SENT_RESOL') AND C_CODIGO = 'APERC';
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SENT_RESOL') AND C_CODIGO = 'TERM';

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SERIESRESOL');
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'SERIESRESOL';

DELETE FROM GE_SERIES WHERE T_CODIGO_SERIE = 'RECSEC';
DELETE FROM GE_SERIES WHERE T_CODIGO_SERIE = 'RPSSEC';
DELETE FROM GE_SERIES WHERE T_CODIGO_SERIE = 'RARSEC';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'RED';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'RPS';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'RAR';

UPDATE GE_CFG_METADATOS_TRAM SET D_FECHA_RESOLUCION = '' WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'RESOL');

-- ---------------------------------------------

DELETE FROM GE_CFG_TAREAS WHERE CFGTAR_VALDOM_TIP_TAR_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TAREAS') AND C_CODIGO = 'FYN');
DELETE FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'FYN';


DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND PLAAUT_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'RESOL');
DELETE FROM GE_CFG_PLAZOS_AUT WHERE PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP')) AND PLAAUT_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'RESOL');

DELETE FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'CON' AND VALDOM_VALDOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_ACC');
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_ACC';

-- -----------

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_VALDOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'RES_NOTIF');
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'RES_NOTIF';


-- Permiso para consultar tramite desde evolución
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'CONS_TRAM_EVOL');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'CONS_TRAM_EVOL';

-- Modificación literal etiqueta Resultado Notificación
UPDATE GE_CFG_METADATOS_TRAM SET D_NOTIF_INFRUCTUOSA = 'Notificación infructuosa';

-- Permisos para listado, edición y consulta de resoluciones
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'MENU_RESOL');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'MENU_RESOL';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'EDIT_RESOL');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'EDIT_RESOL';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'VER_RESOL');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'VER_RESOL';

DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'EDIT_RESOL_EXP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'EDIT_RESOL_EXP';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'DEL_RESOL_EXP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'DEL_RESOL_EXP';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'EDIT_RESOL_PERS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'EDIT_RESOL_PERS';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'DEL_RESOL_PERS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'DEL_RESOL_PERS';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'EDIT_RESOL_SUJ');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'EDIT_RESOL_SUJ';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'DEL_RESOL_SUJ');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'DEL_RESOL_SUJ';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'EDIT_RESOL_DOC');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'EDIT_RESOL_DOC';
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'DEL_RESOL_DOC');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'DEL_RESOL_DOC';

-- Permiso para usuarios
DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_USUARIOS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'LIST_USUARIOS';

DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'ACT_USUARIOS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'ACT_USUARIOS';

DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'CONS_USUARIOS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'CONS_USUARIOS';

DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'DESAC_USUARIOS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'DESAC_USUARIOS';

DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'EDIT_USUARIOS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'EDIT_USUARIOS';

DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_USUARIOS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'NEW_USUARIOS';

DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_USUARIOS');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'SAVE_USUARIOS';


UPDATE GE_CFG_METADATOS_TRAM SET D_FECHA_RESOLUCION = ''
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'RESOL');

UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_RESOLUCION = ''
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'RESOL');


DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'BUS_USUPER');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'BUS_USUPER';



SPOOL OFF;
