rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/009_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.9.0 --
-------------------

ALTER TABLE GE_EXPEDIENTES   ADD ( EXP_RESTRA_ID NUMBER(19, 0) );
ALTER TABLE GE_EXPEDIENTES_H ADD ( EXP_RESTRA_ID NUMBER(19, 0) );

ALTER TABLE GE_TRAMITE_EXPED   ADD ( TRAM_EXP_RESTRA_ID NUMBER(19, 0) );
ALTER TABLE GE_TRAMITE_EXPED_H ADD ( TRAM_EXP_RESTRA_ID NUMBER(19, 0) );


CREATE TABLE GE_DATOS_TMP_USUARIO (
	TMP_ID NUMBER(19,0) NOT NULL,
	--F_CREACION TIMESTAMP, F_MODIFICACION TIMESTAMP, USU_CREACION VARCHAR2(25 CHAR), USU_MODIFICACION VARCHAR2(25 CHAR), 
	N_VERSION NUMBER(19,0),
	TMP_USU_ID NUMBER(19,0) NOT NULL,
	B_BYTES BLOB NOT NULL,
	T_NOMBRE VARCHAR(150),
	T_TIPO_MIME VARCHAR(50) -- Content type
) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_MATERIAS_EXPDT ( 
	MATEXP_ID NUMBER(19,0) NOT NULL, 
	N_VERSION NUMBER(19,0), 
	MATEXP_EXP_ID NUMBER(19,0) NOT NULL, 
	MATEXP_MATTIPEXP_ID NUMBER(19,0) NOT NULL, 
	F_CREACION TIMESTAMP, 
	F_MODIFICACION TIMESTAMP, 
	USU_CREACION VARCHAR2(25 CHAR), 
	USU_MODIFICACION VARCHAR2(25 CHAR) 
) TABLESPACE GESTOR_DAT;

CREATE TABLE GE_MATERIAS_EXPDT_H ( 
	MATEXP_ID NUMBER(19,0) NOT NULL, 
	REV NUMBER(19,0) NOT NULL, 
	REVTYPE NUMBER(3,0), 
	N_VERSION NUMBER(19,0), 
	MATEXP_EXP_ID NUMBER(19,0), 
	MATEXP_MATTIPEXP_ID NUMBER(19,0) 
) TABLESPACE GESTOR_DAT;

ALTER TABLE GE_EXPEDIENTES DROP COLUMN EXP_VALDOM_MAT_ID;
ALTER TABLE GE_EXPEDIENTES_H DROP COLUMN EXP_VALDOM_MAT_ID;


ALTER TABLE GE_SUJETOS_OBLIGADOS ADD (T_PUESTO_TITULAR VARCHAR(255));
ALTER TABLE GE_SUJETOS_OBLIGADOS ADD (L_UNIDAD_TRANSPARENCIA NUMBER(1,0) DEFAULT(0) NOT NULL);
ALTER TABLE GE_SUJETOS_OBLIGADOS ADD (T_CONTACT_UNIDAD_TRANSPARENCIA VARCHAR(255));
ALTER TABLE GE_SUJETOS_OBLIGADOS ADD (L_DPD NUMBER(1,0) DEFAULT(0) NOT NULL);
ALTER TABLE GE_SUJETOS_OBLIGADOS ADD (T_CONTACTO_DPD VARCHAR(255));

ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (T_PUESTO_TITULAR VARCHAR(255));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (L_UNIDAD_TRANSPARENCIA NUMBER(1,0) DEFAULT(0) NOT NULL);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (T_CONTACT_UNIDAD_TRANSPARENCIA VARCHAR(255));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (L_DPD NUMBER(1,0) DEFAULT(0) NOT NULL);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (T_CONTACTO_DPD VARCHAR(255));

ALTER TABLE GE_SUJETOS_OBLIGADOS ADD L_ERRONEO NUMBER(1,0) DEFAULT(0) NOT NULL;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD L_ERRONEO NUMBER(1,0) DEFAULT(0) NOT NULL;

ALTER TABLE GE_TAREAS_EXPEDIENTE ADD   ( T_INDICACIONES_SIG VARCHAR2(500) );
ALTER TABLE GE_TAREAS_EXPEDIENTE_H ADD ( T_INDICACIONES_SIG VARCHAR2(500) );

ALTER TABLE GE_TRAMITE_EXPED   ADD ( TRAM_EXP_USU_FIN_ID NUMBER(19, 0) );	
ALTER TABLE GE_TRAMITE_EXPED   ADD ( F_FECHA_FIN_REAL TIMESTAMP );
ALTER TABLE GE_TRAMITE_EXPED   ADD ( F_FECHA_FIN TIMESTAMP );

ALTER TABLE GE_TRAMITE_EXPED_H ADD ( TRAM_EXP_USU_FIN_ID NUMBER(19, 0) );
ALTER TABLE GE_TRAMITE_EXPED_H ADD ( F_FECHA_FIN_REAL TIMESTAMP );	
ALTER TABLE GE_TRAMITE_EXPED_H ADD ( F_FECHA_FIN TIMESTAMP );

SPOOL OFF;
