rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/009_03_INDICES.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.9.0 --
-------------------

ALTER TABLE GE_MATERIAS_EXPDT ADD CONSTRAINT GE_MATERIAS_EXPDT_PK PRIMARY KEY (MATEXP_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_MATERIAS_EXPDT_H ADD CONSTRAINT GE_MATERIAS_EXPDT_H_PK PRIMARY KEY (MATEXP_ID, REV) USING INDEX TABLESPACE GESTOR_IND;



SPOOL OFF;