rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/009_06_GRANTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.9.0 --
-------------------


GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DATOS_TMP_USUARIO TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_DATOS_TMP_USUARIO TO GE_ROL_GESTOR_DML;
--GRANT SELECT, UPDATE, INSERT, DELETE ON GE_DATOS_TMP_USUARIO_H TO GE_ROL_GESTOR_DML;

GRANT SELECT, UPDATE, INSERT, DELETE ON GE_MATERIAS_EXPDT TO GE_ROL_GESTOR_DML;
GRANT SELECT, ALTER ON S_MATERIAS_EXPDT TO GE_ROL_GESTOR_DML; 
GRANT SELECT, UPDATE, INSERT, DELETE ON GE_MATERIAS_EXPDT_H TO GE_ROL_GESTOR_DML;


SPOOL OFF;
