rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/014_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

---------------------
-- VERSION 0.14.0  --
---------------------

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_OBS');

INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_OBS'),'TEM','Temporal','Temp',0,1,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_OBS')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_OBS'),'PERM','Permanente','Per',0,2,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_OBS')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_OBS'),'ESP','Especial','Esp',0,3,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_OBS')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);

INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES 
(S_PERMISOS.NEXTVAL,'NEW_EXPOBS','Nueva observacion de expediente',1,SYSDATE, (SELECT USER FROM DUAL), 0);

INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES 
(S_PERMISOS.NEXTVAL,'CONS_EXPOBS','Consultar observacion de expediente',1,SYSDATE, (SELECT USER FROM DUAL), 0);

INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES 
(S_PERMISOS.NEXTVAL,'EDIT_EXPOBS','Editar observacion de expediente',1,SYSDATE, (SELECT USER FROM DUAL), 0);

INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES 
(S_PERMISOS.NEXTVAL,'DEL_EXPOBS','Eliminar observacion de expediente',1,SYSDATE, (SELECT USER FROM DUAL), 0);

INSERT INTO GE_PERMISOS (PER_ID, C_CODIGO, D_DESCRIPCION, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES 
(S_PERMISOS.NEXTVAL,'SAVE_EXPOBS','Guardar observacion de expediente',1,SYSDATE, (SELECT USER FROM DUAL), 0);


INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'CONS_EXPOBS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'EDIT_EXPOBS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'DEL_EXPOBS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'SAVE_EXPOBS'),1,SYSDATE, (SELECT USER FROM DUAL), 0);

-- ------------


DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'VIEW_TRAM_AB');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'VIEW_TRAM_AB';

-- ----------------


UPDATE GE_SERIES SET T_PATRON = 'RED-{3}/2022' WHERE T_CODIGO_SERIE = 'RECSEC';
UPDATE GE_SERIES SET T_PATRON = 'RPS-{3}/2022' WHERE T_CODIGO_SERIE = 'RPSSEC';
UPDATE GE_SERIES SET T_PATRON = 'RAR-{3}/2022' WHERE T_CODIGO_SERIE = 'RARSEC';

-- ----------------
UPDATE GE_VALORES_DOMINIOS SET L_ACTIVO = 1 WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_INT') AND C_CODIGO = 'DPD';
UPDATE GE_VALORES_DOMINIOS SET D_DESCRIPCION = 'XPC Pendiente de calificación', T_ABREVIATURA = 'XPC', L_BLOQUEADO = 1 WHERE C_CODIGO = 'XPC' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_EXP');

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'MOT_REL_EXP_PER') AND C_CODIGO = 'NC';

UPDATE GE_SERIES SET N_NUMERO_FINAL = 999, T_PATRON = 'XPC-2022/{3}' WHERE T_CODIGO_SERIE = 'XPCSEC';

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'CAN_ENT') AND C_CODIGO = 'OTROS';

-- ----------------

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_FIRM');

DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_FIRM';


SPOOL OFF;
