rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/009_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION prueba --
-------------------



CREATE TABLE FOR_PRUEBAS_PEDRO_ROMERO (
	PRUD_ID NUMBER(19,0) NOT NULL,
	F_CREACION TIMESTAMP,
	F_MODIFICACION TIMESTAMP,
	USU_CREACION VARCHAR2(25 CHAR),
	USU_MODIFICACION VARCHAR2(25 CHAR), 
	N_VERSION NUMBER(19,0),
	L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL,
	C_CODIGO VARCHAR2(50 CHAR) NOT NULL,
	D_DESCRIPCION VARCHAR2(225 CHAR) NOT NULL
) TABLESPACE GESTOR_DAT;


CREATE TABLE FOR_PRUEBAS_PEDRO_ROMERO_H (
	PRUD_ID NUMBER(19,0) NOT NULL,
	REV NUMBER(19,0) NOT NULL,
	REVTYPE NUMBER(3,0),
	F_CREACION TIMESTAMP,
	F_MODIFICACION TIMESTAMP,
	USU_CREACION VARCHAR2(25 CHAR),
	USU_MODIFICACION VARCHAR2(25 CHAR), 
	N_VERSION NUMBER(19,0),
	L_ACTIVA NUMBER(1,0) DEFAULT 1 NOT NULL,
	C_CODIGO VARCHAR2(50 CHAR) NOT NULL,
	D_DESCRIPCION VARCHAR2(225 CHAR) NOT NULL
) TABLESPACE GESTOR_DAT;

CREATE SEQUENCE S_FOR_PRUEBAS_PEDRO_ROMERO START WITH 1 INCREMENT BY  1;

ALTER TABLE FOR_PRUEBAS_PEDRO_ROMERO ADD CONSTRAINT FOR_PRUEBAS_PEDRO_ROMERO_PK PRIMARY KEY (PRUD_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE FOR_PRUEBAS_PEDRO_ROMERO_H ADD CONSTRAINT FOR_PRUEBAS_PEDRO_ROMERO_H_PK PRIMARY KEY (PRUD_ID, REV) USING INDEX TABLESPACE GESTOR_IND;


ALTER TABLE FOR_PRUEBAS_PEDRO_ROMERO_H ADD CONSTRAINT FOR_PRUEBAS_PEDRO_ROMERO_H_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;


INSERT INTO FOR_PRUEBAS_PEDRO_ROMERO (PRUD_ID, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_FOR_PRUEBAS_PEDRO_ROMERO.NEXTVAL, SYSDATE, (select USER FROM DUAL), 'P1', 'Prueba 1', 1);
INSERT INTO FOR_PRUEBAS_PEDRO_ROMERO (PRUD_ID, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_FOR_PRUEBAS_PEDRO_ROMERO.NEXTVAL, SYSDATE, (select USER FROM DUAL), 'P2', 'Prueba 2', 1);
INSERT INTO FOR_PRUEBAS_PEDRO_ROMERO (PRUD_ID, F_CREACION, USU_CREACION, C_CODIGO, D_DESCRIPCION, N_VERSION) VALUES (S_FOR_PRUEBAS_PEDRO_ROMERO.NEXTVAL, SYSDATE, (select USER FROM DUAL), 'P3', 'Prueba 3', 1);
 
 
 
 
 
 
 
 
 
 
 






SPOOL OFF;
