rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/016_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.16.0 --
--------------------


ALTER TABLE GE_CFG_TAREAS   ADD ( 
	L_CAMBIO_AUT_TRAMITE NUMBER(1, 0) DEFAULT 0 NOT NULL,
	CFGTAR_RESP_CAMBIO_AUT_ID NUMBER(19, 0)
);

ALTER TABLE GE_CFG_TAREAS_H ADD ( 
	L_CAMBIO_AUT_TRAMITE NUMBER(1, 0),
	CFGTAR_RESP_CAMBIO_AUT_ID NUMBER(19, 0)
);


ALTER TABLE GE_TIPO_TRAMITE ADD (D_SUBSITUACION VARCHAR2(50 CHAR));
ALTER TABLE GE_TIPO_TRAMITE_H ADD (D_SUBSITUACION VARCHAR2(50 CHAR));

-- ------------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD (CFG_VALDOM_SERIERESREC_ID NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD (CFG_VALDOM_SERIERESREC_ID NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD (CFG_VALDOM_TIPRESREC_ID NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD (CFG_VALDOM_TIPRESREC_ID NUMBER(19,0));

-- ------------------

ALTER TABLE GE_TIPO_TRAMITE ADD (L_SUBSITUACION_SUP NUMBER(1,0));
ALTER TABLE GE_TIPO_TRAMITE_H ADD (L_SUBSITUACION_SUP NUMBER(1,0));

---------------------------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD (N_DIASFINALIZACION NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD (N_DIASFINALIZACION NUMBER(19,0));

CREATE TABLE GE_LOG_CRON (LOG_CRON_ID NUMBER(19,0) NOT NULL, F_FECHA TIMESTAMP, D_PROCESO VARCHAR2(50 CHAR), D_LOG VARCHAR2(250 CHAR));

-- ------------------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD (DETEXPTRAM_VDOM_ACTREC_ID NUMBER(19,0));
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD (DETEXPTRAM_VDOM_ACTREC_ID NUMBER(19,0));

ALTER TABLE GE_CFG_METADATOS_TRAM ADD (D_ACTO_REC VARCHAR2(50 CHAR));
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_ACTO_REC VARCHAR2(50 CHAR));

-- ------------------

ALTER TABLE GE_AGRUP_DOCUMENTOS   ADD (L_VINCULADO NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE GE_AGRUP_DOCUMENTOS_H ADD (L_VINCULADO NUMBER(1,0));

ALTER TABLE GE_TIPO_TRAMITE   ADD (L_TRAT_VINCULADOS NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE GE_TIPO_TRAMITE_H ADD (L_TRAT_VINCULADOS NUMBER(1,0));

-- ------------------

ALTER TABLE GE_CFG_TAREAS   ADD ( 
	D_CIERRE_AUTO_TRAMITE VARCHAR2(50 CHAR)
);

ALTER TABLE GE_CFG_TAREAS_H ADD ( 
	D_CIERRE_AUTO_TRAMITE VARCHAR2(50 CHAR)
);

-------------------

ALTER TABLE GE_SITUACIONES_EXPEDIENTES ADD (L_NO_SUPERVISADA NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE GE_SITUACIONES_EXPEDIENTES_H ADD (L_NO_SUPERVISADA NUMBER(1,0) DEFAULT 0 NULL);



------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD (N_DIASALEGACIONES NUMBER(19,0));
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD (N_DIASALEGACIONES NUMBER(19,0));
COMMENT ON COLUMN GE_CFG_TIPOEXPEDIENTE.N_DIASALEGACIONES IS 'Indica el valor del número de días que deben transcurrir esperando alegaciones del sujeto obligado en los trámites de un expediente sancionador.';


ALTER TABLE GE_CFG_TAREAS ADD (L_CIERRE_SUBTRA NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE GE_CFG_TAREAS_H ADD (L_CIERRE_SUBTRA NUMBER(1,0) DEFAULT 0 NULL);

-- -----------------

ALTER TABLE GE_CFG_TAREAS   ADD ( 
	D_PLAZO_REFERENCIA VARCHAR2(15 CHAR),
	N_DIAS_PLAZO_REFERENCIA NUMBER(4, 0) DEFAULT 0 NOT NULL
);

ALTER TABLE GE_CFG_TAREAS_H ADD ( 
	D_PLAZO_REFERENCIA VARCHAR2(15 CHAR),
	N_DIAS_PLAZO_REFERENCIA NUMBER(4, 0) DEFAULT 0 NOT NULL
);

ALTER TABLE GE_TAREAS_EXPEDIENTE   ADD ( 
	D_PLAZO_REFERENCIA VARCHAR2(15 CHAR)
);

ALTER TABLE GE_TAREAS_EXPEDIENTE_H ADD ( 
	D_PLAZO_REFERENCIA VARCHAR2(15 CHAR)
);

-- ----------------

ALTER TABLE GE_PERSONAS_EXPEDIENTES ADD (L_INTERESADO NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE GE_PERSONAS_EXPEDIENTES_H ADD (L_INTERESADO NUMBER(1,0) DEFAULT 0 NULL);

-- ----------------

ALTER TABLE GE_CFG_METADATOS_TRAM   ADD (D_BT_EMPUJAR_DOC VARCHAR2(50) DEFAULT 'Enviar Documentos');
ALTER TABLE GE_CFG_METADATOS_TRAM_H ADD (D_BT_EMPUJAR_DOC VARCHAR2(50));

-----------------------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD CFGTIPOEXP_RESPTRAMITACION_ID NUMBER(19,0);
ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD CFGTIPOEXP_PERSONAS_ID NUMBER(19,0);
ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD CFGTIPOEXP_SUJETOSOBLIGADOS_ID NUMBER(19,0);

COMMENT ON COLUMN GE_CFG_TIPOEXPEDIENTE.CFGTIPOEXP_RESPTRAMITACION_ID IS 'Indica el responsable por defecto a presentar preseleccionado en el combo de responsable cuando se da de alta un expediente nuevo.';
COMMENT ON COLUMN GE_CFG_TIPOEXPEDIENTE.CFGTIPOEXP_PERSONAS_ID IS 'Indica la persona a presentar asociada en el expediente al dar un alta nueva.';
COMMENT ON COLUMN GE_CFG_TIPOEXPEDIENTE.CFGTIPOEXP_SUJETOSOBLIGADOS_ID IS 'Indica el sujeto obligado a presentar asociado en el expediente al dar un alta nueva.';

ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD CFGTIPOEXP_RESPTRAMITACION_ID NUMBER(19,0);
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD CFGTIPOEXP_PERSONAS_ID NUMBER(19,0);
ALTER TABLE GE_CFG_TIPOEXPEDIENTE_H ADD CFGTIPOEXP_SUJETOSOBLIGADOS_ID NUMBER(19,0);





SPOOL OFF;
