rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/016_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

--------------------
-- VERSION 0.16.0 --
--------------------


ALTER TABLE GE_CFG_TAREAS ADD CONSTRAINT CFGTAR_RESP_CAMBIO_AUT_FK FOREIGN KEY (CFGTAR_RESP_CAMBIO_AUT_ID)  REFERENCES GE_RESP_TRAMITACION;

-- ----------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD CONSTRAINT GE_VALDOM_SERIERESREC_ID_FK FOREIGN KEY (CFG_VALDOM_SERIERESREC_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD CONSTRAINT GE_CFG_VALDOM_TIPRESREC_ID_FK FOREIGN KEY (CFG_VALDOM_TIPRESREC_ID) REFERENCES GE_VALORES_DOMINIOS;

-- ----------

ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD CONSTRAINT GE_DETEXPTRAM_VDOM_ACTREC_FK FOREIGN KEY (DETEXPTRAM_VDOM_ACTREC_ID) REFERENCES GE_VALORES_DOMINIOS;

---------------------------

ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD CONSTRAINT GE_CFGTIPOEXP_RESPTRAMITACION_ID_FK FOREIGN KEY (CFGTIPOEXP_RESPTRAMITACION_ID) REFERENCES GE_RESP_TRAMITACION;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD CONSTRAINT GE_CFGTIPOEXP_PERSONAS_ID_FK FOREIGN KEY (CFGTIPOEXP_PERSONAS_ID) REFERENCES GE_PERSONAS;
ALTER TABLE GE_CFG_TIPOEXPEDIENTE ADD CONSTRAINT GE_CFGTIPOEXP_SUJETOSOBLIGADOS_ID_FK FOREIGN KEY (CFGTIPOEXP_SUJETOSOBLIGADOS_ID) REFERENCES GE_SUJETOS_OBLIGADOS;

SPOOL OFF;
