rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;



DROP TABLE GE_CFG_EXPED_TRAMITE CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_EXPED_TRAMITE_H CASCADE CONSTRAINTS;

DROP TABLE GE_CFG_EXPED_SUBTRAM CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_EXPED_SUBTRAM_H CASCADE CONSTRAINTS;

DROP TABLE GE_TRAMITE_EXPED CASCADE CONSTRAINTS;
DROP TABLE GE_TRAMITE_EXPED_H CASCADE CONSTRAINTS;

DROP TABLE GE_TIPO_TRAMITE CASCADE CONSTRAINTS;
DROP TABLE GE_TIPO_TRAMITE_H CASCADE CONSTRAINTS;

DROP TABLE GE_TIPOS_DOCUMENTOS CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOS_DOCUMENTOS_H CASCADE CONSTRAINTS;

DROP TABLE GE_CFG_DOC_EXPED_TRAM CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_DOC_EXPED_TRAM_H CASCADE CONSTRAINTS;

DROP TABLE GE_PLANTILLAS CASCADE CONSTRAINTS;
DROP TABLE GE_PLANTILLAS_H  CASCADE CONSTRAINTS;

DROP TABLE GE_PLANTILLA_DOC CASCADE CONSTRAINTS;
DROP TABLE GE_PLANTILLA_DOC_H CASCADE CONSTRAINTS;

DROP TABLE GE_TIPOS_METADATOS_ENI CASCADE CONSTRAINTS;
DROP TABLE GE_TIPOS_METADATOS_ENI_H CASCADE CONSTRAINTS;

DROP TABLE GE_VALORES_META_ENI CASCADE CONSTRAINTS;
DROP TABLE GE_VALORES_META_ENI_H CASCADE CONSTRAINTS;

DROP TABLE GE_DOCUMENTOS CASCADE CONSTRAINTS;
DROP TABLE GE_DOCUMENTOS_H CASCADE CONSTRAINTS;

DROP TABLE GE_DOCUMENTOS_EXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_DOCUMENTOS_EXPEDIENTES_H CASCADE CONSTRAINTS;

DROP TABLE GE_AGRUP_EXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_AGRUP_EXPEDIENTES_H CASCADE CONSTRAINTS;

DROP TABLE GE_AGRUP_DOCUMENTOS CASCADE CONSTRAINTS;
DROP TABLE GE_AGRUP_DOCUMENTOS_H CASCADE CONSTRAINTS;

DROP TABLE GE_METADATOS_DOCUMENTOS CASCADE CONSTRAINTS;      
DROP TABLE GE_METADATOS_DOCUMENTOS_H CASCADE CONSTRAINTS;

DROP TABLE GE_METADATOS_EXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_METADATOS_EXPEDIENTES_H CASCADE CONSTRAINTS;


ALTER TABLE GE_PERMISOS  MODIFY (C_CODIGO VARCHAR2(20 CHAR) ); 
ALTER TABLE GE_PERMISOS_H  MODIFY (C_CODIGO VARCHAR2(20 CHAR) );

DROP TABLE GE_SITUACIONES_EXPEDIENTES CASCADE CONSTRAINTS;
DROP TABLE GE_SITUACIONES_EXPEDIENTES_H CASCADE CONSTRAINTS;

ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN TRAM_EXP_TRAMEXPSUP_ID;
ALTER TABLE GE_TRAMITE_EXPED ADD (TRAM_EXP_TRAMEXPSUP_ID NUMBER(19,0) NOT NULL);

ALTER TABLE GE_USUARIOS  MODIFY (T_CONTRASENYA VARCHAR2(50 CHAR) ); 

SPOOL OFF;
