rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_UNDO_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


DROP SEQUENCE S_TIPO_TRAMITE;
DROP SEQUENCE S_CFG_EXPED_TRAMITE;
DROP SEQUENCE S_CFG_EXPED_SUBTRAM;
DROP SEQUENCE S_TRAMITE_EXPED;

DROP SEQUENCE S_TIPOS_DOCUMENTOS;
DROP SEQUENCE S_CFG_DOC_EXPED_TRAM;
DROP SEQUENCE S_PLANTILLAS;
DROP SEQUENCE S_PLANTILLA_DOC;
DROP SEQUENCE S_TIPOS_METADATOS_ENI;
DROP SEQUENCE S_VALORES_META_ENI;
DROP SEQUENCE S_DOCUMENTOS;
DROP SEQUENCE S_DOCUMENTOS_EXPEDIENTES;
DROP SEQUENCE S_AGRUP_EXPEDIENTES;
DROP SEQUENCE S_AGRUP_DOCUMENTOS;
DROP SEQUENCE S_METADATOS_DOCUMENTOS;
DROP SEQUENCE S_METADATOS_EXPEDIENTES;

DROP SEQUENCE S_SITUACIONES_EXPEDIENTES;



SPOOL OFF;
