rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_UNDO_03_INDICES.LOG

ALTER TABLE GE_TRAMITE_EXPED_H DROP CONSTRAINT GE_TRAMITE_EXPED_H_PK;
ALTER TABLE GE_TRAMITE_EXPED_H  ADD CONSTRAINT GE_TRAMITE_EXPED_H_PK PRIMARY KEY (TRAM_EXP_ID) USING INDEX TABLESPACE GESTOR_IND;

SPOOL OFF;
