rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_UNDO_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_TRAMITE_EXPED ADD CONSTRAINT GE_TRAM_EXP_TRAMEXPSUP_FK FOREIGN KEY (TRAM_EXP_TRAMEXPSUP_ID) REFERENCES GE_TRAMITE_EXPED  (TRAM_EXP_ID) ENABLE;

SPOOL OFF;
