rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

alter table GE_EXPEDIENTES disable constraint "GE_EXP_VALDOM_SIT_FK";
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SIT');

INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'FN','Finalizada','FN',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'AC','Acumulada','AC',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'AN','Anulada','AN',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'PA','Pendiente Decisión Admisión','PA',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'PR','Pendiente Resolución','PR',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'TR','Trasladada','TR',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'ERR','Errónea','ERR',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'PI','Pendiente Acuerdo Inicio','PI',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'PP','Pendiente Informe API','PP',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'PPR','Pendiente Propuesta Resolución','PPR',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'PX','Pendiente Archivo sin API','PX',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);
INSERT INTO GE_VALORES_DOMINIOS (VAL_DOM_ID, VALDOM_DOM_ID, C_CODIGO, D_DESCRIPCION,T_ABREVIATURA, N_NIVEL_ANIDAMIENTO, N_ORDEN, VALDOM_VALDOM_ID, L_BLOQUEADO, L_ACTIVO, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_VALORES_DOMINIOS.NEXTVAL,(SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones'),'IE','Inicio Expediente','IE',0,0,(SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE D_DESCRIPCION = '' AND VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE D_DESCRIPCION = 'Situaciones')),0,1,SYSDATE, (SELECT USER FROM DUAL), 0);

alter table GE_EXPEDIENTES enable constraint "GE_EXP_VALDOM_SIT_FK";


DELETE FROM GE_PERMISOS_PERFILES;
DELETE FROM GE_PERMISOS;

-- se añade aquí porque no se puede modificar con descripciones mayores
ALTER TABLE GE_PERMISOS  MODIFY (D_DESCRIPCION VARCHAR2(50 CHAR) ); 
ALTER TABLE GE_PERMISOS_H MODIFY (D_DESCRIPCION VARCHAR2(50 CHAR) );

-- ---------------------------------
-- Series para documentos
-- ---------------------------------

DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'RES' AND T_DESCRIPCION = 'Resolución';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'ACU' AND T_DESCRIPCION = 'Acuerdo';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'CON' AND T_DESCRIPCION = 'Contrato';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'CNV' AND T_DESCRIPCION = 'Convenio';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'DEC' AND T_DESCRIPCION = 'Declaración';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'COM' AND T_DESCRIPCION = 'Comunicación';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'NOT' AND T_DESCRIPCION = 'Notificación';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'PUB' AND T_DESCRIPCION = 'Publicación';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'ACR' AND T_DESCRIPCION = 'Acuse de recibo';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'ACT' AND T_DESCRIPCION = 'Acta';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'CER' AND T_DESCRIPCION = 'Certificado';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'DIL' AND T_DESCRIPCION = 'Diligencia';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'INF' AND T_DESCRIPCION = 'Informe';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'SOL' AND T_DESCRIPCION = 'Solicitud';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'DEN' AND T_DESCRIPCION = 'Denuncia';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'ALE' AND T_DESCRIPCION = 'Alegación';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'REC' AND T_DESCRIPCION = 'Recurso';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'COC' AND T_DESCRIPCION = 'Comunicación Ciudadano';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'FAC' AND T_DESCRIPCION = 'Factura';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'OTI' AND T_DESCRIPCION = 'Otros incautados';
DELETE FROM GE_ELEMENTOS_SERIES WHERE T_TIPO = 'OTR' AND T_DESCRIPCION = 'Otros';

DELETE FROM GE_SERIES WHERE T_CODIGO_SERIE = 'DOCGRAL';

DELETE FROM GE_PARAMETROS WHERE T_CAMPO = 'extensionesDoc';


DELETE FROM GE_PERMISOS_PERFILES WHERE PERMPERF_PERM_ID IN 
	(SELECT PER_ID FROM GE_PERMISOS WHERE C_CODIGO IN ('CONS_EXPDOC','EDIT_EXPDOC','DESAC_EXPDOC','NEW_EXPDOCTRAB','EDIT_EXPDOCCONF'));
DELETE FROM GE_PERMISOS WHERE C_CODIGO IN ('CONS_EXPDOC','EDIT_EXPDOC','DESAC_EXPDOC','NEW_EXPDOCTRAB','EDIT_EXPDOCCONF');


DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXPACT');
DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXPTAREADET');
DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXPPLAZODET');
DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXPFINTRAM');
DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'DESAC_EXPTRAM');

DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'NEW_EXPACT';
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'NEW_EXPTAREADET';
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'NEW_EXPPLAZODET';
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'NEW_EXPFINTRAM';
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'DESAC_EXPTRAM';


SPOOL OFF;
