rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/008_UNDO_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;


DROP SEQUENCE S_RESP_TRAMITACION    ;
DROP SEQUENCE S_USUARIO_RESP        ;
DROP SEQUENCE S_CFG_TAREAS          ;
DROP SEQUENCE S_TAREAS_EXPEDIENTE   ;
DROP SEQUENCE S_CFG_TAREAS_SIGUIENTE;



SPOOL OFF;
