rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/008_UNDO_07_VISTAS.LOG
ALTER SESSION SET _ORACLE_SCRIPT= TRUE;

CREATE OR REPLACE FORCE VIEW GE_EXP_PEREXP_SUJEXP (EXP_ID, F_CREACION, F_MODIFICACION, USU_CREACION, USU_MODIFICACION, F_FECHA_REGISTRO, T_TIP_EXP, T_NUM_EXPEDIENTE, T_SITUACION, T_FECHA_ENTRADA, T_PERSONA, T_SUJETO_OBLIGADO) AS 
SELECT 
	expe.EXP_ID AS EXP_ID,
	expe.F_CREACION AS F_CREACION,
	expe.F_MODIFICACION AS F_MODIFICACION,
	expe.USU_CREACION AS USU_CREACION,
	expe.USU_MODIFICACION AS USU_MODIFICACION,
	expe.F_FECHA_REGISTRO AS F_FECHA_REGISTRO,
	valortipoexp.T_ABREVIATURA AS T_TIP_EXP,
	expe.T_NUMERO_EXPEDIENTE AS T_NUM_EXPEDIENTE,
	valorsituacion.D_DESCRIPCION AS T_SITUACION,
	expe.F_FECHA_ENTRADA AS T_FECHA_ENTRADA,
	CONCAT(CONCAT(CONCAT(CONCAT(persona.T_NOMBRE_RAZONSOCIAL, ' '),persona.T_PRIMER_APELLIDO), ' '), persona.T_SEGUNDO_APELLIDO)AS T_PERSONA,
	sujetoobligado.D_DESCRIPCION AS T_SUJETO_OBLIGADO
FROM GE_EXPEDIENTES expe
	INNER JOIN GE_VALORES_DOMINIOS valortipoexp ON valortipoexp.VAL_DOM_ID = expe.EXP_VALDOM_TIPEXP_ID 
	INNER JOIN GE_VALORES_DOMINIOS valorsituacion ON valorsituacion.VAL_DOM_ID = expe.EXP_VALDOM_SIT_ID 
	INNER JOIN GE_PERSONAS_EXPEDIENTES perexpe ON  perexpe.PER_EXP_ID=expe.EXP_ID
	INNER JOIN GE_SUJETOS_OBLIGADOS_EXPDT sujetoexpe ON sujetoexpe.SUJ_EXP_ID=expe.EXP_ID
	INNER JOIN GE_PERSONAS persona ON persona.PER_ID =perexpe.PER_PER_ID 
	INNER JOIN GE_SUJETOS_OBLIGADOS sujetoobligado ON sujetoobligado.SUJ_ID = sujetoexpe.SUJ_SUJ_ID 
WHERE perexpe.N_PRINCIPAL =1 AND sujetoexpe.N_PRINCIPAL =1;



-- Añadimos las columnas D.T_IDEN_DOC y T_NOMBRE_FICHERO
CREATE OR REPLACE VIEW GE_LISTADO_DOCUMENTOS_EXP (DOCEXP_ID, DOC_ID, EXP_ID, TRAM_EXP_ID, T_IDEN_DOC, D_DESCRIPCION, D_DESC_ABREV, T_NOMBRE_FICHERO, T_EXTENSION_FICHERO, TIP_DOC_ID, D_DESCRIPCION_TIPO, F_CREACION, F_MODIFICACION, USU_CREACION, USU_MODIFICACION, N_ORDEN, T_DOC_TRABAJO, L_EDITABLE, L_FIRMADO, L_SELLADO, L_ANONIMIZADO, L_ANONIMIZADO_PARCIAL, L_ACTIVO) AS
	SELECT
		DE.DOCEXP_ID AS DOCEXP_ID,
		DE.DOCEXP_DOC_ID AS DOC_ID,
		DE.DOCEXP_EXP_ID AS EXP_ID,
		DE.DOCEXP_TRAM_EXP_ID AS TRAM_EXP_ID,
		D.T_IDEN_DOC AS T_IDEN_DOC,
		DE.D_DESCRIPCION_DOC AS D_DESCRIPCION,
		DE.D_DESC_ABREV_DOC AS D_DESC_ABREV,
		D.T_NOMBRE_FICHERO AS T_NOMBRE_FICHERO,
		D.T_EXTENSION_FICHERO AS T_EXTENSION_FICHERO,
		TD.TIP_DOC_ID AS TIP_DOC_ID,
		TD.D_DESCRIPCION AS D_DESCRIPCION_TIPO,
		D.F_CREACION AS F_CREACION,
		D.F_MODIFICACION AS F_MODIFICACION,
		D.USU_CREACION AS USU_CREACION,
		D.USU_MODIFICACION AS USU_MODIFICACION,
		DE.N_ORDEN AS N_ORDEN,
		DE.T_DOC_TRABAJO AS T_DOC_TRABAJO,
		D.L_EDITABLE AS L_EDITABLE,
		D.L_FIRMADO AS L_FIRMADO,
		D.L_SELLADO AS L_SELLADO,
		D.L_ANONIMIZADO AS L_ANONIMIZADO,
		D.L_ANONIMIZADO_PARCIAL AS L_ANONIMIZADO_PARCIAL,
		D.L_ACTIVO AS L_ACTIVO
	FROM GE_DOCUMENTOS_EXPEDIENTES DE 
		INNER JOIN GE_DOCUMENTOS D ON DE.DOCEXP_DOC_ID = D.DOC_ID
		INNER JOIN GE_TIPOS_DOCUMENTOS TD ON D.DOC_TIPDOC_ID = TD.TIP_DOC_ID
	WHERE DE.L_ACTIVO = 1 AND D.L_ACTIVO = 1;


CREATE OR REPLACE VIEW GE_LISTADO_DOCUMENTOS_EXP_TRAM AS
	SELECT
		DE.*,
		DET.DETR_TRAMEXP_ID AS TRAM_EXPE_ID
	FROM GE_LISTADO_DOCUMENTOS_EXP DE 
		INNER JOIN GE_DOCUMENTOS_EXPED_TRAMITES DET ON DE.DOCEXP_ID = DET.DETR_DOCEXP_ID
	;


SPOOL OFF;