ALTER TABLE GE_TIPO_TRAMITE ADD (L_ALTA_MASIVA NUMBER(1,0) DEFAULT 0 NOT NULL); 
ALTER TABLE GE_TIPO_TRAMITE_H ADD (L_ALTA_MASIVA NUMBER(1,0) DEFAULT 0 NOT NULL); 
COMMENT ON COLUMN GE_TIPO_TRAMITE.L_ALTA_MASIVA IS 'Indica que el alta masiva del subtramite asociado';

UPDATE GE_TIPO_TRAMITE SET L_ALTA_MASIVA = 1 WHERE T_CODIGO IN ('FIRM','NOT'); 
INSERT INTO GE_PERMISOS (PER_ID,F_CREACION,F_MODIFICACION,USU_CREACION,USU_MODIFICACION,L_ACTIVA,C_CODIGO,D_DESCRIPCION,N_VERSION) VALUES (S_PERMISOS.NEXTVAL,SYSDATE,NULL,(SELECT USER FROM DUAL),NULL,'1','NEW_ALTAMASIVASUBTR','Nuevo paquete de trabajo para el alta masiva de subtramites','1');
INSERT INTO GE_PERMISOS_PERFILES (PERM_PERF_ID, PERMPERF_PERF_ID, PERMPERF_PERM_ID, L_ACTIVA, F_CREACION, USU_CREACION, N_VERSION) VALUES (S_PERMISOS_PERFILES.NEXTVAL, (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN'),(SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_ALTAMASIVASUBTR'),1,SYSDATE, (SELECT USER FROM DUAL), 0);