CREATE TABLE GE_TIPO_TRAMITE_DFR AS SELECT * FROM GE_TIPO_TRAMITE;

CREATE TABLE GE_TIPO_TRAMITE_DFR_H AS SELECT * FROM GE_TIPO_TRAMITE_H;

ALTER TABLE GE_TIPO_TRAMITE_DFR ADD L_ESPERA_DOC NUMBER(1,0) DEFAULT 0 NOT NULL;

UPDATE GE_TIPO_TRAMITE_DFR SET L_ESPERA_DOC = 1 WHERE T_CODIGO IN ('TRDPD', 'SUB', 'REQINF', 'PETINFRTE', 'PETINFTER', 'REQCUMPL', 'RREQCUMPL', 'RREQINF', 'TRREC');