rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/009_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.9.0 --
-------------------

DROP TABLE GE_DATOS_TMP_USUARIO;

DROP TABLE GE_MATERIAS_EXPDT;
DROP TABLE GE_MATERIAS_EXPDT_H;

ALTER TABLE GE_EXPEDIENTES ADD (EXP_VALDOM_MAT_ID NUMBER(19,0));
ALTER TABLE GE_EXPEDIENTES_H ADD (EXP_VALDOM_MAT_ID NUMBER(19,0));

ALTER TABLE GE_SUJETOS_OBLIGADOS DROP COLUMN T_PUESTO_TITULAR;
ALTER TABLE GE_SUJETOS_OBLIGADOS DROP COLUMN L_UNIDAD_TRANSPARENCIA;
ALTER TABLE GE_SUJETOS_OBLIGADOS DROP COLUMN T_CONTACT_UNIDAD_TRANSPARENCIA;
ALTER TABLE GE_SUJETOS_OBLIGADOS DROP COLUMN L_DPD;
ALTER TABLE GE_SUJETOS_OBLIGADOS DROP COLUMN T_CONTACTO_DPD;

ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP COLUMN T_PUESTO_TITULAR;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP COLUMN L_UNIDAD_TRANSPARENCIA;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP COLUMN T_CONTACT_UNIDAD_TRANSPARENCIA;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP COLUMN L_DPD;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP COLUMN T_CONTACTO_DPD;

ALTER TABLE GE_SUJETOS_OBLIGADOS DROP COLUMN L_ERRONEO;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP COLUMN L_ERRONEO;


ALTER TABLE GE_TAREAS_EXPEDIENTE   DROP ( T_INDICACIONES_SIG  );

ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN TRAM_EXP_USU_FIN_ID;
ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN F_FECHA_FIN_REAL;
ALTER TABLE GE_TRAMITE_EXPED DROP COLUMN F_FECHA_FIN;

ALTER TABLE GE_TRAMITE_EXPED_H DROP COLUMN TRAM_EXP_USU_FIN_ID;
ALTER TABLE GE_TRAMITE_EXPED_H DROP COLUMN F_FECHA_FIN_REAL;
ALTER TABLE GE_TRAMITE_EXPED_H DROP COLUMN F_FECHA_FIN;


SPOOL OFF;
