rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/009_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.9.0 --
-------------------
UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = null, D_IDENTIF_INTERESADO = null, D_CANAL_SALIDA = null,D_DATOS_CANAL_SALIDA = null, D_NOTIF_INFRUCTUOSA = null
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'SUB') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');

UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = null, D_IDENTIF_INTERESADO = null,D_CANAL_SALIDA = null,D_DATOS_CANAL_SALIDA = null, D_NOTIF_INFRUCTUOSA = null
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'SUB') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');
------------------------------

UPDATE GE_CFG_METADATOS_TRAM SET D_FECHA_LIMITE = 'Fecha limite' WHERE D_FECHA_LIMITE IS NOT NULL;

-------------------
-- Configuración plazos para notificación en subsanación
-------------------


DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID = (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA') AND C_CODIGO = 'NOT';

DELETE FROM GE_CFG_PLAZOS_AUT WHERE 
PLAAUT_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'SUB')
AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'NOT' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_PLA'))
AND PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'RCO' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_EXP'))
AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'DN' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_PLA_TEMP')),'C')
AND V_TIPO_ACCION = 'C';


DELETE FROM GE_CFG_PLAZOS_AUT WHERE 
PLAAUT_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'SUB')
AND PLAAUT_VALDOM_PLAZO_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'NOT' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_PLA'))
AND PLAAUT_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'RCE' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_EXP'))
AND PLAAUT_VALDOM_TIPPLA_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE C_CODIGO = 'DN' AND valdom_dom_id = (SELECT DOM_ID FROM ge_dominios WHERE C_CODIGO = 'TIP_PLA_TEMP')),'C')
AND V_TIPO_ACCION = 'C';

-------------------------------
UPDATE GE_CFG_METADATOS_TRAM SET D_FECHA_FIRMA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'FIRM') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');


UPDATE GE_CFG_METADATOS_TRAM SET D_FECHA_FIRMA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'FIRM') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');

UPDATE GE_CFG_METADATOS_TRAM SET D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL,
D_NOTIF_INFRUCTUOSA = NULL, D_FECHA_RESPUESTA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'REQINF') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');

UPDATE GE_CFG_METADATOS_TRAM SET D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL,
D_NOTIF_INFRUCTUOSA = NULL, D_FECHA_RESPUESTA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'REQINF') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');

DELETE FROM GE_CFG_METADATOS_TRAM  WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCO')
AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'GDOC');

DELETE FROM GE_CFG_METADATOS_TRAM  WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCE')
AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'GDOC');

UPDATE GE_CFG_METADATOS_TRAM SET D_FECHA_INFORME = NULL, D_FECHA_FIRMA = NULL , D_FECHA_ENVIO = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'ACADM') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');

UPDATE GE_CFG_METADATOS_TRAM SET D_FECHA_INFORME = NULL, D_FECHA_FIRMA = NULL, D_FECHA_ENVIO = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'ACADM') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');


DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'EDIT_EXPTIPODOC');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'EDIT_EXPTIPODOC';


UPDATE GE_SERIES SET T_PATRON = 'RCO-2022-{4}', N_NUMERO_FINAL = 9999 WHERE T_PATRON = 'RCO-2022/{3}';
UPDATE GE_SERIES SET T_PATRON = 'RCO-2021-{4}', N_NUMERO_FINAL = 9999 WHERE T_PATRON = 'RCO-2021/{3}';
UPDATE GE_SERIES SET T_PATRON = 'RCE-2022-{4}', N_NUMERO_FINAL = 9999 WHERE T_PATRON = 'RCE-2022/{3}';
UPDATE GE_SERIES SET T_PATRON = 'RCE-2021-{4}', N_NUMERO_FINAL = 9999 WHERE T_PATRON = 'RCE-2021/{3}';


UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = NULL, D_IDENTIF_INTERESADO = NULL, D_FECHA_FIRMA = NULL,
D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL, D_NOTIF_INFRUCTUOSA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'REQAVIS') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');

UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = NULL, D_IDENTIF_INTERESADO = NULL, D_FECHA_FIRMA = NULL,
D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL, D_NOTIF_INFRUCTUOSA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'REQAVIS') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');

UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = NULL, D_IDENTIF_INTERESADO = NULL, D_FECHA_FIRMA = NULL,
D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL, D_NOTIF_INFRUCTUOSA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'REQCUMPL') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');

UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = NULL, D_IDENTIF_INTERESADO = NULL, D_FECHA_FIRMA = NULL,
D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL, D_NOTIF_INFRUCTUOSA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'REQCUMPL') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');

UPDATE GE_TIPO_TRAMITE set T_COMPORTAMIENTO = 'C004' WHERE T_CODIGO = 'TRDPD';


UPDATE GE_CFG_METADATOS_TRAM SET D_AFECTA_PLAZOS = '', D_FECHA_LIMITE = '', D_FECHA_RESPUESTA = '', D_NOTIF_INFRUCTUOSA = '', D_PLAZO = '', D_TIPO_PLAZO = '', D_FECHA_NOTIFICACION = ''
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'TRDPD') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');


UPDATE GE_CFG_METADATOS_TRAM SET D_AFECTA_PLAZOS = '', D_FECHA_LIMITE = '', D_FECHA_RESPUESTA = '', D_NOTIF_INFRUCTUOSA = '', D_PLAZO = '', D_TIPO_PLAZO = '', D_FECHA_NOTIFICACION = ''
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'TRDPD') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'LIST_TAREASEXP');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'LIST_TAREASEXP';

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'ERRO_SUJOBL');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'ERRO_SUJOBL';

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'MODSITFINAL');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'MODSITFINAL';


SPOOL OFF;
