rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_02_SECUENCIAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-------------------
-- VERSION 0.6.0 --
-------------------
CREATE SEQUENCE S_SITUACIONES_EXPEDIENTES START WITH 1 INCREMENT BY 1;


CREATE SEQUENCE S_TIPO_TRAMITE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_CFG_EXPED_TRAMITE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_CFG_EXPED_SUBTRAM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_TRAMITE_EXPED START WITH 1 INCREMENT BY 1;


CREATE SEQUENCE S_TIPOS_DOCUMENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_CFG_DOC_EXPED_TRAM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_PLANTILLAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_PLANTILLA_DOC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_TIPOS_METADATOS_ENI START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_VALORES_META_ENI START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_DOCUMENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_DOCUMENTOS_EXPEDIENTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_AGRUP_EXPEDIENTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_AGRUP_DOCUMENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_METADATOS_DOCUMENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE S_METADATOS_EXPEDIENTES START WITH 1 INCREMENT BY 1;



SPOOL OFF;
