rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_03_INDICES.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_SITUACIONES_EXPEDIENTES ADD CONSTRAINT GE_SITUACION_EXPEDIENTES_PK PRIMARY KEY (SIT_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_SITUACIONES_EXPEDIENTES_H ADD CONSTRAINT GE_SITUACION_EXPEDIENTES_H_PK PRIMARY KEY (SIT_ID, REV) USING INDEX TABLESPACE GESTOR_IND;


ALTER TABLE GE_TIPO_TRAMITE    ADD CONSTRAINT GE_TIPO_TRAMITE_PK   PRIMARY KEY (TIP_TRA_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TIPO_TRAMITE_H  ADD CONSTRAINT GE_TIPO_TRAMITE_H_PK PRIMARY KEY (TIP_TRA_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_CFG_EXPED_TRAMITE    ADD CONSTRAINT GE_CFG_EXPED_TRAMITE_PK   PRIMARY KEY (CFG_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_CFG_EXPED_TRAMITE_H  ADD CONSTRAINT GE_CFG_EXPED_TRAMITE_H_PK PRIMARY KEY (CFG_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_CFG_EXPED_SUBTRAM    ADD CONSTRAINT GE_CFG_EXPED_SUBTRAM_PK   PRIMARY KEY (CFG_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_CFG_EXPED_SUBTRAM_H  ADD CONSTRAINT GE_CFG_EXPED_SUBTRAM_H_PK PRIMARY KEY (CFG_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_TRAMITE_EXPED    ADD CONSTRAINT GE_TRAMITE_EXPED_PK   PRIMARY KEY (TRAM_EXP_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TRAMITE_EXPED_H  ADD CONSTRAINT GE_TRAMITE_EXPED_H_PK PRIMARY KEY (TRAM_EXP_ID) USING INDEX TABLESPACE GESTOR_IND;


ALTER TABLE GE_PLANTILLAS   ADD CONSTRAINT GE_PLANTILLAS_PK   PRIMARY KEY (PLA_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PLANTILLAS_H ADD CONSTRAINT GE_PLANTILLAS_H_PK PRIMARY KEY (PLA_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_PLANTILLA_DOC   ADD CONSTRAINT GE_PLANTILLA_DOC_PK    PRIMARY KEY (PLDOC_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_PLANTILLA_DOC_H ADD CONSTRAINT GE_PLANTILLA_DOC_H_PK  PRIMARY KEY (PLDOC_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_TIPOS_DOCUMENTOS   ADD CONSTRAINT GE_TIPOS_DOCUMENTOS_PK   PRIMARY KEY (TIP_DOC_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TIPOS_DOCUMENTOS_H ADD CONSTRAINT GE_TIPOS_DOCUMENTOS_H_PK PRIMARY KEY (TIP_DOC_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_TIPOS_METADATOS_ENI   ADD CONSTRAINT GE_TIPOS_METADATOS_ENI_PK   PRIMARY KEY (TMETENI_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_TIPOS_METADATOS_ENI_H ADD CONSTRAINT GE_TIPOS_METADATOS_ENI_H_PK PRIMARY KEY (TMETENI_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_VALORES_META_ENI   ADD CONSTRAINT GE_VALORES_META_ENI_PK   PRIMARY KEY (VMETENI_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_VALORES_META_ENI_H ADD CONSTRAINT GE_VALORES_META_ENI_H_PK PRIMARY KEY (VMETENI_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_METADATOS_EXPEDIENTES   ADD CONSTRAINT GE_METADATOS_EXPEDIENTES_PK   PRIMARY KEY (MET_EXP_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_METADATOS_EXPEDIENTES_H ADD CONSTRAINT GE_METADATOS_EXPEDIENTES_H_PK PRIMARY KEY (MET_EXP_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_METADATOS_DOCUMENTOS   ADD CONSTRAINT GE_METADATOS_DOCUMENTOS_PK   PRIMARY KEY (MET_DOC_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_METADATOS_DOCUMENTOS_H ADD CONSTRAINT GE_METADATOS_DOCUMENTOS_H_PK PRIMARY KEY (MET_DOC_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_AGRUP_EXPEDIENTES   ADD CONSTRAINT GE_AGRUP_EXPEDIENTES_PK   PRIMARY KEY (AGREXP_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_AGRUP_EXPEDIENTES_H ADD CONSTRAINT GE_AGRUP_EXPEDIENTES_H_PK PRIMARY KEY (AGREXP_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_AGRUP_DOCUMENTOS   ADD CONSTRAINT GE_AGRUP_DOCUMENTOS_PK   PRIMARY KEY (AGRDOC_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_AGRUP_DOCUMENTOS_H ADD CONSTRAINT GE_AGRUP_DOCUMENTOS_H_PK PRIMARY KEY (AGRDOC_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_DOCUMENTOS   ADD CONSTRAINT GE_DOCUMENTOS_PK   PRIMARY KEY (DOC_ID)         USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_DOCUMENTOS_H ADD CONSTRAINT GE_DOCUMENTOS_H_PK PRIMARY KEY (DOC_ID, REV)    USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES   ADD CONSTRAINT GE_DOCUMENTOS_EXPEDIENTES_PK   PRIMARY KEY (DOCEXP_ID)      USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES_H ADD CONSTRAINT GE_DOCUMENTOS_EXPEDIENTES_H_PK PRIMARY KEY (DOCEXP_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_CFG_DOC_EXPED_TRAM   ADD CONSTRAINT GE_CFG_DOC_EXPED_TRAM_PK   PRIMARY KEY (CFG_DOC_ID) USING INDEX TABLESPACE GESTOR_IND;
ALTER TABLE GE_CFG_DOC_EXPED_TRAM_H ADD CONSTRAINT GE_CFG_DOC_EXPED_TRAM_H_PK PRIMARY KEY (CFG_DOC_ID) USING INDEX TABLESPACE GESTOR_IND;

ALTER TABLE GE_TRAMITE_EXPED_H DROP CONSTRAINT GE_TRAMITE_EXPED_H_PK;
ALTER TABLE GE_TRAMITE_EXPED_H  ADD CONSTRAINT GE_TRAMITE_EXPED_H_PK PRIMARY KEY (TRAM_EXP_ID, REV) USING INDEX TABLESPACE GESTOR_IND;

SPOOL OFF;