rem Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_04_CONSTRAINTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

ALTER TABLE GE_SITUACIONES_EXPEDIENTES ADD CONSTRAINT GE_SIT_SIT_SUPER_FK FOREIGN KEY (SIT_SIT_SUPER_ID) REFERENCES GE_SITUACIONES_EXPEDIENTES;
ALTER TABLE GE_SITUACIONES_EXPEDIENTES ADD CONSTRAINT GE_SIT_VALDOM_TIPEXP_FK FOREIGN KEY (SIT_VALDOM_TIPEXP_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_SITUACIONES_EXPEDIENTES ADD CONSTRAINT GE_SIT_VALDOM_SIT_FK FOREIGN KEY (SIT_VALDOM_SIT_ID) REFERENCES GE_VALORES_DOMINIOS;
ALTER TABLE GE_SITUACIONES_EXPEDIENTES_H ADD CONSTRAINT GE_SIT_EXP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;


ALTER TABLE GE_CFG_EXPED_TRAMITE ADD CONSTRAINT GE_CFG_VALDOM_TIPEXP_FK FOREIGN KEY (CFG_VALDOM_TIPEXP_ID) REFERENCES GE_VALORES_DOMINIOS (VAL_DOM_ID) ENABLE;
ALTER TABLE GE_CFG_EXPED_TRAMITE ADD CONSTRAINT GE_CFG_VALDOM_SIT_FK FOREIGN KEY (CFG_VALDOM_SIT_ID) REFERENCES GE_VALORES_DOMINIOS (VAL_DOM_ID) ENABLE;
ALTER TABLE GE_CFG_EXPED_TRAMITE ADD CONSTRAINT GE_CFG_TIP_TRA_FK FOREIGN KEY (CFG_TIP_TRA_ID) REFERENCES GE_TIPO_TRAMITE (TIP_TRA_ID) ENABLE;
ALTER TABLE GE_CFG_EXPED_TRAMITE_H ADD CONSTRAINT GE_CFG_EXP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_CFG_EXPED_SUBTRAM ADD CONSTRAINT GE_CFG_SUB_VALDOM_TIPEXP_FK FOREIGN KEY (CFG_VALDOM_TIPEXP_ID) REFERENCES GE_VALORES_DOMINIOS (VAL_DOM_ID) ENABLE;
ALTER TABLE GE_CFG_EXPED_SUBTRAM ADD CONSTRAINT GE_CFG_SUB_TIP_TRA_SUP_FK FOREIGN KEY (CFG_TIP_TRA_SUP_ID) REFERENCES GE_TIPO_TRAMITE (TIP_TRA_ID) ENABLE;
ALTER TABLE GE_CFG_EXPED_SUBTRAM ADD CONSTRAINT GE_CFG_SUB_TIP_TRA_FK FOREIGN KEY (CFG_TIP_TRA_ID) REFERENCES GE_TIPO_TRAMITE (TIP_TRA_ID) ENABLE;
ALTER TABLE GE_CFG_EXPED_SUBTRAM_H ADD CONSTRAINT GE_CFG_EXP_SUB_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
 
ALTER TABLE GE_TRAMITE_EXPED ADD CONSTRAINT GE_TRAM_EXP_EXP_FK FOREIGN KEY (TRAM_EXP_EXP_ID) REFERENCES GE_EXPEDIENTES (EXP_ID) ENABLE;
ALTER TABLE GE_TRAMITE_EXPED ADD CONSTRAINT GE_TRAM_EXP_TIP_TRA_FK FOREIGN KEY (TRAM_EXP_TIP_TRA_ID) REFERENCES GE_TIPO_TRAMITE (TIP_TRA_ID) ENABLE;
ALTER TABLE GE_TRAMITE_EXPED ADD CONSTRAINT GE_TRAM_EXP_TRAMEXPSUP_FK FOREIGN KEY (TRAM_EXP_TRAMEXPSUP_ID) REFERENCES GE_TRAMITE_EXPED (TRAM_EXP_ID) ENABLE;
ALTER TABLE GE_TRAMITE_EXPED_H ADD CONSTRAINT GE_TRAM_EXP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;


ALTER TABLE GE_PLANTILLA_DOC ADD CONSTRAINT GE_PLDOC_CFGDOC_FK FOREIGN KEY (PLDOC_CFGDOC_ID) REFERENCES GE_CFG_DOC_EXPED_TRAM (CFG_DOC_ID) ENABLE;
ALTER TABLE GE_PLANTILLA_DOC ADD CONSTRAINT GE_PLDOC_PLA_FK FOREIGN KEY (PLDOC_PLA_ID) REFERENCES GE_PLANTILLAS (PLA_ID) ENABLE;
ALTER TABLE GE_PLANTILLA_DOC_H ADD CONSTRAINT GE_PLANTILLA_DOC_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_VALORES_META_ENI ADD CONSTRAINT GE_VMETENI_TMETENI_FK FOREIGN KEY (VMETENI_TMETENI_ID) REFERENCES GE_TIPOS_METADATOS_ENI (TMETENI_ID) ENABLE;
ALTER TABLE GE_VALORES_META_ENI_H ADD CONSTRAINT GE_VAL_META_ENI_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_METADATOS_EXPEDIENTES ADD CONSTRAINT GE_METEXP_EXP_FK FOREIGN KEY (METEXP_EXP_ID) REFERENCES GE_EXPEDIENTES (EXP_ID) ENABLE;
ALTER TABLE GE_METADATOS_EXPEDIENTES ADD CONSTRAINT GE_METEXP_TMETENI_FK FOREIGN KEY (METEXP_TMETENI_ID) REFERENCES GE_TIPOS_METADATOS_ENI (TMETENI_ID) ENABLE;
ALTER TABLE GE_METADATOS_EXPEDIENTES_H ADD CONSTRAINT GE_META_EXPDTE_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_METADATOS_DOCUMENTOS ADD CONSTRAINT GE_METDOC_DOC_FK FOREIGN KEY (METDOC_DOC_ID) REFERENCES GE_DOCUMENTOS (DOC_ID) ENABLE;
ALTER TABLE GE_METADATOS_DOCUMENTOS ADD CONSTRAINT GE_METDOC_TMETENI_FK FOREIGN KEY (METDOC_TMETENI_ID) REFERENCES GE_TIPOS_METADATOS_ENI (TMETENI_ID) ENABLE;
ALTER TABLE GE_METADATOS_DOCUMENTOS_H ADD CONSTRAINT GE_META_DOC_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_AGRUP_EXPEDIENTES ADD CONSTRAINT GE_AGREXP_EXP_FK FOREIGN KEY (AGREXP_EXP_ID) REFERENCES GE_EXPEDIENTES (EXP_ID) ENABLE;
ALTER TABLE GE_AGRUP_EXPEDIENTES_H ADD CONSTRAINT GE_AGRUP_EXPDTE_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_AGRUP_DOCUMENTOS ADD CONSTRAINT GE_AGRDOC_AGREXP_FK FOREIGN KEY (AGRDOC_AGREXP_ID) REFERENCES GE_AGRUP_EXPEDIENTES (AGREXP_ID) ENABLE;
ALTER TABLE GE_AGRUP_DOCUMENTOS ADD CONSTRAINT GE_AGRDOC_DOC_FK FOREIGN KEY (AGRDOC_DOC_ID) REFERENCES GE_DOCUMENTOS (DOC_ID) ENABLE;
ALTER TABLE GE_AGRUP_DOCUMENTOS_H ADD CONSTRAINT GE_AGRUP_DOCS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_DOCUMENTOS ADD CONSTRAINT GE_DOC_TIPDOC_FK FOREIGN KEY (DOC_TIPDOC_ID) REFERENCES GE_TIPOS_DOCUMENTOS (TIP_DOC_ID) ENABLE;
ALTER TABLE GE_DOCUMENTOS ADD CONSTRAINT GE_DOC_PLA_FK FOREIGN KEY (DOC_PLA_ID) REFERENCES GE_PLANTILLAS (PLA_ID) ENABLE;
ALTER TABLE GE_DOCUMENTOS ADD CONSTRAINT DOC_ORIGINAL_FK FOREIGN KEY (DOC_ORIGINAL_ID) REFERENCES GE_DOCUMENTOS (DOC_ID) ENABLE;
ALTER TABLE GE_DOCUMENTOS_H ADD CONSTRAINT GE_DOCUMENTOS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES ADD CONSTRAINT GE_DOCEXP_DOC_FK FOREIGN KEY (DOCEXP_DOC_ID) REFERENCES GE_DOCUMENTOS (DOC_ID) ENABLE;
ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES ADD CONSTRAINT GE_DOCEXP_EXP_FK FOREIGN KEY (DOCEXP_EXP_ID) REFERENCES GE_EXPEDIENTES (EXP_ID) ENABLE;
ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES ADD CONSTRAINT GE_DOCEXP_TRAM_EXP_FK FOREIGN KEY (DOCEXP_TRAM_EXP_ID) REFERENCES GE_TRAMITE_EXPED (TRAM_EXP_ID) ENABLE;
ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES ADD CONSTRAINT GE_DOCEXP_AGRDOC_FK FOREIGN KEY (DOCEXP_AGRDOC_ID) REFERENCES GE_AGRUP_DOCUMENTOS (AGRDOC_ID) ENABLE;
ALTER TABLE GE_DOCUMENTOS_EXPEDIENTES_H ADD CONSTRAINT GE_DOCUMENTOS_EXP_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

ALTER TABLE GE_CFG_DOC_EXPED_TRAM ADD CONSTRAINT GE_CFGDOC_VALDOM_TIPEXP_FK FOREIGN KEY (CFGDOC_VALDOM_TIPEXP_ID) REFERENCES GE_VALORES_DOMINIOS (VAL_DOM_ID) ENABLE;
ALTER TABLE GE_CFG_DOC_EXPED_TRAM ADD CONSTRAINT GE_CFGDOC_VALDOM_SIT_FK FOREIGN KEY (CFGDOC_VALDOM_SIT_ID) REFERENCES GE_VALORES_DOMINIOS (VAL_DOM_ID) ENABLE;
ALTER TABLE GE_CFG_DOC_EXPED_TRAM ADD CONSTRAINT GE_CFGDOC_TIP_TRA_FK FOREIGN KEY (CFGDOC_TIP_TRA_ID) REFERENCES GE_TIPO_TRAMITE (TIP_TRA_ID) ENABLE;
ALTER TABLE GE_CFG_DOC_EXPED_TRAM ADD CONSTRAINT GE_CFGDOC_TIP_TRA_SUP_FK FOREIGN KEY (CFGDOC_TIP_TRA_SUP_ID) REFERENCES GE_TIPO_TRAMITE (TIP_TRA_ID) ENABLE;
ALTER TABLE GE_CFG_DOC_EXPED_TRAM ADD CONSTRAINT GE_CFGDOC_TIP_DOC_FK FOREIGN KEY (CFGDOC_TIP_DOC_ID) REFERENCES GE_TIPOS_DOCUMENTOS (TIP_DOC_ID) ENABLE;
ALTER TABLE GE_CFG_DOC_EXPED_TRAM_H ADD CONSTRAINT GE_CFG_DOC_EXP_TR_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;



-- Cambios en la tabla GE_DOCUMENTOS
ALTER TABLE GE_DOCUMENTOS ADD CONSTRAINT GE_DOC_T_IDEN_DOC_UK UNIQUE (T_IDEN_DOC);

ALTER TABLE GE_TIPOS_DOCUMENTOS_H ADD CONSTRAINT GE_TIPOSDOCUMENTOS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_TIPO_TRAMITE_H ADD CONSTRAINT GE_TIPO_TRAMITE_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_PLANTILLAS_H ADD CONSTRAINT GE_PLANTILLAS_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;
ALTER TABLE GE_TIPOS_METADATOS_ENI_H ADD CONSTRAINT GE_TIPOSMETADATENI_H_REVAUD_FK FOREIGN KEY (REV) REFERENCES GE_REVAUD;

SPOOL OFF;
