rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/006_07_VISTAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;
	
CREATE OR REPLACE VIEW GE_LIST_EXP_PEREXP (EXP_ID, F_CREACION, F_MODIFICACION, USU_CREACION, USU_MODIFICACION, T_NUM_EXPEDIENTE, T_NOMBRE_EXPEDIENTE, N_PRINCIPAL, T_MOTREL, PER_PER_ID) AS 
	SELECT 
		expe.EXP_ID AS EXP_ID,
		expe.F_CREACION AS F_CREACION,
		expe.F_MODIFICACION AS F_MODIFICACION,
		expe.USU_CREACION AS USU_CREACION,
		expe.USU_MODIFICACION AS USU_MODIFICACION,
		expe.T_NUMERO_EXPEDIENTE AS T_NUM_EXPEDIENTE,
		expe.T_NOMBRE_EXPEDIENTE AS T_NOMBRE_EXPEDIENTE,
		perexpe.N_PRINCIPAL AS N_PRINCIPAL,
		valormotrel.D_DESCRIPCION AS T_MOTREL,
		perexpe.PER_PER_ID AS PER_PER_ID
	FROM GE_EXPEDIENTES expe
		INNER JOIN GE_PERSONAS_EXPEDIENTES perexpe ON  perexpe.PER_EXP_ID = expe.EXP_ID
		INNER JOIN GE_VALORES_DOMINIOS valormotrel ON valormotrel.VAL_DOM_ID = perexpe.PER_VALDOM_MOTRELEXPPER_ID;
GRANT SELECT ON GE_LIST_EXP_PEREXP TO GE_ROL_GESTOR_DML;


CREATE OR REPLACE VIEW GE_LISTADO_DOCUMENTOS_EXP (DOCEXP_ID, DOC_ID, EXP_ID, D_DESCRIPCION, T_EXTENSION_FICHERO, TIP_DOC_ID, D_DESCRIPCION_TIPO, F_CREACION, F_MODIFICACION, USU_CREACION, USU_MODIFICACION, N_ORDEN, T_DOC_TRABAJO, L_EDITABLE, L_FIRMADO, L_SELLADO, L_ANONIMIZADO, L_ANONIMIZADO_PARCIAL, L_ACTIVO) AS
	SELECT
		DE.DOCEXP_ID AS DOCEXP_ID,
		DE.DOCEXP_DOC_ID AS DOC_ID,
		DE.DOCEXP_EXP_ID AS EXP_ID,
		DE.D_DESCRIPCION_DOC AS D_DESCRIPCION,
		D.T_EXTENSION_FICHERO AS T_EXTENSION_FICHERO,
		TD.TIP_DOC_ID AS TIP_DOC_ID,
		TD.D_DESCRIPCION AS D_DESCRIPCION_TIPO,
		D.F_CREACION AS F_CREACION,
		D.F_MODIFICACION AS F_MODIFICACION,
		D.USU_CREACION AS USU_CREACION,
		D.USU_MODIFICACION AS USU_MODIFICACION,
		DE.N_ORDEN AS N_ORDEN,
		DE.T_DOC_TRABAJO AS T_DOC_TRABAJO,
		D.L_EDITABLE AS L_EDITABLE,
		D.L_FIRMADO AS L_FIRMADO,
		D.L_SELLADO AS L_SELLADO,
		D.L_ANONIMIZADO AS L_ANONIMIZADO,
		D.L_ANONIMIZADO_PARCIAL AS L_ANONIMIZADO_PARCIAL,
		D.L_ACTIVO AS L_ACTIVO
	FROM GE_DOCUMENTOS_EXPEDIENTES DE 
		INNER JOIN GE_DOCUMENTOS D ON DE.DOCEXP_ID = D.DOC_ID
		INNER JOIN GE_TIPOS_DOCUMENTOS TD ON D.DOC_TIPDOC_ID = TD.TIP_DOC_ID
	WHERE DE.L_ACTIVO = 1 AND D.L_ACTIVO = 1;
GRANT SELECT ON GE_LISTADO_DOCUMENTOS_EXP      TO GE_ROL_GESTOR_DML;



SPOOL OFF;