rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/007_UNDO_01_TABLAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

DROP TABLE GE_DETALLE_EXPDTE_TRAM CASCADE CONSTRAINTS;
DROP TABLE GE_DETALLE_EXPDTE_TRAM_H CASCADE CONSTRAINTS;

DROP TABLE GE_CFG_METADATOS_TRAM CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_METADATOS_TRAM_H CASCADE CONSTRAINTS;
-------------------------------------------------------

DROP TABLE GE_CFG_PLAZOS_ESTILOS CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_PLAZOS_ESTILOS_H CASCADE CONSTRAINTS;

DROP TABLE GE_CFG_PLAZOS_EXPDTE CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_PLAZOS_EXPDTE_H CASCADE CONSTRAINTS;

DROP TABLE GE_PLAZOS_EXPDTE CASCADE CONSTRAINTS;
DROP TABLE GE_PLAZOS_EXPDTE_H CASCADE CONSTRAINTS;
-------------------------------------------------------

DROP TABLE GE_CFG_PLAZOS_AUT CASCADE CONSTRAINTS;
DROP TABLE GE_CFG_PLAZOS_AUT_H CASCADE CONSTRAINTS;


ALTER TABLE GE_EXPEDIENTES_H MODIFY (T_MOTIVO VARCHAR2(255 CHAR));
-------------------------------------------------------

DROP TABLE GE_DOCUMENTOS_EXPED_TRAMITES   CASCADE CONSTRAINTS;
DROP TABLE GE_DOCUMENTOS_EXPED_TRAMITES_H CASCADE CONSTRAINTS;
-------------------------------------------------------

ALTER TABLE GE_SUJETOS_OBLIGADOS ADD (T_ABREVIATURA_TMP VARCHAR2(20 CHAR));
ALTER TABLE GE_SUJETOS_OBLIGADOS MODIFY (T_ABREVIATURA_3 VARCHAR2(20 CHAR));
UPDATE GE_SUJETOS_OBLIGADOS SET T_ABREVIATURA_TMP = T_ABREVIATURA_3, T_ABREVIATURA_3 = T_ABREVIATURA_1, T_ABREVIATURA_1 = '';
ALTER TABLE GE_SUJETOS_OBLIGADOS MODIFY (T_ABREVIATURA_1 VARCHAR2(5 CHAR));
UPDATE GE_SUJETOS_OBLIGADOS SET T_ABREVIATURA_1 = T_ABREVIATURA_TMP;
ALTER TABLE GE_SUJETOS_OBLIGADOS DROP (T_ABREVIATURA_TMP);

ALTER TABLE GE_SUJETOS_OBLIGADOS_H ADD (T_ABREVIATURA_TMP VARCHAR2(20 CHAR));
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (T_ABREVIATURA_3 VARCHAR2(20 CHAR));
UPDATE GE_SUJETOS_OBLIGADOS_H SET T_ABREVIATURA_TMP = T_ABREVIATURA_3, T_ABREVIATURA_3 = T_ABREVIATURA_1, T_ABREVIATURA_1 = '';
ALTER TABLE GE_SUJETOS_OBLIGADOS_H MODIFY (T_ABREVIATURA_1 VARCHAR2(5 CHAR));
UPDATE GE_SUJETOS_OBLIGADOS_H SET T_ABREVIATURA_1 = T_ABREVIATURA_TMP;
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP (T_ABREVIATURA_TMP);


ALTER TABLE GE_SUJETOS_OBLIGADOS   DROP (SUJ_VALDOM_VIACOM_ID, SUJ_VALDOM_TIPOLO_ID);
ALTER TABLE GE_SUJETOS_OBLIGADOS_H DROP (SUJ_VALDOM_VIACOM_ID, SUJ_VALDOM_TIPOLO_ID);




ALTER TABLE GE_DETALLE_EXPDTE_TRAM ADD INT_ID NUMBER(19,0);
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H ADD INT_ID NUMBER(19,0);

ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN DETEXPTRAM_VALDOM_INT_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN DETEXPTRAM_PER_INT_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM DROP COLUMN DETEXPTRAM_SUJOBL_INT_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN DETEXPTRAM_VALDOM_INT_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN DETEXPTRAM_PER_INT_ID;
ALTER TABLE GE_DETALLE_EXPDTE_TRAM_H DROP COLUMN DETEXPTRAM_SUJOBL_INT_ID;

SPOOL OFF;
