rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/007_UNDO_05_INSERTS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_INT');
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'CAN_SAL');
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'SENT_RESOL');
DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA');

DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_INT';
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'CAN_SAL';
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'SENT_RESOL';
DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'TIP_PLA';
----------------------------------------------------------------------------------------------------------------------------

DELETE FROM GE_VALORES_DOMINIOS WHERE VALDOM_DOM_ID IN (SELECT DOM_ID FROM GE_DOMINIOS WHERE C_CODIGO = 'PLAZOS');

DELETE FROM GE_DOMINIOS WHERE C_CODIGO = 'PLAZOS';
----------------------------------------------------------------------------------------------------------------------------
UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = NULL, D_IDENTIF_INTERESADO = NULL, D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'TRDPD') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');

UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = NULL, D_IDENTIF_INTERESADO = NULL, D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'TRA') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCE');

UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = NULL, D_IDENTIF_INTERESADO = NULL, D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'TRDPD') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');

UPDATE GE_CFG_METADATOS_TRAM SET D_TIPO_INTERESADO = NULL, D_IDENTIF_INTERESADO = NULL, D_CANAL_SALIDA = NULL, D_DATOS_CANAL_SALIDA = NULL
WHERE METTRAM_TIPTRAM_ID = (SELECT TIP_TRA_ID FROM GE_TIPO_TRAMITE WHERE T_CODIGO = 'TRA') 
AND METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM GE_VALORES_DOMINIOS WHERE C_CODIGO = 'RCO');

----------------------------------------------------------------------------------------------------------------------------

DELETE FROM GE_PERMISOS_PERFILES  WHERE PERMPERF_PERF_ID = (SELECT PER_ID FROM GE_PERFILES WHERE c_codigo = 'ADMIN') AND PERMPERF_PERM_ID = (SELECT PER_ID FROM GE_PERMISOS WHERE c_codigo = 'NEW_EXPDOCGEN');
DELETE FROM GE_PERMISOS WHERE C_CODIGO = 'NEW_EXPDOCGEN';


DELETE FROM GE_CFG_METADATOS_TRAM  WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCE')
AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'REV');

DELETE FROM GE_CFG_METADATOS_TRAM  WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCO')
AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'REV');

DELETE FROM GE_CFG_METADATOS_TRAM  WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCE')
AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'FIRM');

DELETE FROM GE_CFG_METADATOS_TRAM  WHERE METTRAM_VALDOM_TIPEXP_ID = (SELECT VAL_DOM_ID FROM ge_valores_dominios WHERE c_codigo = 'RCO')
AND METTRAM_TIPTRAM_ID = (SELECT tip_tra_id FROM ge_tipo_tramite WHERE t_codigo = 'FIRM');


SPOOL OFF;
