rem  Comprobación UTF8: Esto aparece en árabe: أنا تظهر في اللغة العربية

SPOOL logs/007_UNDO_07_VISTAS.LOG
ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;
	

-- Versión anterior, sin columna T_IDEN_DOC
CREATE OR REPLACE VIEW GE_LISTADO_DOCUMENTOS_EXP (DOCEXP_ID, DOC_ID, EXP_ID, T_IDEN_DOC, D_DESCRIPCION, T_EXTENSION_FICHERO, TIP_DOC_ID, D_DESCRIPCION_TIPO, F_CREACION, F_MODIFICACION, USU_CREACION, USU_MODIFICACION, N_ORDEN, T_DOC_TRABAJO, L_EDITABLE, L_FIRMADO, L_SELLADO, L_ANONIMIZADO, L_ANONIMIZADO_PARCIAL, L_ACTIVO) AS
	SELECT
		DE.DOCEXP_ID AS DOCEXP_ID,
		DE.DOCEXP_DOC_ID AS DOC_ID,
		DE.DOCEXP_EXP_ID AS EXP_ID,
		D.T_IDEN_DOC AS T_IDEN_DOC,
		DE.D_DESCRIPCION_DOC AS D_DESCRIPCION,
		D.T_EXTENSION_FICHERO AS T_EXTENSION_FICHERO,
		TD.TIP_DOC_ID AS TIP_DOC_ID,
		TD.D_DESCRIPCION AS D_DESCRIPCION_TIPO,
		D.F_CREACION AS F_CREACION,
		D.F_MODIFICACION AS F_MODIFICACION,
		D.USU_CREACION AS USU_CREACION,
		D.USU_MODIFICACION AS USU_MODIFICACION,
		DE.N_ORDEN AS N_ORDEN,
		DE.T_DOC_TRABAJO AS T_DOC_TRABAJO,
		D.L_EDITABLE AS L_EDITABLE,
		D.L_FIRMADO AS L_FIRMADO,
		D.L_SELLADO AS L_SELLADO,
		D.L_ANONIMIZADO AS L_ANONIMIZADO,
		D.L_ANONIMIZADO_PARCIAL AS L_ANONIMIZADO_PARCIAL,
		D.L_ACTIVO AS L_ACTIVO
	FROM GE_DOCUMENTOS_EXPEDIENTES DE 
		INNER JOIN GE_DOCUMENTOS D ON DE.DOCEXP_ID = D.DOC_ID
		INNER JOIN GE_TIPOS_DOCUMENTOS TD ON D.DOC_TIPDOC_ID = TD.TIP_DOC_ID
	WHERE DE.L_ACTIVO = 1 AND D.L_ACTIVO = 1;


DROP VIEW GE_LISTADO_DOCUMENTOS_EXP_TRAM;




SPOOL OFF;
