
SPOOL 00_ESQUEMAS.LOG

ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

-- TABLESPACE
CREATE SMALLFILE TABLESPACE GESTOR_DAT LOGGING DATAFILE '/u01/app/oracle/oradata/MORAL/gestor_dat01.dbf' SIZE 100M EXTENT MANAGEMENT LOCAL	SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE GESTOR_IND LOGGING DATAFILE '/u01/app/oracle/oradata/MORAL/gestor_ind01.dbf' SIZE 100M EXTENT MANAGEMENT LOCAL	SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE GESTOR_BLOB LOGGING DATAFILE '/u01/app/oracle/oradata/MORAL/gestor_blob01.dbf' SIZE 100M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE GESTOR_CLOB LOGGING DATAFILE '/u01/app/oracle/oradata/MORAL/gestor_clob01.dbf' SIZE 100M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE SMALLFILE TABLESPACE GESTOR_NLOB LOGGING DATAFILE '/u01/app/oracle/oradata/MORAL/gestor_nlob01.dbf' SIZE 50M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


-- ROLES
-- Role de DML de objetos
CREATE ROLE GE_ROL_GESTOR_DDL;
GRANT CONNECT TO GE_ROL_GESTOR_DDL;
GRANT RESOURCE TO GE_ROL_GESTOR_DDL;
GRANT CREATE VIEW TO GE_ROL_GESTOR_DDL;
-- Role de manipulación de los datos
CREATE ROLE GE_ROL_GESTOR_DML;
GRANT CREATE SESSION TO GE_ROL_GESTOR_DML;
GRANT ALTER SESSION TO GE_ROL_GESTOR_DML;
GRANT CREATE SYNONYM TO GE_ROL_GESTOR_DML;

--USERS
-- Propietario del ESQUEMA
CREATE USER GESTOR PROFILE DEFAULT IDENTIFIED BY "X_1_GESTOR" DEFAULT TABLESPACE GESTOR_DAT TEMPORARY TABLESPACE TEMP 
	QUOTA UNLIMITED ON GESTOR_DAT 
	QUOTA UNLIMITED ON GESTOR_IND
	QUOTA UNLIMITED ON GESTOR_BLOB
	QUOTA UNLIMITED ON GESTOR_CLOB
	QUOTA UNLIMITED ON GESTOR_NLOB
	ACCOUNT UNLOCK ;
GRANT GE_ROL_GESTOR_DDL TO GESTOR ;

-- Usuario de CONEXION de la aplicación.
CREATE USER GESTOR_APP PROFILE DEFAULT IDENTIFIED BY "GE_APP_XXX12" DEFAULT TABLESPACE GESTOR_DAT TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON GESTOR_DAT
	QUOTA UNLIMITED ON GESTOR_IND
	QUOTA UNLIMITED ON GESTOR_BLOB
	QUOTA UNLIMITED ON GESTOR_CLOB
	QUOTA UNLIMITED ON GESTOR_NLOB
	ACCOUNT UNLOCK ;
GRANT GE_ROL_GESTOR_DML TO GESTOR_APP ;

-- Usuario de WEB  de la aplicación
CREATE USER GESTOR_WEB PROFILE DEFAULT IDENTIFIED BY "GE_WEB_XXX34" DEFAULT TABLESPACE GESTOR_DAT TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON GESTOR_DAT
	QUOTA UNLIMITED ON GESTOR_IND
	QUOTA UNLIMITED ON GESTOR_BLOB
	QUOTA UNLIMITED ON GESTOR_CLOB
	QUOTA UNLIMITED ON GESTOR_NLOB
	ACCOUNT UNLOCK ;
GRANT GE_ROL_GESTOR_DML TO GESTOR_WEB ;

PROMPT *****************************************
PROMPT * FIN DE LA INSTALACION    CREACIÓN DEL *
PROMPT * ESQUEMA    GESTOR  GESTOR             *
PROMPT *****************************************

SPOOL OFF;

